package nc.ccas.gasel.model.pe.auto;

/** Class _AbsenceAM was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AbsenceAM extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 8540597248545233579L;
	public static final String DEBUT_PROPERTY = "debut";
    public static final String FIN_PROPERTY = "fin";
    public static final String ASSISTANTE_MATERNELLE_PROPERTY = "assistanteMaternelle";

    public static final String ID_PK_COLUMN = "id";

    public void setDebut(java.util.Date debut) {
        writeProperty("debut", debut);
    }
    public java.util.Date getDebut() {
        return (java.util.Date)readProperty("debut");
    }
    
    
    public void setFin(java.util.Date fin) {
        writeProperty("fin", fin);
    }
    public java.util.Date getFin() {
        return (java.util.Date)readProperty("fin");
    }
    
    
    public void setAssistanteMaternelle(nc.ccas.gasel.model.pe.AssistanteMaternelle assistanteMaternelle) {
        setToOneTarget("assistanteMaternelle", assistanteMaternelle, true);
    }

    public nc.ccas.gasel.model.pe.AssistanteMaternelle getAssistanteMaternelle() {
        return (nc.ccas.gasel.model.pe.AssistanteMaternelle)readProperty("assistanteMaternelle");
    } 
    
    
}
