package nc.ccas.gasel.model.pe.auto;

/** Class _AidePaiement was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AidePaiement extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -8688553665393021230L;
	public static final String MONTANT_AIDE_PROPERTY = "montantAide";
    public static final String MONTANT_PRIS_EN_CHARGE_PROPERTY = "montantPrisEnCharge";
    public static final String ENFANT_PROPERTY = "enfant";
    public static final String ORGANISME_PROPERTY = "organisme";

    public static final String ID_PK_COLUMN = "id";

    public void setMontantAide(Integer montantAide) {
        writeProperty("montantAide", montantAide);
    }
    public Integer getMontantAide() {
        return (Integer)readProperty("montantAide");
    }
    
    
    public void setMontantPrisEnCharge(Integer montantPrisEnCharge) {
        writeProperty("montantPrisEnCharge", montantPrisEnCharge);
    }
    public Integer getMontantPrisEnCharge() {
        return (Integer)readProperty("montantPrisEnCharge");
    }
    
    
    public void setEnfant(nc.ccas.gasel.model.pe.EnfantRAM enfant) {
        setToOneTarget("enfant", enfant, true);
    }

    public nc.ccas.gasel.model.pe.EnfantRAM getEnfant() {
        return (nc.ccas.gasel.model.pe.EnfantRAM)readProperty("enfant");
    } 
    
    
    public void setOrganisme(nc.ccas.gasel.model.pe.enums.OrganismeSocial organisme) {
        setToOneTarget("organisme", organisme, true);
    }

    public nc.ccas.gasel.model.pe.enums.OrganismeSocial getOrganisme() {
        return (nc.ccas.gasel.model.pe.enums.OrganismeSocial)readProperty("organisme");
    } 
    
    
}
