package nc.ccas.gasel.model.pe.auto;

import java.util.List;

import nc.ccas.gasel.model.pe.AssistanteMaternelle;

/** Class _AspectDossierAM was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AspectDossierAM extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6803234659700335475L;
	public static final String ALERTE_ASSURANCE_PROPERTY = "alerteAssurance";
    public static final String ASSURANCE_PROPERTY = "assurance";
    public static final String ASSISTANTES_MATERNELLE_PROPERTY = "assistantesMaternelle";
    public static final String DOSSIER_PROPERTY = "dossier";

    public static final String DOSSIER_ID_PK_COLUMN = "dossier_id";

    public void setAlerteAssurance(Boolean alerteAssurance) {
        writeProperty("alerteAssurance", alerteAssurance);
    }
    public Boolean getAlerteAssurance() {
        return (Boolean)readProperty("alerteAssurance");
    }
    
    
    public void setAssurance(java.util.Date assurance) {
        writeProperty("assurance", assurance);
    }
    public java.util.Date getAssurance() {
        return (java.util.Date)readProperty("assurance");
    }
    
    
    public void addToAssistantesMaternelle(nc.ccas.gasel.model.pe.AssistanteMaternelle obj) {
        addToManyTarget("assistantesMaternelle", obj, true);
    }
    public void removeFromAssistantesMaternelle(nc.ccas.gasel.model.pe.AssistanteMaternelle obj) {
        removeToManyTarget("assistantesMaternelle", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pe.AssistanteMaternelle> getAssistantesMaternelle() {
        return (List<AssistanteMaternelle>)readProperty("assistantesMaternelle");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.core.Dossier dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.core.Dossier getDossier() {
        return (nc.ccas.gasel.model.core.Dossier)readProperty("dossier");
    } 
    
    
}
