package nc.ccas.gasel.model.pe.auto;

import java.util.List;

import nc.ccas.gasel.model.pe.AbsenceAM;
import nc.ccas.gasel.model.pe.FormationAM;
import nc.ccas.gasel.model.pe.Garde;
import nc.ccas.gasel.model.pe.IntegrationRAM;

/** Class _AssistanteMaternelle was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AssistanteMaternelle extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 7289018122660464158L;
	public static final String AGREMENT_PROPERTY = "agrement";
    public static final String ASSURANCE_LOGEMENT_PROPERTY = "assuranceLogement";
    public static final String ASSURANCE_VEHICULE_PROPERTY = "assuranceVehicule";
    public static final String CASIER_JUDICIAIRE_PROPERTY = "casierJudiciaire";
    public static final String CERTIFICAT_MEDICAL_PROPERTY = "certificatMedical";
    public static final String DERNIERE_VISITE_PROPERTY = "derniereVisite";
    public static final String HEURE_DEBUT_TRAVAIL_PROPERTY = "heureDebutTravail";
    public static final String HEURE_FIN_TRAVAIL_PROPERTY = "heureFinTravail";
    public static final String MOTIF_NB_ENFANTS_SOUHAITES_PROPERTY = "motifNbEnfantsSouhaites";
    public static final String NB_ENFANTS_SOUHAITES_PROPERTY = "nbEnfantsSouhaites";
    public static final String PERMIS_CONDUIRE_PROPERTY = "permisConduire";
    public static final String RESPONSABILITE_CIVILE_PROPERTY = "responsabiliteCivile";
    public static final String ABSENCES_AM_PROPERTY = "absencesAM";
    public static final String DOSSIER_PROPERTY = "dossier";
    public static final String FORMATIONS_AM_PROPERTY = "formationsAM";
    public static final String GARDES_PROPERTY = "gardes";
    public static final String INTEGRATIONS_PROPERTY = "integrations";
    public static final String PERSONNE_PROPERTY = "personne";
    public static final String REFERENT_PROPERTY = "referent";

    public static final String ID_PK_COLUMN = "id";

    public void setAgrement(java.util.Date agrement) {
        writeProperty("agrement", agrement);
    }
    public java.util.Date getAgrement() {
        return (java.util.Date)readProperty("agrement");
    }
    
    
    public void setAssuranceLogement(java.util.Date assuranceLogement) {
        writeProperty("assuranceLogement", assuranceLogement);
    }
    public java.util.Date getAssuranceLogement() {
        return (java.util.Date)readProperty("assuranceLogement");
    }
    
    
    public void setAssuranceVehicule(java.util.Date assuranceVehicule) {
        writeProperty("assuranceVehicule", assuranceVehicule);
    }
    public java.util.Date getAssuranceVehicule() {
        return (java.util.Date)readProperty("assuranceVehicule");
    }
    
    
    public void setCasierJudiciaire(java.util.Date casierJudiciaire) {
        writeProperty("casierJudiciaire", casierJudiciaire);
    }
    public java.util.Date getCasierJudiciaire() {
        return (java.util.Date)readProperty("casierJudiciaire");
    }
    
    
    public void setCertificatMedical(java.util.Date certificatMedical) {
        writeProperty("certificatMedical", certificatMedical);
    }
    public java.util.Date getCertificatMedical() {
        return (java.util.Date)readProperty("certificatMedical");
    }
    
    
    public void setDerniereVisite(java.util.Date derniereVisite) {
        writeProperty("derniereVisite", derniereVisite);
    }
    public java.util.Date getDerniereVisite() {
        return (java.util.Date)readProperty("derniereVisite");
    }
    
    
    public void setHeureDebutTravail(String heureDebutTravail) {
        writeProperty("heureDebutTravail", heureDebutTravail);
    }
    public String getHeureDebutTravail() {
        return (String)readProperty("heureDebutTravail");
    }
    
    
    public void setHeureFinTravail(String heureFinTravail) {
        writeProperty("heureFinTravail", heureFinTravail);
    }
    public String getHeureFinTravail() {
        return (String)readProperty("heureFinTravail");
    }
    
    
    public void setMotifNbEnfantsSouhaites(String motifNbEnfantsSouhaites) {
        writeProperty("motifNbEnfantsSouhaites", motifNbEnfantsSouhaites);
    }
    public String getMotifNbEnfantsSouhaites() {
        return (String)readProperty("motifNbEnfantsSouhaites");
    }
    
    
    public void setNbEnfantsSouhaites(Integer nbEnfantsSouhaites) {
        writeProperty("nbEnfantsSouhaites", nbEnfantsSouhaites);
    }
    public Integer getNbEnfantsSouhaites() {
        return (Integer)readProperty("nbEnfantsSouhaites");
    }
    
    
    public void setPermisConduire(Boolean permisConduire) {
        writeProperty("permisConduire", permisConduire);
    }
    public Boolean getPermisConduire() {
        return (Boolean)readProperty("permisConduire");
    }
    
    
    public void setResponsabiliteCivile(java.util.Date responsabiliteCivile) {
        writeProperty("responsabiliteCivile", responsabiliteCivile);
    }
    public java.util.Date getResponsabiliteCivile() {
        return (java.util.Date)readProperty("responsabiliteCivile");
    }
    
    
    public void addToAbsencesAM(nc.ccas.gasel.model.pe.AbsenceAM obj) {
        addToManyTarget("absencesAM", obj, true);
    }
    public void removeFromAbsencesAM(nc.ccas.gasel.model.pe.AbsenceAM obj) {
        removeToManyTarget("absencesAM", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pe.AbsenceAM> getAbsencesAM() {
        return (List<AbsenceAM>)readProperty("absencesAM");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.pe.AspectDossierAM dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.pe.AspectDossierAM getDossier() {
        return (nc.ccas.gasel.model.pe.AspectDossierAM)readProperty("dossier");
    } 
    
    
    public void addToFormationsAM(nc.ccas.gasel.model.pe.FormationAM obj) {
        addToManyTarget("formationsAM", obj, true);
    }
    public void removeFromFormationsAM(nc.ccas.gasel.model.pe.FormationAM obj) {
        removeToManyTarget("formationsAM", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pe.FormationAM> getFormationsAM() {
        return (List<FormationAM>)readProperty("formationsAM");
    }
    
    
    public void addToGardes(nc.ccas.gasel.model.pe.Garde obj) {
        addToManyTarget("gardes", obj, true);
    }
    public void removeFromGardes(nc.ccas.gasel.model.pe.Garde obj) {
        removeToManyTarget("gardes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pe.Garde> getGardes() {
        return (List<Garde>)readProperty("gardes");
    }
    
    
    public void addToIntegrations(nc.ccas.gasel.model.pe.IntegrationRAM obj) {
        addToManyTarget("integrations", obj, true);
    }
    public void removeFromIntegrations(nc.ccas.gasel.model.pe.IntegrationRAM obj) {
        removeToManyTarget("integrations", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pe.IntegrationRAM> getIntegrations() {
        return (List<IntegrationRAM>)readProperty("integrations");
    }
    
    
    public void setPersonne(nc.ccas.gasel.model.core.Personne personne) {
        setToOneTarget("personne", personne, true);
    }

    public nc.ccas.gasel.model.core.Personne getPersonne() {
        return (nc.ccas.gasel.model.core.Personne)readProperty("personne");
    } 
    
    
    public void setReferent(nc.ccas.gasel.model.core.Utilisateur referent) {
        setToOneTarget("referent", referent, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getReferent() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("referent");
    } 
    
    
}
