package nc.ccas.gasel.model.pe.auto;

/** Class _AutorisationEnfant was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AutorisationEnfant extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 4800927542048974036L;
	public static final String ACCEPTE_PROPERTY = "accepte";
    public static final String AUTORISATION_PARENTALE_PROPERTY = "autorisationParentale";
    public static final String ENFANT_PROPERTY = "enfant";

    public static final String ID_PK_COLUMN = "id";

    public void setAccepte(Boolean accepte) {
        writeProperty("accepte", accepte);
    }
    public Boolean getAccepte() {
        return (Boolean)readProperty("accepte");
    }
    
    
    public void setAutorisationParentale(nc.ccas.gasel.model.pe.enums.AutorisationParentale autorisationParentale) {
        setToOneTarget("autorisationParentale", autorisationParentale, true);
    }

    public nc.ccas.gasel.model.pe.enums.AutorisationParentale getAutorisationParentale() {
        return (nc.ccas.gasel.model.pe.enums.AutorisationParentale)readProperty("autorisationParentale");
    } 
    
    
    public void setEnfant(nc.ccas.gasel.model.pe.EnfantRAM enfant) {
        setToOneTarget("enfant", enfant, true);
    }

    public nc.ccas.gasel.model.pe.EnfantRAM getEnfant() {
        return (nc.ccas.gasel.model.pe.EnfantRAM)readProperty("enfant");
    } 
    
    
}
