package nc.ccas.gasel.model.pe.auto;

import java.util.List;

import nc.ccas.gasel.model.pe.AbsenceEnfant;
import nc.ccas.gasel.model.pe.AidePaiement;
import nc.ccas.gasel.model.pe.AutorisationEnfant;
import nc.ccas.gasel.model.pe.Garde;

/** Class _EnfantRAM was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _EnfantRAM extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2666356478486636232L;
	public static final String CERTIFICAT_MEDICAL_PROPERTY = "certificatMedical";
    public static final String DERNIER_CONTACT_PROPERTY = "dernierContact";
    public static final String ENTREE_PROPERTY = "entree";
    public static final String SORTIE_PROPERTY = "sortie";
    public static final String ABSENCES_PROPERTY = "absences";
    public static final String AIDES_PAIEMENT_PROPERTY = "aidesPaiement";
    public static final String AUTORISATIONS_PROPERTY = "autorisations";
    public static final String DOSSIER_PROPERTY = "dossier";
    public static final String GARDES_PROPERTY = "gardes";
    public static final String HANDICAP_PROPERTY = "handicap";
    public static final String PERSONNE_PROPERTY = "personne";
    public static final String QUARTIER_TRAVAIL_PARENT_PROPERTY = "quartierTravailParent";

    public static final String ID_PK_COLUMN = "id";

    public void setCertificatMedical(Boolean certificatMedical) {
        writeProperty("certificatMedical", certificatMedical);
    }
    public Boolean getCertificatMedical() {
        return (Boolean)readProperty("certificatMedical");
    }
    
    
    public void setDernierContact(java.util.Date dernierContact) {
        writeProperty("dernierContact", dernierContact);
    }
    public java.util.Date getDernierContact() {
        return (java.util.Date)readProperty("dernierContact");
    }
    
    
    public void setEntree(java.util.Date entree) {
        writeProperty("entree", entree);
    }
    public java.util.Date getEntree() {
        return (java.util.Date)readProperty("entree");
    }
    
    
    public void setSortie(java.util.Date sortie) {
        writeProperty("sortie", sortie);
    }
    public java.util.Date getSortie() {
        return (java.util.Date)readProperty("sortie");
    }
    
    
    public void addToAbsences(nc.ccas.gasel.model.pe.AbsenceEnfant obj) {
        addToManyTarget("absences", obj, true);
    }
    public void removeFromAbsences(nc.ccas.gasel.model.pe.AbsenceEnfant obj) {
        removeToManyTarget("absences", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pe.AbsenceEnfant> getAbsences() {
        return (List<AbsenceEnfant>)readProperty("absences");
    }
    
    
    public void addToAidesPaiement(nc.ccas.gasel.model.pe.AidePaiement obj) {
        addToManyTarget("aidesPaiement", obj, true);
    }
    public void removeFromAidesPaiement(nc.ccas.gasel.model.pe.AidePaiement obj) {
        removeToManyTarget("aidesPaiement", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pe.AidePaiement> getAidesPaiement() {
        return (List<AidePaiement>)readProperty("aidesPaiement");
    }
    
    
    public void addToAutorisations(nc.ccas.gasel.model.pe.AutorisationEnfant obj) {
        addToManyTarget("autorisations", obj, true);
    }
    public void removeFromAutorisations(nc.ccas.gasel.model.pe.AutorisationEnfant obj) {
        removeToManyTarget("autorisations", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pe.AutorisationEnfant> getAutorisations() {
        return (List<AutorisationEnfant>)readProperty("autorisations");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.pe.AspectDossierEnfant dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.pe.AspectDossierEnfant getDossier() {
        return (nc.ccas.gasel.model.pe.AspectDossierEnfant)readProperty("dossier");
    } 
    
    
    public void addToGardes(nc.ccas.gasel.model.pe.Garde obj) {
        addToManyTarget("gardes", obj, true);
    }
    public void removeFromGardes(nc.ccas.gasel.model.pe.Garde obj) {
        removeToManyTarget("gardes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pe.Garde> getGardes() {
        return (List<Garde>)readProperty("gardes");
    }
    
    
    public void setHandicap(nc.ccas.gasel.model.pe.HandicapPE handicap) {
        setToOneTarget("handicap", handicap, true);
    }

    public nc.ccas.gasel.model.pe.HandicapPE getHandicap() {
        return (nc.ccas.gasel.model.pe.HandicapPE)readProperty("handicap");
    } 
    
    
    public void setPersonne(nc.ccas.gasel.model.core.Personne personne) {
        setToOneTarget("personne", personne, true);
    }

    public nc.ccas.gasel.model.core.Personne getPersonne() {
        return (nc.ccas.gasel.model.core.Personne)readProperty("personne");
    } 
    
    
    public void setQuartierTravailParent(nc.ccas.gasel.model.mairie.Quartier quartierTravailParent) {
        setToOneTarget("quartierTravailParent", quartierTravailParent, true);
    }

    public nc.ccas.gasel.model.mairie.Quartier getQuartierTravailParent() {
        return (nc.ccas.gasel.model.mairie.Quartier)readProperty("quartierTravailParent");
    } 
    
    
}
