package nc.ccas.gasel.model.pe.auto;

/** Class _FormationAM was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _FormationAM extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6267386534280273553L;
	public static final String ATTESTATION_EMISE_PROPERTY = "attestationEmise";
    public static final String OBTENTION_PROPERTY = "obtention";
    public static final String ASSISTANTE_MATERNELLE_PROPERTY = "assistanteMaternelle";
    public static final String FORMATION_PROPERTY = "formation";

    public static final String ID_PK_COLUMN = "id";

    public void setAttestationEmise(Boolean attestationEmise) {
        writeProperty("attestationEmise", attestationEmise);
    }
    public Boolean getAttestationEmise() {
        return (Boolean)readProperty("attestationEmise");
    }
    
    
    public void setObtention(java.util.Date obtention) {
        writeProperty("obtention", obtention);
    }
    public java.util.Date getObtention() {
        return (java.util.Date)readProperty("obtention");
    }
    
    
    public void setAssistanteMaternelle(nc.ccas.gasel.model.pe.AssistanteMaternelle assistanteMaternelle) {
        setToOneTarget("assistanteMaternelle", assistanteMaternelle, true);
    }

    public nc.ccas.gasel.model.pe.AssistanteMaternelle getAssistanteMaternelle() {
        return (nc.ccas.gasel.model.pe.AssistanteMaternelle)readProperty("assistanteMaternelle");
    } 
    
    
    public void setFormation(nc.ccas.gasel.model.pe.enums.Formation formation) {
        setToOneTarget("formation", formation, true);
    }

    public nc.ccas.gasel.model.pe.enums.Formation getFormation() {
        return (nc.ccas.gasel.model.pe.enums.Formation)readProperty("formation");
    } 
    
    
}
