package nc.ccas.gasel.model.pe.auto;

/** Class _HandicapPE was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _HandicapPE extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1883792725302403273L;
	public static final String LIBELLE_PROPERTY = "libelle";
    public static final String PONDERATION_PROPERTY = "ponderation";
    public static final String ENFANT_PROPERTY = "enfant";

    public static final String ID_PK_COLUMN = "id";

    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setPonderation(Integer ponderation) {
        writeProperty("ponderation", ponderation);
    }
    public Integer getPonderation() {
        return (Integer)readProperty("ponderation");
    }
    
    
    public void setEnfant(nc.ccas.gasel.model.pe.EnfantRAM enfant) {
        setToOneTarget("enfant", enfant, true);
    }

    public nc.ccas.gasel.model.pe.EnfantRAM getEnfant() {
        return (nc.ccas.gasel.model.pe.EnfantRAM)readProperty("enfant");
    } 
    
    
}
