package nc.ccas.gasel.model.pe.enums.auto;

/** Class _ModeGarde was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ModeGarde extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6927626342921985337L;
	public static final String ACTIF_PROPERTY = "actif";
    public static final String DIMANCHE_AM_PROPERTY = "dimancheAM";
    public static final String DIMANCHE_MATIN_PROPERTY = "dimancheMatin";
    public static final String DIMANCHE_MIDI_PROPERTY = "dimancheMidi";
    public static final String DIMANCHE_SOIR_PROPERTY = "dimancheSoir";
    public static final String JEUDI_AM_PROPERTY = "jeudiAM";
    public static final String JEUDI_MATIN_PROPERTY = "jeudiMatin";
    public static final String JEUDI_MIDI_PROPERTY = "jeudiMidi";
    public static final String JEUDI_SOIR_PROPERTY = "jeudiSoir";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String LOCKED_PROPERTY = "locked";
    public static final String LUNDI_AM_PROPERTY = "lundiAM";
    public static final String LUNDI_MATIN_PROPERTY = "lundiMatin";
    public static final String LUNDI_MIDI_PROPERTY = "lundiMidi";
    public static final String LUNDI_SOIR_PROPERTY = "lundiSoir";
    public static final String MARDI_AM_PROPERTY = "mardiAM";
    public static final String MARDI_MATIN_PROPERTY = "mardiMatin";
    public static final String MARDI_MIDI_PROPERTY = "mardiMidi";
    public static final String MARDI_SOIR_PROPERTY = "mardiSoir";
    public static final String MERCREDI_AM_PROPERTY = "mercrediAM";
    public static final String MERCREDI_MATIN_PROPERTY = "mercrediMatin";
    public static final String MERCREDI_MIDI_PROPERTY = "mercrediMidi";
    public static final String MERCREDI_SOIR_PROPERTY = "mercrediSoir";
    public static final String SAMEDI_AM_PROPERTY = "samediAM";
    public static final String SAMEDI_MATIN_PROPERTY = "samediMatin";
    public static final String SAMEDI_MIDI_PROPERTY = "samediMidi";
    public static final String SAMEDI_SOIR_PROPERTY = "samediSoir";
    public static final String VENDREDI_AM_PROPERTY = "vendrediAM";
    public static final String VENDREDI_MATIN_PROPERTY = "vendrediMatin";
    public static final String VENDREDI_MIDI_PROPERTY = "vendrediMidi";
    public static final String VENDREDI_SOIR_PROPERTY = "vendrediSoir";

    public static final String ID_PK_COLUMN = "id";

    public void setActif(Boolean actif) {
        writeProperty("actif", actif);
    }
    public Boolean getActif() {
        return (Boolean)readProperty("actif");
    }
    
    
    public void setDimancheAM(Boolean dimancheAM) {
        writeProperty("dimancheAM", dimancheAM);
    }
    public Boolean getDimancheAM() {
        return (Boolean)readProperty("dimancheAM");
    }
    
    
    public void setDimancheMatin(Boolean dimancheMatin) {
        writeProperty("dimancheMatin", dimancheMatin);
    }
    public Boolean getDimancheMatin() {
        return (Boolean)readProperty("dimancheMatin");
    }
    
    
    public void setDimancheMidi(Boolean dimancheMidi) {
        writeProperty("dimancheMidi", dimancheMidi);
    }
    public Boolean getDimancheMidi() {
        return (Boolean)readProperty("dimancheMidi");
    }
    
    
    public void setDimancheSoir(Boolean dimancheSoir) {
        writeProperty("dimancheSoir", dimancheSoir);
    }
    public Boolean getDimancheSoir() {
        return (Boolean)readProperty("dimancheSoir");
    }
    
    
    public void setJeudiAM(Boolean jeudiAM) {
        writeProperty("jeudiAM", jeudiAM);
    }
    public Boolean getJeudiAM() {
        return (Boolean)readProperty("jeudiAM");
    }
    
    
    public void setJeudiMatin(Boolean jeudiMatin) {
        writeProperty("jeudiMatin", jeudiMatin);
    }
    public Boolean getJeudiMatin() {
        return (Boolean)readProperty("jeudiMatin");
    }
    
    
    public void setJeudiMidi(Boolean jeudiMidi) {
        writeProperty("jeudiMidi", jeudiMidi);
    }
    public Boolean getJeudiMidi() {
        return (Boolean)readProperty("jeudiMidi");
    }
    
    
    public void setJeudiSoir(Boolean jeudiSoir) {
        writeProperty("jeudiSoir", jeudiSoir);
    }
    public Boolean getJeudiSoir() {
        return (Boolean)readProperty("jeudiSoir");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }
    
    
    public void setLundiAM(Boolean lundiAM) {
        writeProperty("lundiAM", lundiAM);
    }
    public Boolean getLundiAM() {
        return (Boolean)readProperty("lundiAM");
    }
    
    
    public void setLundiMatin(Boolean lundiMatin) {
        writeProperty("lundiMatin", lundiMatin);
    }
    public Boolean getLundiMatin() {
        return (Boolean)readProperty("lundiMatin");
    }
    
    
    public void setLundiMidi(Boolean lundiMidi) {
        writeProperty("lundiMidi", lundiMidi);
    }
    public Boolean getLundiMidi() {
        return (Boolean)readProperty("lundiMidi");
    }
    
    
    public void setLundiSoir(Boolean lundiSoir) {
        writeProperty("lundiSoir", lundiSoir);
    }
    public Boolean getLundiSoir() {
        return (Boolean)readProperty("lundiSoir");
    }
    
    
    public void setMardiAM(Boolean mardiAM) {
        writeProperty("mardiAM", mardiAM);
    }
    public Boolean getMardiAM() {
        return (Boolean)readProperty("mardiAM");
    }
    
    
    public void setMardiMatin(Boolean mardiMatin) {
        writeProperty("mardiMatin", mardiMatin);
    }
    public Boolean getMardiMatin() {
        return (Boolean)readProperty("mardiMatin");
    }
    
    
    public void setMardiMidi(Boolean mardiMidi) {
        writeProperty("mardiMidi", mardiMidi);
    }
    public Boolean getMardiMidi() {
        return (Boolean)readProperty("mardiMidi");
    }
    
    
    public void setMardiSoir(Boolean mardiSoir) {
        writeProperty("mardiSoir", mardiSoir);
    }
    public Boolean getMardiSoir() {
        return (Boolean)readProperty("mardiSoir");
    }
    
    
    public void setMercrediAM(Boolean mercrediAM) {
        writeProperty("mercrediAM", mercrediAM);
    }
    public Boolean getMercrediAM() {
        return (Boolean)readProperty("mercrediAM");
    }
    
    
    public void setMercrediMatin(Boolean mercrediMatin) {
        writeProperty("mercrediMatin", mercrediMatin);
    }
    public Boolean getMercrediMatin() {
        return (Boolean)readProperty("mercrediMatin");
    }
    
    
    public void setMercrediMidi(Boolean mercrediMidi) {
        writeProperty("mercrediMidi", mercrediMidi);
    }
    public Boolean getMercrediMidi() {
        return (Boolean)readProperty("mercrediMidi");
    }
    
    
    public void setMercrediSoir(Boolean mercrediSoir) {
        writeProperty("mercrediSoir", mercrediSoir);
    }
    public Boolean getMercrediSoir() {
        return (Boolean)readProperty("mercrediSoir");
    }
    
    
    public void setSamediAM(Boolean samediAM) {
        writeProperty("samediAM", samediAM);
    }
    public Boolean getSamediAM() {
        return (Boolean)readProperty("samediAM");
    }
    
    
    public void setSamediMatin(Boolean samediMatin) {
        writeProperty("samediMatin", samediMatin);
    }
    public Boolean getSamediMatin() {
        return (Boolean)readProperty("samediMatin");
    }
    
    
    public void setSamediMidi(Boolean samediMidi) {
        writeProperty("samediMidi", samediMidi);
    }
    public Boolean getSamediMidi() {
        return (Boolean)readProperty("samediMidi");
    }
    
    
    public void setSamediSoir(Boolean samediSoir) {
        writeProperty("samediSoir", samediSoir);
    }
    public Boolean getSamediSoir() {
        return (Boolean)readProperty("samediSoir");
    }
    
    
    public void setVendrediAM(Boolean vendrediAM) {
        writeProperty("vendrediAM", vendrediAM);
    }
    public Boolean getVendrediAM() {
        return (Boolean)readProperty("vendrediAM");
    }
    
    
    public void setVendrediMatin(Boolean vendrediMatin) {
        writeProperty("vendrediMatin", vendrediMatin);
    }
    public Boolean getVendrediMatin() {
        return (Boolean)readProperty("vendrediMatin");
    }
    
    
    public void setVendrediMidi(Boolean vendrediMidi) {
        writeProperty("vendrediMidi", vendrediMidi);
    }
    public Boolean getVendrediMidi() {
        return (Boolean)readProperty("vendrediMidi");
    }
    
    
    public void setVendrediSoir(Boolean vendrediSoir) {
        writeProperty("vendrediSoir", vendrediSoir);
    }
    public Boolean getVendrediSoir() {
        return (Boolean)readProperty("vendrediSoir");
    }
    
    
}
