package nc.ccas.gasel.model.import_v1.auto;

/** Class _ImportV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ImportV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3241713236121507524L;
	public static final String DST_ENTITY_PROPERTY = "dstEntity";
    public static final String DST_ID_PROPERTY = "dstId";
    public static final String SRC_ENTITY_PROPERTY = "srcEntity";
    public static final String SRC_ID_PROPERTY = "srcId";

    public static final String ID_PK_COLUMN = "id";

    public void setDstEntity(String dstEntity) {
        writeProperty("dstEntity", dstEntity);
    }
    public String getDstEntity() {
        return (String)readProperty("dstEntity");
    }
    
    
    public void setDstId(String dstId) {
        writeProperty("dstId", dstId);
    }
    public String getDstId() {
        return (String)readProperty("dstId");
    }
    
    
    public void setSrcEntity(String srcEntity) {
        writeProperty("srcEntity", srcEntity);
    }
    public String getSrcEntity() {
        return (String)readProperty("srcEntity");
    }
    
    
    public void setSrcId(String srcId) {
        writeProperty("srcId", srcId);
    }
    public String getSrcId() {
        return (String)readProperty("srcId");
    }
    
    
}
