package nc.ccas.gasel.model.habitat.auto;

import java.util.List;

import nc.ccas.gasel.model.habitat.ObjectifHabitat;

/** Class _ActionSociale was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ActionSociale extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -5500752768080758370L;
	public static final String CONTRAT_OBJECTIFS_PROPERTY = "contratObjectifs";
    public static final String DATE_PROPERTY = "date";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String EN_COURS_PROPERTY = "enCours";
    public static final String PAR_FAMILLE_PROPERTY = "parFamille";
    public static final String PAR_REFERENT_SOCIAL_PROPERTY = "parReferentSocial";
    public static final String PROJET_PROPERTY = "projet";
    public static final String PROJET_INSERTION_PROPERTY = "projetInsertion";
    public static final String DETAILS_PRIVES_PROPERTY = "detailsPrives";
    public static final String DOSSIER_PROPERTY = "dossier";

    public static final String ID_PK_COLUMN = "id";

    public void setContratObjectifs(Boolean contratObjectifs) {
        writeProperty("contratObjectifs", contratObjectifs);
    }
    public Boolean getContratObjectifs() {
        return (Boolean)readProperty("contratObjectifs");
    }
    
    
    public void setDate(java.util.Date date) {
        writeProperty("date", date);
    }
    public java.util.Date getDate() {
        return (java.util.Date)readProperty("date");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setEnCours(Boolean enCours) {
        writeProperty("enCours", enCours);
    }
    public Boolean getEnCours() {
        return (Boolean)readProperty("enCours");
    }
    
    
    public void setParFamille(Boolean parFamille) {
        writeProperty("parFamille", parFamille);
    }
    public Boolean getParFamille() {
        return (Boolean)readProperty("parFamille");
    }
    
    
    public void setParReferentSocial(Boolean parReferentSocial) {
        writeProperty("parReferentSocial", parReferentSocial);
    }
    public Boolean getParReferentSocial() {
        return (Boolean)readProperty("parReferentSocial");
    }
    
    
    public void setProjet(String projet) {
        writeProperty("projet", projet);
    }
    public String getProjet() {
        return (String)readProperty("projet");
    }
    
    
    public void setProjetInsertion(Boolean projetInsertion) {
        writeProperty("projetInsertion", projetInsertion);
    }
    public Boolean getProjetInsertion() {
        return (Boolean)readProperty("projetInsertion");
    }
    
    
    public void addToDetailsPrives(nc.ccas.gasel.model.habitat.ObjectifHabitat obj) {
        addToManyTarget("detailsPrives", obj, true);
    }
    public void removeFromDetailsPrives(nc.ccas.gasel.model.habitat.ObjectifHabitat obj) {
        removeToManyTarget("detailsPrives", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.ObjectifHabitat> getDetailsPrives() {
        return (List<ObjectifHabitat>)readProperty("detailsPrives");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.habitat.AspectDossierHabitat dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.habitat.AspectDossierHabitat getDossier() {
        return (nc.ccas.gasel.model.habitat.AspectDossierHabitat)readProperty("dossier");
    } 
    
    
}
