package nc.ccas.gasel.model.habitat.auto;

import java.util.List;

import nc.ccas.gasel.model.core.enums.Problematique;
import nc.ccas.gasel.model.habitat.AspectDossierHabitat;

/** Class _ActionCollective was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ActionCollective extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 4337502102589237396L;
	public static final String DESCRIPTION_PROPERTY = "description";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String DOSSIERS_PROPERTY = "dossiers";
    public static final String PROBLEMATIQUES_PROPERTY = "problematiques";
    public static final String REFERENT_FAMILIAL_PROPERTY = "referentFamilial";
    public static final String REFERENT_SOCIAL_PROPERTY = "referentSocial";

    public static final String ID_PK_COLUMN = "id";

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void addToDossiers(nc.ccas.gasel.model.habitat.AspectDossierHabitat obj) {
        addToManyTarget("dossiers", obj, true);
    }
    public void removeFromDossiers(nc.ccas.gasel.model.habitat.AspectDossierHabitat obj) {
        removeToManyTarget("dossiers", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.AspectDossierHabitat> getDossiers() {
        return (List<AspectDossierHabitat>)readProperty("dossiers");
    }
    
    
    public void addToProblematiques(nc.ccas.gasel.model.core.enums.Problematique obj) {
        addToManyTarget("problematiques", obj, true);
    }
    public void removeFromProblematiques(nc.ccas.gasel.model.core.enums.Problematique obj) {
        removeToManyTarget("problematiques", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.core.enums.Problematique> getProblematiques() {
        return (List<Problematique>)readProperty("problematiques");
    }
    
    
    public void setReferentFamilial(nc.ccas.gasel.model.core.Utilisateur referentFamilial) {
        setToOneTarget("referentFamilial", referentFamilial, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getReferentFamilial() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("referentFamilial");
    } 
    
    
    public void setReferentSocial(nc.ccas.gasel.model.core.Utilisateur referentSocial) {
        setToOneTarget("referentSocial", referentSocial, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getReferentSocial() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("referentSocial");
    } 
    
    
}
