package nc.ccas.gasel.model.habitat.auto;

import java.util.List;

import nc.ccas.gasel.model.habitat.ActionSociale;
import nc.ccas.gasel.model.habitat.AideLogement;
import nc.ccas.gasel.model.habitat.AideSociale;
import nc.ccas.gasel.model.habitat.DemandeAffectation;
import nc.ccas.gasel.model.habitat.DemandeAideLogement;
import nc.ccas.gasel.model.habitat.PrevisionnelHabitat;

/** Class _AspectDossierHabitat was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AspectDossierHabitat extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3782854375033776642L;
	public static final String DATE_RELOGEMENT_PROPERTY = "dateRelogement";
    public static final String DEBUT_ASL_PROPERTY = "debutASL";
    public static final String DEMANDE_INTERVENTION_PROPERTY = "demandeIntervention";
    public static final String ECHEANCE_SORTIE_PROPERTY = "echeanceSortie";
    public static final String NUMERO_MH_PROPERTY = "numeroMH";
    public static final String AIDES_PROPERTY = "aides";
    public static final String AIDES_COMPLEMENTAIRES_PROPERTY = "aidesComplementaires";
    public static final String AUTRES_PROBLEMES_PROPERTY = "autresProblemes";
    public static final String DEMANDES_AFFECTATION_PROPERTY = "demandesAffectation";
    public static final String DEMANDES_AIDE_LOGEMENT_PROPERTY = "demandesAideLogement";
    public static final String DOSSIER_PROPERTY = "dossier";
    public static final String ORIGINE_PROPERTY = "origine";
    public static final String ORIGINE_SIGNALEMENT_PROPERTY = "origineSignalement";
    public static final String PHASE_PROPERTY = "phase";
    public static final String PLANNING_PROPERTY = "planning";
    public static final String QUARTIER_RELOGEMENT_PROPERTY = "quartierRelogement";
    public static final String REFERENT_FAMILIAL_PROPERTY = "referentFamilial";
    public static final String REFERENT_SOCIAL_PROPERTY = "referentSocial";
    public static final String TYPE_LOGEMENT_ORIGINE_PROPERTY = "typeLogementOrigine";

    public static final String DOSSIER_ID_PK_COLUMN = "dossier_id";

    public void setDateRelogement(java.util.Date dateRelogement) {
        writeProperty("dateRelogement", dateRelogement);
    }
    public java.util.Date getDateRelogement() {
        return (java.util.Date)readProperty("dateRelogement");
    }
    
    
    public void setDebutASL(java.util.Date debutASL) {
        writeProperty("debutASL", debutASL);
    }
    public java.util.Date getDebutASL() {
        return (java.util.Date)readProperty("debutASL");
    }
    
    
    public void setDemandeIntervention(Boolean demandeIntervention) {
        writeProperty("demandeIntervention", demandeIntervention);
    }
    public Boolean getDemandeIntervention() {
        return (Boolean)readProperty("demandeIntervention");
    }
    
    
    public void setEcheanceSortie(java.util.Date echeanceSortie) {
        writeProperty("echeanceSortie", echeanceSortie);
    }
    public java.util.Date getEcheanceSortie() {
        return (java.util.Date)readProperty("echeanceSortie");
    }
    
    
    public void setNumeroMH(String numeroMH) {
        writeProperty("numeroMH", numeroMH);
    }
    public String getNumeroMH() {
        return (String)readProperty("numeroMH");
    }
    
    
    public void addToAides(nc.ccas.gasel.model.habitat.AideLogement obj) {
        addToManyTarget("aides", obj, true);
    }
    public void removeFromAides(nc.ccas.gasel.model.habitat.AideLogement obj) {
        removeToManyTarget("aides", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.AideLogement> getAides() {
        return (List<AideLogement>)readProperty("aides");
    }
    
    
    public void addToAidesComplementaires(nc.ccas.gasel.model.habitat.AideSociale obj) {
        addToManyTarget("aidesComplementaires", obj, true);
    }
    public void removeFromAidesComplementaires(nc.ccas.gasel.model.habitat.AideSociale obj) {
        removeToManyTarget("aidesComplementaires", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.AideSociale> getAidesComplementaires() {
        return (List<AideSociale>)readProperty("aidesComplementaires");
    }
    
    
    public void addToAutresProblemes(nc.ccas.gasel.model.habitat.ActionSociale obj) {
        addToManyTarget("autresProblemes", obj, true);
    }
    public void removeFromAutresProblemes(nc.ccas.gasel.model.habitat.ActionSociale obj) {
        removeToManyTarget("autresProblemes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.ActionSociale> getAutresProblemes() {
        return (List<ActionSociale>)readProperty("autresProblemes");
    }
    
    
    public void addToDemandesAffectation(nc.ccas.gasel.model.habitat.DemandeAffectation obj) {
        addToManyTarget("demandesAffectation", obj, true);
    }
    public void removeFromDemandesAffectation(nc.ccas.gasel.model.habitat.DemandeAffectation obj) {
        removeToManyTarget("demandesAffectation", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.DemandeAffectation> getDemandesAffectation() {
        return (List<DemandeAffectation>)readProperty("demandesAffectation");
    }
    
    
    public void addToDemandesAideLogement(nc.ccas.gasel.model.habitat.DemandeAideLogement obj) {
        addToManyTarget("demandesAideLogement", obj, true);
    }
    public void removeFromDemandesAideLogement(nc.ccas.gasel.model.habitat.DemandeAideLogement obj) {
        removeToManyTarget("demandesAideLogement", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.DemandeAideLogement> getDemandesAideLogement() {
        return (List<DemandeAideLogement>)readProperty("demandesAideLogement");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.core.Dossier dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.core.Dossier getDossier() {
        return (nc.ccas.gasel.model.core.Dossier)readProperty("dossier");
    } 
    
    
    public void setOrigine(nc.ccas.gasel.model.habitat.SiteRHI origine) {
        setToOneTarget("origine", origine, true);
    }

    public nc.ccas.gasel.model.habitat.SiteRHI getOrigine() {
        return (nc.ccas.gasel.model.habitat.SiteRHI)readProperty("origine");
    } 
    
    
    public void setOrigineSignalement(nc.ccas.gasel.model.habitat.enums.OrigineSignalementHb origineSignalement) {
        setToOneTarget("origineSignalement", origineSignalement, true);
    }

    public nc.ccas.gasel.model.habitat.enums.OrigineSignalementHb getOrigineSignalement() {
        return (nc.ccas.gasel.model.habitat.enums.OrigineSignalementHb)readProperty("origineSignalement");
    } 
    
    
    public void setPhase(nc.ccas.gasel.model.habitat.enums.PhaseRelogement phase) {
        setToOneTarget("phase", phase, true);
    }

    public nc.ccas.gasel.model.habitat.enums.PhaseRelogement getPhase() {
        return (nc.ccas.gasel.model.habitat.enums.PhaseRelogement)readProperty("phase");
    } 
    
    
    public void addToPlanning(nc.ccas.gasel.model.habitat.PrevisionnelHabitat obj) {
        addToManyTarget("planning", obj, true);
    }
    public void removeFromPlanning(nc.ccas.gasel.model.habitat.PrevisionnelHabitat obj) {
        removeToManyTarget("planning", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.PrevisionnelHabitat> getPlanning() {
        return (List<PrevisionnelHabitat>)readProperty("planning");
    }
    
    
    public void setQuartierRelogement(nc.ccas.gasel.model.mairie.Quartier quartierRelogement) {
        setToOneTarget("quartierRelogement", quartierRelogement, true);
    }

    public nc.ccas.gasel.model.mairie.Quartier getQuartierRelogement() {
        return (nc.ccas.gasel.model.mairie.Quartier)readProperty("quartierRelogement");
    } 
    
    
    public void setReferentFamilial(nc.ccas.gasel.model.core.Utilisateur referentFamilial) {
        setToOneTarget("referentFamilial", referentFamilial, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getReferentFamilial() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("referentFamilial");
    } 
    
    
    public void setReferentSocial(nc.ccas.gasel.model.core.Utilisateur referentSocial) {
        setToOneTarget("referentSocial", referentSocial, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getReferentSocial() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("referentSocial");
    } 
    
    
    public void setTypeLogementOrigine(nc.ccas.gasel.model.habitat.enums.TypeLogement typeLogementOrigine) {
        setToOneTarget("typeLogementOrigine", typeLogementOrigine, true);
    }

    public nc.ccas.gasel.model.habitat.enums.TypeLogement getTypeLogementOrigine() {
        return (nc.ccas.gasel.model.habitat.enums.TypeLogement)readProperty("typeLogementOrigine");
    } 
    
    
}
