package nc.ccas.gasel.model.habitat.auto;

import java.util.List;

import nc.ccas.gasel.model.habitat.SecoursImmediatExceptionnel;

/** Class _AspectSIE was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AspectSIE extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -8415171838901234037L;
	public static final String DOSSIER_PROPERTY = "dossier";
    public static final String SECOURS_PROPERTY = "secours";

    public static final String DOSSIER_ID_PK_COLUMN = "dossier_id";

    public void setDossier(nc.ccas.gasel.model.core.Dossier dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.core.Dossier getDossier() {
        return (nc.ccas.gasel.model.core.Dossier)readProperty("dossier");
    } 
    
    
    public void addToSecours(nc.ccas.gasel.model.habitat.SecoursImmediatExceptionnel obj) {
        addToManyTarget("secours", obj, true);
    }
    public void removeFromSecours(nc.ccas.gasel.model.habitat.SecoursImmediatExceptionnel obj) {
        removeToManyTarget("secours", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.SecoursImmediatExceptionnel> getSecours() {
        return (List<SecoursImmediatExceptionnel>)readProperty("secours");
    }
    
    
}
