package nc.ccas.gasel.model.habitat.auto;

/** Class _DemandeAffectation was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _DemandeAffectation extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6783149940439152109L;
	public static final String DATE_PROPERTY = "date";
    public static final String AFF_ACCESSION_PROPERTY = "affAccession";
    public static final String AFF_LOCATIF_PROPERTY = "affLocatif";
    public static final String AFF_REHABILITATION_PROPERTY = "affRehabilitation";
    public static final String DOSSIER_PROPERTY = "dossier";
    public static final String QUARTIER_PROPERTY = "quartier";
    public static final String TYPE_PROPERTY = "type";
    public static final String TYPE_DEMANDE_PROPERTY = "typeDemande";

    public static final String ID_PK_COLUMN = "id";

    public void setDate(java.util.Date date) {
        writeProperty("date", date);
    }
    public java.util.Date getDate() {
        return (java.util.Date)readProperty("date");
    }
    
    
    public void setAffAccession(nc.ccas.gasel.model.habitat.AffectationAccession affAccession) {
        setToOneTarget("affAccession", affAccession, true);
    }

    public nc.ccas.gasel.model.habitat.AffectationAccession getAffAccession() {
        return (nc.ccas.gasel.model.habitat.AffectationAccession)readProperty("affAccession");
    } 
    
    
    public void setAffLocatif(nc.ccas.gasel.model.habitat.AffectationLocatif affLocatif) {
        setToOneTarget("affLocatif", affLocatif, true);
    }

    public nc.ccas.gasel.model.habitat.AffectationLocatif getAffLocatif() {
        return (nc.ccas.gasel.model.habitat.AffectationLocatif)readProperty("affLocatif");
    } 
    
    
    public void setAffRehabilitation(nc.ccas.gasel.model.habitat.AffectationRehabilitation affRehabilitation) {
        setToOneTarget("affRehabilitation", affRehabilitation, true);
    }

    public nc.ccas.gasel.model.habitat.AffectationRehabilitation getAffRehabilitation() {
        return (nc.ccas.gasel.model.habitat.AffectationRehabilitation)readProperty("affRehabilitation");
    } 
    
    
    public void setDossier(nc.ccas.gasel.model.habitat.AspectDossierHabitat dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.habitat.AspectDossierHabitat getDossier() {
        return (nc.ccas.gasel.model.habitat.AspectDossierHabitat)readProperty("dossier");
    } 
    
    
    public void setQuartier(nc.ccas.gasel.model.mairie.Quartier quartier) {
        setToOneTarget("quartier", quartier, true);
    }

    public nc.ccas.gasel.model.mairie.Quartier getQuartier() {
        return (nc.ccas.gasel.model.mairie.Quartier)readProperty("quartier");
    } 
    
    
    public void setType(nc.ccas.gasel.model.habitat.enums.TypeLogement type) {
        setToOneTarget("type", type, true);
    }

    public nc.ccas.gasel.model.habitat.enums.TypeLogement getType() {
        return (nc.ccas.gasel.model.habitat.enums.TypeLogement)readProperty("type");
    } 
    
    
    public void setTypeDemande(nc.ccas.gasel.model.habitat.enums.TypeAffDemandeHabitat typeDemande) {
        setToOneTarget("typeDemande", typeDemande, true);
    }

    public nc.ccas.gasel.model.habitat.enums.TypeAffDemandeHabitat getTypeDemande() {
        return (nc.ccas.gasel.model.habitat.enums.TypeAffDemandeHabitat)readProperty("typeDemande");
    } 
    
    
}
