package nc.ccas.gasel.model.habitat.auto;

import java.util.List;

import nc.ccas.gasel.model.habitat.AideLogement;

/** Class _DemandeAideLogement was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _DemandeAideLogement extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -7085544309405547049L;
	public static final String DATE_CC_PROPERTY = "dateCC";
    public static final String DATE_CT_PROPERTY = "dateCT";
    public static final String EVALUATION_SOCIALE_PROPERTY = "evaluationSociale";
    public static final String RESUME_CC_PROPERTY = "resumeCC";
    public static final String AIDES_PROPERTY = "aides";
    public static final String ATTRIBUTION_PROPERTY = "attribution";
    public static final String DOSSIER_HABITAT_PROPERTY = "dossierHabitat";
    public static final String MOTIF_CT_PROPERTY = "motifCT";

    public static final String ID_PK_COLUMN = "id";

    public void setDateCC(java.util.Date dateCC) {
        writeProperty("dateCC", dateCC);
    }
    public java.util.Date getDateCC() {
        return (java.util.Date)readProperty("dateCC");
    }
    
    
    public void setDateCT(java.util.Date dateCT) {
        writeProperty("dateCT", dateCT);
    }
    public java.util.Date getDateCT() {
        return (java.util.Date)readProperty("dateCT");
    }
    
    
    public void setEvaluationSociale(String evaluationSociale) {
        writeProperty("evaluationSociale", evaluationSociale);
    }
    public String getEvaluationSociale() {
        return (String)readProperty("evaluationSociale");
    }
    
    
    public void setResumeCC(String resumeCC) {
        writeProperty("resumeCC", resumeCC);
    }
    public String getResumeCC() {
        return (String)readProperty("resumeCC");
    }
    
    
    public void addToAides(nc.ccas.gasel.model.habitat.AideLogement obj) {
        addToManyTarget("aides", obj, true);
    }
    public void removeFromAides(nc.ccas.gasel.model.habitat.AideLogement obj) {
        removeToManyTarget("aides", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.AideLogement> getAides() {
        return (List<AideLogement>)readProperty("aides");
    }
    
    
    public void setAttribution(nc.ccas.gasel.model.habitat.Attribution attribution) {
        setToOneTarget("attribution", attribution, true);
    }

    public nc.ccas.gasel.model.habitat.Attribution getAttribution() {
        return (nc.ccas.gasel.model.habitat.Attribution)readProperty("attribution");
    } 
    
    
    public void setDossierHabitat(nc.ccas.gasel.model.habitat.AspectDossierHabitat dossierHabitat) {
        setToOneTarget("dossierHabitat", dossierHabitat, true);
    }

    public nc.ccas.gasel.model.habitat.AspectDossierHabitat getDossierHabitat() {
        return (nc.ccas.gasel.model.habitat.AspectDossierHabitat)readProperty("dossierHabitat");
    } 
    
    
    public void setMotifCT(nc.ccas.gasel.model.habitat.enums.MotifCT motifCT) {
        setToOneTarget("motifCT", motifCT, true);
    }

    public nc.ccas.gasel.model.habitat.enums.MotifCT getMotifCT() {
        return (nc.ccas.gasel.model.habitat.enums.MotifCT)readProperty("motifCT");
    } 
    
    
}
