package nc.ccas.gasel.model.habitat.auto;

/** Class _Intervention was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Intervention extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6644380987385443145L;
	public static final String PAR_TS_PROPERTY = "parTS";
    public static final String MOTIF_PROPERTY = "motif";
    public static final String OBJECTIF_PROPERTY = "objectif";

    public static final String ID_PK_COLUMN = "id";

    public void setParTS(Boolean parTS) {
        writeProperty("parTS", parTS);
    }
    public Boolean getParTS() {
        return (Boolean)readProperty("parTS");
    }
    
    
    public void setMotif(nc.ccas.gasel.model.habitat.enums.MotifIntervention motif) {
        setToOneTarget("motif", motif, true);
    }

    public nc.ccas.gasel.model.habitat.enums.MotifIntervention getMotif() {
        return (nc.ccas.gasel.model.habitat.enums.MotifIntervention)readProperty("motif");
    } 
    
    
    public void setObjectif(nc.ccas.gasel.model.habitat.ObjectifHabitat objectif) {
        setToOneTarget("objectif", objectif, true);
    }

    public nc.ccas.gasel.model.habitat.ObjectifHabitat getObjectif() {
        return (nc.ccas.gasel.model.habitat.ObjectifHabitat)readProperty("objectif");
    } 
    
    
}
