package nc.ccas.gasel.model.habitat.auto;

import java.util.List;

import nc.ccas.gasel.model.habitat.Intervention;
import nc.ccas.gasel.model.habitat.ObjectifProbHabitat;

/** Class _ObjectifHabitat was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ObjectifHabitat extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3727313190779176414L;
	public static final String ECHEANCE_PROPERTY = "echeance";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String ACTION_SOCIALE_PROPERTY = "actionSociale";
    public static final String INTERVENTIONS_PROPERTY = "interventions";
    public static final String PROBLEMATIQUES_PROPERTY = "problematiques";

    public static final String ID_PK_COLUMN = "id";

    public void setEcheance(java.util.Date echeance) {
        writeProperty("echeance", echeance);
    }
    public java.util.Date getEcheance() {
        return (java.util.Date)readProperty("echeance");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setActionSociale(nc.ccas.gasel.model.habitat.ActionSociale actionSociale) {
        setToOneTarget("actionSociale", actionSociale, true);
    }

    public nc.ccas.gasel.model.habitat.ActionSociale getActionSociale() {
        return (nc.ccas.gasel.model.habitat.ActionSociale)readProperty("actionSociale");
    } 
    
    
    public void addToInterventions(nc.ccas.gasel.model.habitat.Intervention obj) {
        addToManyTarget("interventions", obj, true);
    }
    public void removeFromInterventions(nc.ccas.gasel.model.habitat.Intervention obj) {
        removeToManyTarget("interventions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.Intervention> getInterventions() {
        return (List<Intervention>)readProperty("interventions");
    }
    
    
    public void addToProblematiques(nc.ccas.gasel.model.habitat.ObjectifProbHabitat obj) {
        addToManyTarget("problematiques", obj, true);
    }
    public void removeFromProblematiques(nc.ccas.gasel.model.habitat.ObjectifProbHabitat obj) {
        removeToManyTarget("problematiques", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.habitat.ObjectifProbHabitat> getProblematiques() {
        return (List<ObjectifProbHabitat>)readProperty("problematiques");
    }
    
    
}
