package nc.ccas.gasel.model.habitat.auto;

/** Class _ObservationSiteRHI was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ObservationSiteRHI extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 2962196031297735406L;
	public static final String OBSERVATION_PROPERTY = "observation";
    public static final String SITE_PROPERTY = "site";

    public static final String ID_PK_COLUMN = "id";

    public void setObservation(String observation) {
        writeProperty("observation", observation);
    }
    public String getObservation() {
        return (String)readProperty("observation");
    }
    
    
    public void setSite(nc.ccas.gasel.model.habitat.SiteRHI site) {
        setToOneTarget("site", site, true);
    }

    public nc.ccas.gasel.model.habitat.SiteRHI getSite() {
        return (nc.ccas.gasel.model.habitat.SiteRHI)readProperty("site");
    } 
    
    
}
