package nc.ccas.gasel.model.core.auto;

/** Class _ActivitePersonne was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ActivitePersonne extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -1676183264830615884L;
	public static final String DEBUT_PROPERTY = "debut";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String FIN_PROPERTY = "fin";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String CONTRAT_PROPERTY = "contrat";
    public static final String PERSONNE_PROPERTY = "personne";
    public static final String TYPE_PROPERTY = "type";

    public static final String ID_PK_COLUMN = "id";

    public void setDebut(java.util.Date debut) {
        writeProperty("debut", debut);
    }
    public java.util.Date getDebut() {
        return (java.util.Date)readProperty("debut");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setFin(java.util.Date fin) {
        writeProperty("fin", fin);
    }
    public java.util.Date getFin() {
        return (java.util.Date)readProperty("fin");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setContrat(nc.ccas.gasel.model.core.enums.TypeContrat contrat) {
        setToOneTarget("contrat", contrat, true);
    }

    public nc.ccas.gasel.model.core.enums.TypeContrat getContrat() {
        return (nc.ccas.gasel.model.core.enums.TypeContrat)readProperty("contrat");
    } 
    
    
    public void setPersonne(nc.ccas.gasel.model.core.Personne personne) {
        setToOneTarget("personne", personne, true);
    }

    public nc.ccas.gasel.model.core.Personne getPersonne() {
        return (nc.ccas.gasel.model.core.Personne)readProperty("personne");
    } 
    
    
    public void setType(nc.ccas.gasel.model.core.enums.TypeActivite type) {
        setToOneTarget("type", type, true);
    }

    public nc.ccas.gasel.model.core.enums.TypeActivite getType() {
        return (nc.ccas.gasel.model.core.enums.TypeActivite)readProperty("type");
    } 
    
    
}
