package nc.ccas.gasel.model.core.auto;

import java.util.List;

import nc.ccas.gasel.model.core.Personne;
import nc.ccas.gasel.model.core.enums.Problematique;
import nc.ccas.gasel.model.core.enums.TypePublic;

/** Class _Dossier was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Dossier extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2100237824310118736L;
	public static final String DATE_ARRIVEE_COMMUNE_PROPERTY = "dateArriveeCommune";
    public static final String DATE_OUVERTURE_PROPERTY = "dateOuverture";
    public static final String MODIF_DATE_PROPERTY = "modifDate";
    public static final String ADRESSE_HABITATION_PROPERTY = "adresseHabitation";
    public static final String ADRESSE_POSTALE_PROPERTY = "adressePostale";
    public static final String CHEF_FAMILLE_PROPERTY = "chefFamille";
    public static final String CONJOINT_PROPERTY = "conjoint";
    public static final String MODIF_UTILISATEUR_PROPERTY = "modifUtilisateur";
    public static final String PERSONNES_ACHARGE_PROPERTY = "personnesACharge";
    public static final String PERSONNES_NON_ACHARGE_PROPERTY = "personnesNonACharge";
    public static final String PROBLEMATIQUES_PROPERTY = "problematiques";
    public static final String REFERENT_PROPERTY = "referent";
    public static final String SIGNALEMENT_PROPERTY = "signalement";
    public static final String TYPE_HABITAT_PROPERTY = "typeHabitat";
    public static final String TYPES_PUBLIC_PROPERTY = "typesPublic";

    public static final String ID_PK_COLUMN = "id";

    public void setDateArriveeCommune(java.util.Date dateArriveeCommune) {
        writeProperty("dateArriveeCommune", dateArriveeCommune);
    }
    public java.util.Date getDateArriveeCommune() {
        return (java.util.Date)readProperty("dateArriveeCommune");
    }
    
    
    public void setDateOuverture(java.util.Date dateOuverture) {
        writeProperty("dateOuverture", dateOuverture);
    }
    public java.util.Date getDateOuverture() {
        return (java.util.Date)readProperty("dateOuverture");
    }
    
    
    public void setModifDate(java.util.Date modifDate) {
        writeProperty("modifDate", modifDate);
    }
    public java.util.Date getModifDate() {
        return (java.util.Date)readProperty("modifDate");
    }
    
    
    public void setAdresseHabitation(nc.ccas.gasel.model.core.Adresse adresseHabitation) {
        setToOneTarget("adresseHabitation", adresseHabitation, true);
    }

    public nc.ccas.gasel.model.core.Adresse getAdresseHabitation() {
        return (nc.ccas.gasel.model.core.Adresse)readProperty("adresseHabitation");
    } 
    
    
    public void setAdressePostale(nc.ccas.gasel.model.core.Adresse adressePostale) {
        setToOneTarget("adressePostale", adressePostale, true);
    }

    public nc.ccas.gasel.model.core.Adresse getAdressePostale() {
        return (nc.ccas.gasel.model.core.Adresse)readProperty("adressePostale");
    } 
    
    
    public void setChefFamille(nc.ccas.gasel.model.core.Personne chefFamille) {
        setToOneTarget("chefFamille", chefFamille, true);
    }

    public nc.ccas.gasel.model.core.Personne getChefFamille() {
        return (nc.ccas.gasel.model.core.Personne)readProperty("chefFamille");
    } 
    
    
    public void setConjoint(nc.ccas.gasel.model.core.Personne conjoint) {
        setToOneTarget("conjoint", conjoint, true);
    }

    public nc.ccas.gasel.model.core.Personne getConjoint() {
        return (nc.ccas.gasel.model.core.Personne)readProperty("conjoint");
    } 
    
    
    public void setModifUtilisateur(nc.ccas.gasel.model.core.Utilisateur modifUtilisateur) {
        setToOneTarget("modifUtilisateur", modifUtilisateur, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getModifUtilisateur() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("modifUtilisateur");
    } 
    
    
    public void addToPersonnesACharge(nc.ccas.gasel.model.core.Personne obj) {
        addToManyTarget("personnesACharge", obj, true);
    }
    public void removeFromPersonnesACharge(nc.ccas.gasel.model.core.Personne obj) {
        removeToManyTarget("personnesACharge", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.core.Personne> getPersonnesACharge() {
        return (List<Personne>)readProperty("personnesACharge");
    }
    
    
    public void addToPersonnesNonACharge(nc.ccas.gasel.model.core.Personne obj) {
        addToManyTarget("personnesNonACharge", obj, true);
    }
    public void removeFromPersonnesNonACharge(nc.ccas.gasel.model.core.Personne obj) {
        removeToManyTarget("personnesNonACharge", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.core.Personne> getPersonnesNonACharge() {
        return (List<Personne>)readProperty("personnesNonACharge");
    }
    
    
    public void addToProblematiques(nc.ccas.gasel.model.core.enums.Problematique obj) {
        addToManyTarget("problematiques", obj, true);
    }
    public void removeFromProblematiques(nc.ccas.gasel.model.core.enums.Problematique obj) {
        removeToManyTarget("problematiques", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.core.enums.Problematique> getProblematiques() {
        return (List<Problematique>)readProperty("problematiques");
    }
    
    
    public void setReferent(nc.ccas.gasel.model.core.Utilisateur referent) {
        setToOneTarget("referent", referent, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getReferent() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("referent");
    } 
    
    
    public void setSignalement(nc.ccas.gasel.model.core.enums.OrigineSignalement signalement) {
        setToOneTarget("signalement", signalement, true);
    }

    public nc.ccas.gasel.model.core.enums.OrigineSignalement getSignalement() {
        return (nc.ccas.gasel.model.core.enums.OrigineSignalement)readProperty("signalement");
    } 
    
    
    public void setTypeHabitat(nc.ccas.gasel.model.core.enums.TypeHabitat typeHabitat) {
        setToOneTarget("typeHabitat", typeHabitat, true);
    }

    public nc.ccas.gasel.model.core.enums.TypeHabitat getTypeHabitat() {
        return (nc.ccas.gasel.model.core.enums.TypeHabitat)readProperty("typeHabitat");
    } 
    
    
    public void addToTypesPublic(nc.ccas.gasel.model.core.enums.TypePublic obj) {
        addToManyTarget("typesPublic", obj, true);
    }
    public void removeFromTypesPublic(nc.ccas.gasel.model.core.enums.TypePublic obj) {
        removeToManyTarget("typesPublic", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.core.enums.TypePublic> getTypesPublic() {
        return (List<TypePublic>)readProperty("typesPublic");
    }
    
    
}
