package nc.ccas.gasel.model.core.auto;

import java.util.List;

import nc.ccas.gasel.model.core.AccesPage;
import nc.ccas.gasel.model.core.Utilisateur;

/** Class _Groupe was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Groupe extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5684290284903460058L;
	public static final String LIBELLE_PROPERTY = "libelle";
    public static final String ACCES_PAGE_PROPERTY = "accesPage";
    public static final String UTILISATEURS_PROPERTY = "utilisateurs";

    public static final String ID_PK_COLUMN = "id";

    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void addToAccesPage(nc.ccas.gasel.model.core.AccesPage obj) {
        addToManyTarget("accesPage", obj, true);
    }
    public void removeFromAccesPage(nc.ccas.gasel.model.core.AccesPage obj) {
        removeToManyTarget("accesPage", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.core.AccesPage> getAccesPage() {
        return (List<AccesPage>)readProperty("accesPage");
    }
    
    
    public void addToUtilisateurs(nc.ccas.gasel.model.core.Utilisateur obj) {
        addToManyTarget("utilisateurs", obj, true);
    }
    public void removeFromUtilisateurs(nc.ccas.gasel.model.core.Utilisateur obj) {
        removeToManyTarget("utilisateurs", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.core.Utilisateur> getUtilisateurs() {
        return (List<Utilisateur>)readProperty("utilisateurs");
    }
    
    
}
