package nc.ccas.gasel.model.core.auto;

import java.util.List;

/** Class _Utilisateur was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Utilisateur extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -8543307491861444874L;
	public static final String ACTIF_PROPERTY = "actif";
    public static final String INITIALES_PROPERTY = "initiales";
    public static final String LOGIN_PROPERTY = "login";
    public static final String NOM_PROPERTY = "nom";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String PRENOM_PROPERTY = "prenom";
    public static final String GROUPES_PROPERTY = "groupes";

    public static final String ID_PK_COLUMN = "id";

    public void setActif(Boolean actif) {
        writeProperty("actif", actif);
    }
    public Boolean getActif() {
        return (Boolean)readProperty("actif");
    }
    
    
    public void setInitiales(String initiales) {
        writeProperty("initiales", initiales);
    }
    public String getInitiales() {
        return (String)readProperty("initiales");
    }
    
    
    public void setLogin(String login) {
        writeProperty("login", login);
    }
    public String getLogin() {
        return (String)readProperty("login");
    }
    
    
    public void setNom(String nom) {
        writeProperty("nom", nom);
    }
    public String getNom() {
        return (String)readProperty("nom");
    }
    
    
    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }
    
    
    public void setPrenom(String prenom) {
        writeProperty("prenom", prenom);
    }
    public String getPrenom() {
        return (String)readProperty("prenom");
    }
    
    
    public void addToGroupes(nc.ccas.gasel.model.core.Groupe obj) {
        addToManyTarget("groupes", obj, true);
    }
    public void removeFromGroupes(nc.ccas.gasel.model.core.Groupe obj) {
        removeToManyTarget("groupes", obj, true);
    }
    public List<?> getGroupes() {
        return (List<?>)readProperty("groupes");
    }
    
    
}
