package nc.ccas.gasel.model.vues.auto;

/** Class _AideResumeMontants was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AideResumeMontants extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3085017362261888639L;
	public static final String ANNEE_PROPERTY = "annee";
    public static final String MOIS_PROPERTY = "mois";
    public static final String MONTANT_AIDE_PROPERTY = "montantAide";
    public static final String MONTANT_BONS_PROPERTY = "montantBons";
    public static final String MONTANT_BONS_ANNULE_PROPERTY = "montantBonsAnnule";
    public static final String MONTANT_BONS_EDITE_PROPERTY = "montantBonsEdite";
    public static final String MONTANT_BONS_INUTILISE_PROPERTY = "montantBonsInutilise";
    public static final String MONTANT_BONS_INUTILISE_BRUT_PROPERTY = "montantBonsInutiliseBrut";
    public static final String MONTANT_BONS_UTILISE_PROPERTY = "montantBonsUtilise";
    public static final String AIDE_PROPERTY = "aide";
    public static final String BIM_PROPERTY = "bim";
    public static final String PUBLIC_PROPERTY = "public";
    public static final String SECTEUR_PROPERTY = "secteur";

    public static final String ANNEE_MOIS_PK_COLUMN = "annee_mois";
    public static final String ID_PK_COLUMN = "id";

    public void setAnnee(Integer annee) {
        writeProperty("annee", annee);
    }
    public Integer getAnnee() {
        return (Integer)readProperty("annee");
    }
    
    
    public void setMois(Integer mois) {
        writeProperty("mois", mois);
    }
    public Integer getMois() {
        return (Integer)readProperty("mois");
    }
    
    
    public void setMontantAide(Integer montantAide) {
        writeProperty("montantAide", montantAide);
    }
    public Integer getMontantAide() {
        return (Integer)readProperty("montantAide");
    }
    
    
    public void setMontantBons(Integer montantBons) {
        writeProperty("montantBons", montantBons);
    }
    public Integer getMontantBons() {
        return (Integer)readProperty("montantBons");
    }
    
    
    public void setMontantBonsAnnule(Integer montantBonsAnnule) {
        writeProperty("montantBonsAnnule", montantBonsAnnule);
    }
    public Integer getMontantBonsAnnule() {
        return (Integer)readProperty("montantBonsAnnule");
    }
    
    
    public void setMontantBonsEdite(Integer montantBonsEdite) {
        writeProperty("montantBonsEdite", montantBonsEdite);
    }
    public Integer getMontantBonsEdite() {
        return (Integer)readProperty("montantBonsEdite");
    }
    
    
    public void setMontantBonsInutilise(Integer montantBonsInutilise) {
        writeProperty("montantBonsInutilise", montantBonsInutilise);
    }
    public Integer getMontantBonsInutilise() {
        return (Integer)readProperty("montantBonsInutilise");
    }
    
    
    public void setMontantBonsInutiliseBrut(Integer montantBonsInutiliseBrut) {
        writeProperty("montantBonsInutiliseBrut", montantBonsInutiliseBrut);
    }
    public Integer getMontantBonsInutiliseBrut() {
        return (Integer)readProperty("montantBonsInutiliseBrut");
    }
    
    
    public void setMontantBonsUtilise(Integer montantBonsUtilise) {
        writeProperty("montantBonsUtilise", montantBonsUtilise);
    }
    public Integer getMontantBonsUtilise() {
        return (Integer)readProperty("montantBonsUtilise");
    }
    
    
    public void setAide(nc.ccas.gasel.model.aides.Aide aide) {
        setToOneTarget("aide", aide, true);
    }

    public nc.ccas.gasel.model.aides.Aide getAide() {
        return (nc.ccas.gasel.model.aides.Aide)readProperty("aide");
    } 
    
    
    public void setBim(nc.ccas.gasel.model.budget.BudgetImpMensuel bim) {
        setToOneTarget("bim", bim, true);
    }

    public nc.ccas.gasel.model.budget.BudgetImpMensuel getBim() {
        return (nc.ccas.gasel.model.budget.BudgetImpMensuel)readProperty("bim");
    } 
    
    
    public void setPublic(nc.ccas.gasel.model.core.enums.TypePublic _public) {
        setToOneTarget("public", _public, true);
    }

    public nc.ccas.gasel.model.core.enums.TypePublic getPublic() {
        return (nc.ccas.gasel.model.core.enums.TypePublic)readProperty("public");
    } 
    
    
    public void setSecteur(nc.ccas.gasel.model.budget.SecteurAide secteur) {
        setToOneTarget("secteur", secteur, true);
    }

    public nc.ccas.gasel.model.budget.SecteurAide getSecteur() {
        return (nc.ccas.gasel.model.budget.SecteurAide)readProperty("secteur");
    } 
    
    
}
