package nc.ccas.gasel.model.v1.auto;

/** Class _ActiviteV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ActiviteV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -7178658266208120943L;
	public static final String DATE_DEBUT_PROPERTY = "dateDebut";
    public static final String DATE_FIN_PROPERTY = "dateFin";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String ADMINISTRE_PROPERTY = "administre";
    public static final String TYPE_PROPERTY = "type";
    public static final String TYPE_CONTRAT_PROPERTY = "typeContrat";

    public static final String T_ACTIVITE_ID_PK_COLUMN = "t_activite_id";

    public void setDateDebut(java.util.Date dateDebut) {
        writeProperty("dateDebut", dateDebut);
    }
    public java.util.Date getDateDebut() {
        return (java.util.Date)readProperty("dateDebut");
    }
    
    
    public void setDateFin(java.util.Date dateFin) {
        writeProperty("dateFin", dateFin);
    }
    public java.util.Date getDateFin() {
        return (java.util.Date)readProperty("dateFin");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setAdministre(nc.ccas.gasel.model.v1.AdministreV1 administre) {
        setToOneTarget("administre", administre, true);
    }

    public nc.ccas.gasel.model.v1.AdministreV1 getAdministre() {
        return (nc.ccas.gasel.model.v1.AdministreV1)readProperty("administre");
    } 
    
    
    public void setType(nc.ccas.gasel.model.mairie.TypeActiviteV1 type) {
        setToOneTarget("type", type, true);
    }

    public nc.ccas.gasel.model.mairie.TypeActiviteV1 getType() {
        return (nc.ccas.gasel.model.mairie.TypeActiviteV1)readProperty("type");
    } 
    
    
    public void setTypeContrat(nc.ccas.gasel.model.v1.TypeContratV1 typeContrat) {
        setToOneTarget("typeContrat", typeContrat, true);
    }

    public nc.ccas.gasel.model.v1.TypeContratV1 getTypeContrat() {
        return (nc.ccas.gasel.model.v1.TypeContratV1)readProperty("typeContrat");
    } 
    
    
}
