package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.ActiviteV1;
import nc.ccas.gasel.model.v1.ChargeV1;
import nc.ccas.gasel.model.v1.RessourceV1;

/** Class _AdministreV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AdministreV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4423698958873188927L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String HANDICAP_PROPERTY = "handicap";
    public static final String MATRICULE_PROPERTY = "matricule";
    public static final String SUPPRIME_PROPERTY = "supprime";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String PERSONNE_PROPERTY = "Personne";
    public static final String A_OBTENU_PROPERTY = "aObtenu";
    public static final String A_POUR_PROPERTY = "aPour";
    public static final String A_SUIVI_PROPERTY = "aSuivi";
    public static final String A_UNE_PROPERTY = "aUne";
    public static final String EST_AU_CHEF_DE_FAMILLE_PROPERTY = "estAuChefDeFamille";
    public static final String EST_COUVERT_PAR_PROPERTY = "estCouvertPar";
    public static final String EST_DANS_ID_PROPERTY = "estDansID";
    public static final String EST_MUTUALISE_PAR_PROPERTY = "estMutualisePar";
    public static final String POSSEDE_PROPERTY = "possede";
    public static final String T_ACTIVITE_ARRAY_PROPERTY = "tActiviteArray";
    public static final String T_CHARGE_ARRAY_PROPERTY = "tChargeArray";
    public static final String T_RESSOURCE_ARRAY_PROPERTY = "tRessourceArray";

    public static final String T_PERSONNE_ID_PK_COLUMN = "t_personne_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setHandicap(String handicap) {
        writeProperty("handicap", handicap);
    }
    public String getHandicap() {
        return (String)readProperty("handicap");
    }
    
    
    public void setMatricule(String matricule) {
        writeProperty("matricule", matricule);
    }
    public String getMatricule() {
        return (String)readProperty("matricule");
    }
    
    
    public void setSupprime(String supprime) {
        writeProperty("supprime", supprime);
    }
    public String getSupprime() {
        return (String)readProperty("supprime");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setPersonne(nc.ccas.gasel.model.v1.PersonneV1 Personne) {
        setToOneTarget("Personne", Personne, true);
    }

    public nc.ccas.gasel.model.v1.PersonneV1 getPersonne() {
        return (nc.ccas.gasel.model.v1.PersonneV1)readProperty("Personne");
    } 
    
    
    public void setAObtenu(nc.ccas.gasel.model.v1.DiplomeV1 aObtenu) {
        setToOneTarget("aObtenu", aObtenu, true);
    }

    public nc.ccas.gasel.model.v1.DiplomeV1 getAObtenu() {
        return (nc.ccas.gasel.model.v1.DiplomeV1)readProperty("aObtenu");
    } 
    
    
    public void setAPour(nc.ccas.gasel.model.v1.StatutV1 aPour) {
        setToOneTarget("aPour", aPour, true);
    }

    public nc.ccas.gasel.model.v1.StatutV1 getAPour() {
        return (nc.ccas.gasel.model.v1.StatutV1)readProperty("aPour");
    } 
    
    
    public void setASuivi(nc.ccas.gasel.model.v1.NiveauScolaireV1 aSuivi) {
        setToOneTarget("aSuivi", aSuivi, true);
    }

    public nc.ccas.gasel.model.v1.NiveauScolaireV1 getASuivi() {
        return (nc.ccas.gasel.model.v1.NiveauScolaireV1)readProperty("aSuivi");
    } 
    
    
    public void setAUne(nc.ccas.gasel.model.v1.SituationFamillialeV1 aUne) {
        setToOneTarget("aUne", aUne, true);
    }

    public nc.ccas.gasel.model.v1.SituationFamillialeV1 getAUne() {
        return (nc.ccas.gasel.model.v1.SituationFamillialeV1)readProperty("aUne");
    } 
    
    
    public void setEstAuChefDeFamille(nc.ccas.gasel.model.v1.LienAChargeV1 estAuChefDeFamille) {
        setToOneTarget("estAuChefDeFamille", estAuChefDeFamille, true);
    }

    public nc.ccas.gasel.model.v1.LienAChargeV1 getEstAuChefDeFamille() {
        return (nc.ccas.gasel.model.v1.LienAChargeV1)readProperty("estAuChefDeFamille");
    } 
    
    
    public void setEstCouvertPar(nc.ccas.gasel.model.v1.CouvertureSocialeV1 estCouvertPar) {
        setToOneTarget("estCouvertPar", estCouvertPar, true);
    }

    public nc.ccas.gasel.model.v1.CouvertureSocialeV1 getEstCouvertPar() {
        return (nc.ccas.gasel.model.v1.CouvertureSocialeV1)readProperty("estCouvertPar");
    } 
    
    
    public void setEstDansID(nc.ccas.gasel.model.v1.SituationProfessionnelleV1 estDansID) {
        setToOneTarget("estDansID", estDansID, true);
    }

    public nc.ccas.gasel.model.v1.SituationProfessionnelleV1 getEstDansID() {
        return (nc.ccas.gasel.model.v1.SituationProfessionnelleV1)readProperty("estDansID");
    } 
    
    
    public void setEstMutualisePar(nc.ccas.gasel.model.v1.MutuelleV1 estMutualisePar) {
        setToOneTarget("estMutualisePar", estMutualisePar, true);
    }

    public nc.ccas.gasel.model.v1.MutuelleV1 getEstMutualisePar() {
        return (nc.ccas.gasel.model.v1.MutuelleV1)readProperty("estMutualisePar");
    } 
    
    
    public void setPossede(nc.ccas.gasel.model.v1.CarteSejourV1 possede) {
        setToOneTarget("possede", possede, true);
    }

    public nc.ccas.gasel.model.v1.CarteSejourV1 getPossede() {
        return (nc.ccas.gasel.model.v1.CarteSejourV1)readProperty("possede");
    } 
    
    
    public void addToTActiviteArray(nc.ccas.gasel.model.v1.ActiviteV1 obj) {
        addToManyTarget("tActiviteArray", obj, true);
    }
    public void removeFromTActiviteArray(nc.ccas.gasel.model.v1.ActiviteV1 obj) {
        removeToManyTarget("tActiviteArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.ActiviteV1> getTActiviteArray() {
        return (List<ActiviteV1>)readProperty("tActiviteArray");
    }
    
    
    public void addToTChargeArray(nc.ccas.gasel.model.v1.ChargeV1 obj) {
        addToManyTarget("tChargeArray", obj, true);
    }
    public void removeFromTChargeArray(nc.ccas.gasel.model.v1.ChargeV1 obj) {
        removeToManyTarget("tChargeArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.ChargeV1> getTChargeArray() {
        return (List<ChargeV1>)readProperty("tChargeArray");
    }
    
    
    public void addToTRessourceArray(nc.ccas.gasel.model.v1.RessourceV1 obj) {
        addToManyTarget("tRessourceArray", obj, true);
    }
    public void removeFromTRessourceArray(nc.ccas.gasel.model.v1.RessourceV1 obj) {
        removeToManyTarget("tRessourceArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.RessourceV1> getTRessourceArray() {
        return (List<RessourceV1>)readProperty("tRessourceArray");
    }
    
    
}
