package nc.ccas.gasel.model.v1.auto;

/** Class _AdresseV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AdresseV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3796700166395789150L;
	public static final String CHAMP_LIBRE_PROPERTY = "champLibre";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String NUMERODOSSIER_PROPERTY = "numerodossier";
    public static final String THE_CODE_POSTAL_ID_PROPERTY = "theCodePostalId";
    public static final String THE_RUE_ID_PROPERTY = "theRueId";
    public static final String THE_VILLE_ID_PROPERTY = "theVilleId";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String DOSSIER_PROPERTY = "dossier";
    public static final String THE_BP_PROPERTY = "theBP";
    public static final String THE_NUMERO_PROPERTY = "theNumero";

    public static final String T_ADRESSE_ID_PK_COLUMN = "t_adresse_id";

    public void setChampLibre(String champLibre) {
        writeProperty("champLibre", champLibre);
    }
    public String getChampLibre() {
        return (String)readProperty("champLibre");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setNumerodossier(String numerodossier) {
        writeProperty("numerodossier", numerodossier);
    }
    public String getNumerodossier() {
        return (String)readProperty("numerodossier");
    }
    
    
    public void setTheCodePostalId(Integer theCodePostalId) {
        writeProperty("theCodePostalId", theCodePostalId);
    }
    public Integer getTheCodePostalId() {
        return (Integer)readProperty("theCodePostalId");
    }
    
    
    public void setTheRueId(Integer theRueId) {
        writeProperty("theRueId", theRueId);
    }
    public Integer getTheRueId() {
        return (Integer)readProperty("theRueId");
    }
    
    
    public void setTheVilleId(Integer theVilleId) {
        writeProperty("theVilleId", theVilleId);
    }
    public Integer getTheVilleId() {
        return (Integer)readProperty("theVilleId");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.v1.DossierV1 dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.v1.DossierV1 getDossier() {
        return (nc.ccas.gasel.model.v1.DossierV1)readProperty("dossier");
    } 
    
    
    public void setTheBP(nc.ccas.gasel.model.v1.BPV1 theBP) {
        setToOneTarget("theBP", theBP, true);
    }

    public nc.ccas.gasel.model.v1.BPV1 getTheBP() {
        return (nc.ccas.gasel.model.v1.BPV1)readProperty("theBP");
    } 
    
    
    public void setTheNumero(nc.ccas.gasel.model.v1.NumeroV1 theNumero) {
        setToOneTarget("theNumero", theNumero, true);
    }

    public nc.ccas.gasel.model.v1.NumeroV1 getTheNumero() {
        return (nc.ccas.gasel.model.v1.NumeroV1)readProperty("theNumero");
    } 
    
    
}
