package nc.ccas.gasel.model.v1.auto;

/** Class _AideSpecifiqueV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AideSpecifiqueV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 7353426016088413649L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String AIDE_PROPERTY = "Aide";
    public static final String AIDE_EAU_PROPERTY = "AideEau";
    public static final String AIDE_OM_PROPERTY = "AideOM";

    public static final String T_AIDE_ID_PK_COLUMN = "t_aide_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setAide(nc.ccas.gasel.model.v1.AideV1 Aide) {
        setToOneTarget("Aide", Aide, true);
    }

    public nc.ccas.gasel.model.v1.AideV1 getAide() {
        return (nc.ccas.gasel.model.v1.AideV1)readProperty("Aide");
    } 
    
    
    public void setAideEau(nc.ccas.gasel.model.v1.AideEauV1 AideEau) {
        setToOneTarget("AideEau", AideEau, true);
    }

    public nc.ccas.gasel.model.v1.AideEauV1 getAideEau() {
        return (nc.ccas.gasel.model.v1.AideEauV1)readProperty("AideEau");
    } 
    
    
    public void setAideOM(nc.ccas.gasel.model.v1.AideOMV1 AideOM) {
        setToOneTarget("AideOM", AideOM, true);
    }

    public nc.ccas.gasel.model.v1.AideOMV1 getAideOM() {
        return (nc.ccas.gasel.model.v1.AideOMV1)readProperty("AideOM");
    } 
    
    
}
