package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.BonV1;

/** Class _AideV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AideV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6809135423537133005L;
	public static final String CODE_PROPERTY = "code";
    public static final String DATE_DEBUT_PROPERTY = "dateDebut";
    public static final String DATE_FIN_PROPERTY = "dateFin";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String MONTANT_PROPERTY = "montant";
    public static final String QUANTITE_MENSUELLE_PROPERTY = "quantiteMensuelle";
    public static final String TYPE_BUSINESS_PROPERTY = "typeBusiness";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String AIDE_SPECIFIQUE_PROPERTY = "AideSpecifique";
    public static final String A_POUR_FREQUENCE_AIDE_PROPERTY = "aPourFrequenceAide";
    public static final String CONCERNE_DOSSIER_PROPERTY = "concerneDossier";
    public static final String NECESSITE_ARRETE_PROPERTY = "necessiteArrete";
    public static final String T_BON_ARRAY_PROPERTY = "tBonArray";
    public static final String TYPE_AIDE_PROPERTY = "typeAide";

    public static final String T_AIDE_ID_PK_COLUMN = "t_aide_id";

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }
    
    
    public void setDateDebut(java.util.Date dateDebut) {
        writeProperty("dateDebut", dateDebut);
    }
    public java.util.Date getDateDebut() {
        return (java.util.Date)readProperty("dateDebut");
    }
    
    
    public void setDateFin(java.util.Date dateFin) {
        writeProperty("dateFin", dateFin);
    }
    public java.util.Date getDateFin() {
        return (java.util.Date)readProperty("dateFin");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setMontant(Double montant) {
        writeProperty("montant", montant);
    }
    public Double getMontant() {
        return (Double)readProperty("montant");
    }
    
    
    public void setQuantiteMensuelle(Short quantiteMensuelle) {
        writeProperty("quantiteMensuelle", quantiteMensuelle);
    }
    public Short getQuantiteMensuelle() {
        return (Short)readProperty("quantiteMensuelle");
    }
    
    
    public void setTypeBusiness(String typeBusiness) {
        writeProperty("typeBusiness", typeBusiness);
    }
    public String getTypeBusiness() {
        return (String)readProperty("typeBusiness");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setAideSpecifique(nc.ccas.gasel.model.v1.AideSpecifiqueV1 AideSpecifique) {
        setToOneTarget("AideSpecifique", AideSpecifique, true);
    }

    public nc.ccas.gasel.model.v1.AideSpecifiqueV1 getAideSpecifique() {
        return (nc.ccas.gasel.model.v1.AideSpecifiqueV1)readProperty("AideSpecifique");
    } 
    
    
    public void setAPourFrequenceAide(nc.ccas.gasel.model.v1.FrequenceAideV1 aPourFrequenceAide) {
        setToOneTarget("aPourFrequenceAide", aPourFrequenceAide, true);
    }

    public nc.ccas.gasel.model.v1.FrequenceAideV1 getAPourFrequenceAide() {
        return (nc.ccas.gasel.model.v1.FrequenceAideV1)readProperty("aPourFrequenceAide");
    } 
    
    
    public void setConcerneDossier(nc.ccas.gasel.model.v1.DossierV1 concerneDossier) {
        setToOneTarget("concerneDossier", concerneDossier, true);
    }

    public nc.ccas.gasel.model.v1.DossierV1 getConcerneDossier() {
        return (nc.ccas.gasel.model.v1.DossierV1)readProperty("concerneDossier");
    } 
    
    
    public void setNecessiteArrete(nc.ccas.gasel.model.v1.ArreteV1 necessiteArrete) {
        setToOneTarget("necessiteArrete", necessiteArrete, true);
    }

    public nc.ccas.gasel.model.v1.ArreteV1 getNecessiteArrete() {
        return (nc.ccas.gasel.model.v1.ArreteV1)readProperty("necessiteArrete");
    } 
    
    
    public void addToTBonArray(nc.ccas.gasel.model.v1.BonV1 obj) {
        addToManyTarget("tBonArray", obj, true);
    }
    public void removeFromTBonArray(nc.ccas.gasel.model.v1.BonV1 obj) {
        removeToManyTarget("tBonArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.BonV1> getTBonArray() {
        return (List<BonV1>)readProperty("tBonArray");
    }
    
    
    public void setTypeAide(nc.ccas.gasel.model.v1.TypeAideV1 typeAide) {
        setToOneTarget("typeAide", typeAide, true);
    }

    public nc.ccas.gasel.model.v1.TypeAideV1 getTypeAide() {
        return (nc.ccas.gasel.model.v1.TypeAideV1)readProperty("typeAide");
    } 
    
    
}
