package nc.ccas.gasel.model.v1.auto;

/** Class _AideEauV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AideEauV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 4844220935183212764L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String DEPASSEMENT_M3_PROPERTY = "depassementM3";
    public static final String MONTANT_DEJA_PAYE_PROPERTY = "montantDejaPaye";
    public static final String PERIODE_PRESTATION_PROPERTY = "periodePrestation";
    public static final String POLICE_PROPERTY = "police";
    public static final String PRISE_EN_CHARGE_CONSO_PROPERTY = "priseEnChargeConso";
    public static final String RESTANT_DU_PROPERTY = "restantDu";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String AIDE_SPECIFIQUE_PROPERTY = "AideSpecifique";

    public static final String T_AIDE_ID_PK_COLUMN = "t_aide_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setDepassementM3(Double depassementM3) {
        writeProperty("depassementM3", depassementM3);
    }
    public Double getDepassementM3() {
        return (Double)readProperty("depassementM3");
    }
    
    
    public void setMontantDejaPaye(Double montantDejaPaye) {
        writeProperty("montantDejaPaye", montantDejaPaye);
    }
    public Double getMontantDejaPaye() {
        return (Double)readProperty("montantDejaPaye");
    }
    
    
    public void setPeriodePrestation(String periodePrestation) {
        writeProperty("periodePrestation", periodePrestation);
    }
    public String getPeriodePrestation() {
        return (String)readProperty("periodePrestation");
    }
    
    
    public void setPolice(String police) {
        writeProperty("police", police);
    }
    public String getPolice() {
        return (String)readProperty("police");
    }
    
    
    public void setPriseEnChargeConso(Double priseEnChargeConso) {
        writeProperty("priseEnChargeConso", priseEnChargeConso);
    }
    public Double getPriseEnChargeConso() {
        return (Double)readProperty("priseEnChargeConso");
    }
    
    
    public void setRestantDu(Double restantDu) {
        writeProperty("restantDu", restantDu);
    }
    public Double getRestantDu() {
        return (Double)readProperty("restantDu");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setAideSpecifique(nc.ccas.gasel.model.v1.AideSpecifiqueV1 AideSpecifique) {
        setToOneTarget("AideSpecifique", AideSpecifique, true);
    }

    public nc.ccas.gasel.model.v1.AideSpecifiqueV1 getAideSpecifique() {
        return (nc.ccas.gasel.model.v1.AideSpecifiqueV1)readProperty("AideSpecifique");
    } 
    
    
}
