package nc.ccas.gasel.model.v1.auto;

/** Class _AideOMV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AideOMV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1329964433992231768L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String NUMERO_FACTURE_PROPERTY = "numeroFacture";
    public static final String NUMERO_REDEVABLE_PROPERTY = "numeroRedevable";
    public static final String PERIODE_PRESTATION_PROPERTY = "periodePrestation";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String AIDE_SPECIFIQUE_PROPERTY = "AideSpecifique";

    public static final String T_AIDE_ID_PK_COLUMN = "t_aide_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setNumeroFacture(String numeroFacture) {
        writeProperty("numeroFacture", numeroFacture);
    }
    public String getNumeroFacture() {
        return (String)readProperty("numeroFacture");
    }
    
    
    public void setNumeroRedevable(String numeroRedevable) {
        writeProperty("numeroRedevable", numeroRedevable);
    }
    public String getNumeroRedevable() {
        return (String)readProperty("numeroRedevable");
    }
    
    
    public void setPeriodePrestation(String periodePrestation) {
        writeProperty("periodePrestation", periodePrestation);
    }
    public String getPeriodePrestation() {
        return (String)readProperty("periodePrestation");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setAideSpecifique(nc.ccas.gasel.model.v1.AideSpecifiqueV1 AideSpecifique) {
        setToOneTarget("AideSpecifique", AideSpecifique, true);
    }

    public nc.ccas.gasel.model.v1.AideSpecifiqueV1 getAideSpecifique() {
        return (nc.ccas.gasel.model.v1.AideSpecifiqueV1)readProperty("AideSpecifique");
    } 
    
    
}
