package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.AideV1;

/** Class _ArreteV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ArreteV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -7951360354493414891L;
	public static final String CHAMP_PROPERTY = "champ";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String REFERENCE_FICHIER_PROPERTY = "referenceFichier";
    public static final String TYPE_ARRETE_PROPERTY = "typeArrete";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String EST_SUR_BUDGET_IMPUTATION_PROPERTY = "estSurBudgetImputation";
    public static final String T_AIDE_ARRAY_PROPERTY = "tAideArray";

    public static final String T_ARRETE_ID_PK_COLUMN = "t_arrete_id";

    public void setChamp(String champ) {
        writeProperty("champ", champ);
    }
    public String getChamp() {
        return (String)readProperty("champ");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setNumero(String numero) {
        writeProperty("numero", numero);
    }
    public String getNumero() {
        return (String)readProperty("numero");
    }
    
    
    public void setReferenceFichier(String referenceFichier) {
        writeProperty("referenceFichier", referenceFichier);
    }
    public String getReferenceFichier() {
        return (String)readProperty("referenceFichier");
    }
    
    
    public void setTypeArrete(String typeArrete) {
        writeProperty("typeArrete", typeArrete);
    }
    public String getTypeArrete() {
        return (String)readProperty("typeArrete");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setEstSurBudgetImputation(nc.ccas.gasel.model.v1.BudgetImputationV1 estSurBudgetImputation) {
        setToOneTarget("estSurBudgetImputation", estSurBudgetImputation, true);
    }

    public nc.ccas.gasel.model.v1.BudgetImputationV1 getEstSurBudgetImputation() {
        return (nc.ccas.gasel.model.v1.BudgetImputationV1)readProperty("estSurBudgetImputation");
    } 
    
    
    public void addToTAideArray(nc.ccas.gasel.model.v1.AideV1 obj) {
        addToManyTarget("tAideArray", obj, true);
    }
    public void removeFromTAideArray(nc.ccas.gasel.model.v1.AideV1 obj) {
        removeToManyTarget("tAideArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.AideV1> getTAideArray() {
        return (List<AideV1>)readProperty("tAideArray");
    }
    
    
}
