package nc.ccas.gasel.model.v1.auto;

/** Class _ArticleFournisseurV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ArticleFournisseurV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3656907760242936642L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String FOURNISSEUR_ID_PROPERTY = "fournisseurId";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String ARTICLE_PRESTATION_PROPERTY = "articlePrestation";

    public static final String T_ARTICLEFOURNISSEUR_ID_PK_COLUMN = "t_articlefournisseur_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setFournisseurId(Integer fournisseurId) {
        writeProperty("fournisseurId", fournisseurId);
    }
    public Integer getFournisseurId() {
        return (Integer)readProperty("fournisseurId");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setArticlePrestation(nc.ccas.gasel.model.v1.ArticlePrestationV1 articlePrestation) {
        setToOneTarget("articlePrestation", articlePrestation, true);
    }

    public nc.ccas.gasel.model.v1.ArticlePrestationV1 getArticlePrestation() {
        return (nc.ccas.gasel.model.v1.ArticlePrestationV1)readProperty("articlePrestation");
    } 
    
    
}
