package nc.ccas.gasel.model.v1.auto;

/** Class _AssignationGroupeV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AssignationGroupeV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6831262132890820887L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String COMPTE_PROPERTY = "compte";
    public static final String GROUPE_PROPERTY = "groupe";

    public static final String T_ASSIGNATIONGROUPE_ID_PK_COLUMN = "t_assignationgroupe_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setCompte(nc.ccas.gasel.model.v1.CompteV1 compte) {
        setToOneTarget("compte", compte, true);
    }

    public nc.ccas.gasel.model.v1.CompteV1 getCompte() {
        return (nc.ccas.gasel.model.v1.CompteV1)readProperty("compte");
    } 
    
    
    public void setGroupe(nc.ccas.gasel.model.v1.GroupeV1 groupe) {
        setToOneTarget("groupe", groupe, true);
    }

    public nc.ccas.gasel.model.v1.GroupeV1 getGroupe() {
        return (nc.ccas.gasel.model.v1.GroupeV1)readProperty("groupe");
    } 
    
    
}
