package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.PersonneNonAChargeV1;

/** Class _AutreLienV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AutreLienV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6489802149926516673L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String LIEN_DE_PARENTE_PROPERTY = "LienDeParente";
    public static final String T_PERSONNENONACHARGE_ARRAY_PROPERTY = "tPersonnenonachargeArray";

    public static final String T_ENUM_ID_PK_COLUMN = "t_enum_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setLienDeParente(nc.ccas.gasel.model.v1.LienDeParenteV1 LienDeParente) {
        setToOneTarget("LienDeParente", LienDeParente, true);
    }

    public nc.ccas.gasel.model.v1.LienDeParenteV1 getLienDeParente() {
        return (nc.ccas.gasel.model.v1.LienDeParenteV1)readProperty("LienDeParente");
    } 
    
    
    public void addToTPersonnenonachargeArray(nc.ccas.gasel.model.v1.PersonneNonAChargeV1 obj) {
        addToManyTarget("tPersonnenonachargeArray", obj, true);
    }
    public void removeFromTPersonnenonachargeArray(nc.ccas.gasel.model.v1.PersonneNonAChargeV1 obj) {
        removeToManyTarget("tPersonnenonachargeArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.PersonneNonAChargeV1> getTPersonnenonachargeArray() {
        return (List<PersonneNonAChargeV1>)readProperty("tPersonnenonachargeArray");
    }
    
    
}
