package nc.ccas.gasel.model.v1.auto;

/** Class _BonV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _BonV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -7614600012251096663L;
	public static final String DATE_DEBUT_PROPERTY = "dateDebut";
    public static final String DATE_FIN_PROPERTY = "dateFin";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String ETAT_PROPERTY = "etat";
    public static final String MONTANT_PROPERTY = "montant";
    public static final String MONTANT_NON_UTILISE_PROPERTY = "montantNonUtilise";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String SESSION_EDITION_PROPERTY = "sessionEdition";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String CONCERNE_FACTURE_PROPERTY = "concerneFacture";
    public static final String CORRESPOND_AAIDE_PROPERTY = "correspondAAide";

    public static final String T_BON_ID_PK_COLUMN = "t_bon_id";

    public void setDateDebut(java.util.Date dateDebut) {
        writeProperty("dateDebut", dateDebut);
    }
    public java.util.Date getDateDebut() {
        return (java.util.Date)readProperty("dateDebut");
    }
    
    
    public void setDateFin(java.util.Date dateFin) {
        writeProperty("dateFin", dateFin);
    }
    public java.util.Date getDateFin() {
        return (java.util.Date)readProperty("dateFin");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setEtat(String etat) {
        writeProperty("etat", etat);
    }
    public String getEtat() {
        return (String)readProperty("etat");
    }
    
    
    public void setMontant(Double montant) {
        writeProperty("montant", montant);
    }
    public Double getMontant() {
        return (Double)readProperty("montant");
    }
    
    
    public void setMontantNonUtilise(Double montantNonUtilise) {
        writeProperty("montantNonUtilise", montantNonUtilise);
    }
    public Double getMontantNonUtilise() {
        return (Double)readProperty("montantNonUtilise");
    }
    
    
    public void setNumero(String numero) {
        writeProperty("numero", numero);
    }
    public String getNumero() {
        return (String)readProperty("numero");
    }
    
    
    public void setSessionEdition(String sessionEdition) {
        writeProperty("sessionEdition", sessionEdition);
    }
    public String getSessionEdition() {
        return (String)readProperty("sessionEdition");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setConcerneFacture(nc.ccas.gasel.model.v1.FactureV1 concerneFacture) {
        setToOneTarget("concerneFacture", concerneFacture, true);
    }

    public nc.ccas.gasel.model.v1.FactureV1 getConcerneFacture() {
        return (nc.ccas.gasel.model.v1.FactureV1)readProperty("concerneFacture");
    } 
    
    
    public void setCorrespondAAide(nc.ccas.gasel.model.v1.AideV1 correspondAAide) {
        setToOneTarget("correspondAAide", correspondAAide, true);
    }

    public nc.ccas.gasel.model.v1.AideV1 getCorrespondAAide() {
        return (nc.ccas.gasel.model.v1.AideV1)readProperty("correspondAAide");
    } 
    
    
}
