package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.HabilitationBoutonV1;

/** Class _BoutonV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _BoutonV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 2669969961948818660L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String LABEL_PROPERTY = "label";
    public static final String NOM_PROPERTY = "nom";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String COMPOSANT_PROPERTY = "composant";
    public static final String T_HABILITATIONBOUTON_ARRAY_PROPERTY = "tHabilitationboutonArray";

    public static final String T_BOUTON_ID_PK_COLUMN = "t_bouton_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setLabel(String label) {
        writeProperty("label", label);
    }
    public String getLabel() {
        return (String)readProperty("label");
    }
    
    
    public void setNom(String nom) {
        writeProperty("nom", nom);
    }
    public String getNom() {
        return (String)readProperty("nom");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setComposant(nc.ccas.gasel.model.v1.ComposantV1 composant) {
        setToOneTarget("composant", composant, true);
    }

    public nc.ccas.gasel.model.v1.ComposantV1 getComposant() {
        return (nc.ccas.gasel.model.v1.ComposantV1)readProperty("composant");
    } 
    
    
    public void addToTHabilitationboutonArray(nc.ccas.gasel.model.v1.HabilitationBoutonV1 obj) {
        addToManyTarget("tHabilitationboutonArray", obj, true);
    }
    public void removeFromTHabilitationboutonArray(nc.ccas.gasel.model.v1.HabilitationBoutonV1 obj) {
        removeToManyTarget("tHabilitationboutonArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.HabilitationBoutonV1> getTHabilitationboutonArray() {
        return (List<HabilitationBoutonV1>)readProperty("tHabilitationboutonArray");
    }
    
    
}
