package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.ArreteV1;
import nc.ccas.gasel.model.v1.BudgetSecteurAideV1;

/** Class _BudgetImputationV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _BudgetImputationV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4035939267739189287L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String MOIS_PROPERTY = "mois";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String BUDGET_PROPERTY = "Budget";
    public static final String EST_DANS_BUDGET_IMPUTATION_ANNUEL_PROPERTY = "estDansBudgetImputationAnnuel";
    public static final String POUR_IMPUTATION_PROPERTY = "pourImputation";
    public static final String T_ARRETE_ARRAY_PROPERTY = "tArreteArray";
    public static final String T_BUDGETSECTEURAIDE_ARRAY_PROPERTY = "tBudgetsecteuraideArray";

    public static final String T_BUDGET_ID_PK_COLUMN = "t_budget_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setMois(Short mois) {
        writeProperty("mois", mois);
    }
    public Short getMois() {
        return (Short)readProperty("mois");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setBudget(nc.ccas.gasel.model.v1.BudgetV1 Budget) {
        setToOneTarget("Budget", Budget, true);
    }

    public nc.ccas.gasel.model.v1.BudgetV1 getBudget() {
        return (nc.ccas.gasel.model.v1.BudgetV1)readProperty("Budget");
    } 
    
    
    public void setEstDansBudgetImputationAnnuel(nc.ccas.gasel.model.v1.BudgetImputationAnnuelV1 estDansBudgetImputationAnnuel) {
        setToOneTarget("estDansBudgetImputationAnnuel", estDansBudgetImputationAnnuel, true);
    }

    public nc.ccas.gasel.model.v1.BudgetImputationAnnuelV1 getEstDansBudgetImputationAnnuel() {
        return (nc.ccas.gasel.model.v1.BudgetImputationAnnuelV1)readProperty("estDansBudgetImputationAnnuel");
    } 
    
    
    public void setPourImputation(nc.ccas.gasel.model.v1.ImputationV1 pourImputation) {
        setToOneTarget("pourImputation", pourImputation, true);
    }

    public nc.ccas.gasel.model.v1.ImputationV1 getPourImputation() {
        return (nc.ccas.gasel.model.v1.ImputationV1)readProperty("pourImputation");
    } 
    
    
    public void addToTArreteArray(nc.ccas.gasel.model.v1.ArreteV1 obj) {
        addToManyTarget("tArreteArray", obj, true);
    }
    public void removeFromTArreteArray(nc.ccas.gasel.model.v1.ArreteV1 obj) {
        removeToManyTarget("tArreteArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.ArreteV1> getTArreteArray() {
        return (List<ArreteV1>)readProperty("tArreteArray");
    }
    
    
    public void addToTBudgetsecteuraideArray(nc.ccas.gasel.model.v1.BudgetSecteurAideV1 obj) {
        addToManyTarget("tBudgetsecteuraideArray", obj, true);
    }
    public void removeFromTBudgetsecteuraideArray(nc.ccas.gasel.model.v1.BudgetSecteurAideV1 obj) {
        removeToManyTarget("tBudgetsecteuraideArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.BudgetSecteurAideV1> getTBudgetsecteuraideArray() {
        return (List<BudgetSecteurAideV1>)readProperty("tBudgetsecteuraideArray");
    }
    
    
}
