package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.BudgetImputationAnnuelV1;

/** Class _BudgetAnnuelV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _BudgetAnnuelV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -1763801764701773637L;
	public static final String ANNEE_PROPERTY = "annee";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String DATE_VALIDATION_PROPERTY = "dateValidation";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String VALIDE_PROPERTY = "valide";
    public static final String BUDGET_PROPERTY = "Budget";
    public static final String T_BUDGETIMPUTATIONANNUEL_ARRAY_PROPERTY = "tBudgetimputationannuelArray";

    public static final String T_BUDGET_ID_PK_COLUMN = "t_budget_id";

    public void setAnnee(Short annee) {
        writeProperty("annee", annee);
    }
    public Short getAnnee() {
        return (Short)readProperty("annee");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setDateValidation(java.util.Date dateValidation) {
        writeProperty("dateValidation", dateValidation);
    }
    public java.util.Date getDateValidation() {
        return (java.util.Date)readProperty("dateValidation");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setValide(String valide) {
        writeProperty("valide", valide);
    }
    public String getValide() {
        return (String)readProperty("valide");
    }
    
    
    public void setBudget(nc.ccas.gasel.model.v1.BudgetV1 Budget) {
        setToOneTarget("Budget", Budget, true);
    }

    public nc.ccas.gasel.model.v1.BudgetV1 getBudget() {
        return (nc.ccas.gasel.model.v1.BudgetV1)readProperty("Budget");
    } 
    
    
    public void addToTBudgetimputationannuelArray(nc.ccas.gasel.model.v1.BudgetImputationAnnuelV1 obj) {
        addToManyTarget("tBudgetimputationannuelArray", obj, true);
    }
    public void removeFromTBudgetimputationannuelArray(nc.ccas.gasel.model.v1.BudgetImputationAnnuelV1 obj) {
        removeToManyTarget("tBudgetimputationannuelArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.BudgetImputationAnnuelV1> getTBudgetimputationannuelArray() {
        return (List<BudgetImputationAnnuelV1>)readProperty("tBudgetimputationannuelArray");
    }
    
    
}
