package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.LigneVirementV1;

/** Class _BudgetV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _BudgetV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5376228566665560796L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String MONTANT_PROPERTY = "montant";
    public static final String RESTANT_PROPERTY = "restant";
    public static final String TYPE_BUSINESS_PROPERTY = "typeBusiness";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String BUDGET_ANNUEL_PROPERTY = "BudgetAnnuel";
    public static final String BUDGET_IMPUTATION_PROPERTY = "BudgetImputation";
    public static final String BUDGET_IMPUTATION_ANNUEL_PROPERTY = "BudgetImputationAnnuel";
    public static final String BUDGET_SECTEUR_AIDE_PROPERTY = "BudgetSecteurAide";
    public static final String BUDGET_TYPE_PUBLIC_PROPERTY = "BudgetTypePublic";
    public static final String T_LIGNEVIREMENT_ARRAY_PROPERTY = "tLignevirementArray";
    public static final String T_LIGNEVIREMENT_ARRAY1_PROPERTY = "tLignevirementArray1";

    public static final String T_BUDGET_ID_PK_COLUMN = "t_budget_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setMontant(Double montant) {
        writeProperty("montant", montant);
    }
    public Double getMontant() {
        return (Double)readProperty("montant");
    }
    
    
    public void setRestant(Double restant) {
        writeProperty("restant", restant);
    }
    public Double getRestant() {
        return (Double)readProperty("restant");
    }
    
    
    public void setTypeBusiness(String typeBusiness) {
        writeProperty("typeBusiness", typeBusiness);
    }
    public String getTypeBusiness() {
        return (String)readProperty("typeBusiness");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setBudgetAnnuel(nc.ccas.gasel.model.v1.BudgetAnnuelV1 BudgetAnnuel) {
        setToOneTarget("BudgetAnnuel", BudgetAnnuel, true);
    }

    public nc.ccas.gasel.model.v1.BudgetAnnuelV1 getBudgetAnnuel() {
        return (nc.ccas.gasel.model.v1.BudgetAnnuelV1)readProperty("BudgetAnnuel");
    } 
    
    
    public void setBudgetImputation(nc.ccas.gasel.model.v1.BudgetImputationV1 BudgetImputation) {
        setToOneTarget("BudgetImputation", BudgetImputation, true);
    }

    public nc.ccas.gasel.model.v1.BudgetImputationV1 getBudgetImputation() {
        return (nc.ccas.gasel.model.v1.BudgetImputationV1)readProperty("BudgetImputation");
    } 
    
    
    public void setBudgetImputationAnnuel(nc.ccas.gasel.model.v1.BudgetImputationAnnuelV1 BudgetImputationAnnuel) {
        setToOneTarget("BudgetImputationAnnuel", BudgetImputationAnnuel, true);
    }

    public nc.ccas.gasel.model.v1.BudgetImputationAnnuelV1 getBudgetImputationAnnuel() {
        return (nc.ccas.gasel.model.v1.BudgetImputationAnnuelV1)readProperty("BudgetImputationAnnuel");
    } 
    
    
    public void setBudgetSecteurAide(nc.ccas.gasel.model.v1.BudgetSecteurAideV1 BudgetSecteurAide) {
        setToOneTarget("BudgetSecteurAide", BudgetSecteurAide, true);
    }

    public nc.ccas.gasel.model.v1.BudgetSecteurAideV1 getBudgetSecteurAide() {
        return (nc.ccas.gasel.model.v1.BudgetSecteurAideV1)readProperty("BudgetSecteurAide");
    } 
    
    
    public void setBudgetTypePublic(nc.ccas.gasel.model.v1.BudgetTypePublicV1 BudgetTypePublic) {
        setToOneTarget("BudgetTypePublic", BudgetTypePublic, true);
    }

    public nc.ccas.gasel.model.v1.BudgetTypePublicV1 getBudgetTypePublic() {
        return (nc.ccas.gasel.model.v1.BudgetTypePublicV1)readProperty("BudgetTypePublic");
    } 
    
    
    public void addToTLignevirementArray(nc.ccas.gasel.model.v1.LigneVirementV1 obj) {
        addToManyTarget("tLignevirementArray", obj, true);
    }
    public void removeFromTLignevirementArray(nc.ccas.gasel.model.v1.LigneVirementV1 obj) {
        removeToManyTarget("tLignevirementArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.LigneVirementV1> getTLignevirementArray() {
        return (List<LigneVirementV1>)readProperty("tLignevirementArray");
    }
    
    
    public void addToTLignevirementArray1(nc.ccas.gasel.model.v1.LigneVirementV1 obj) {
        addToManyTarget("tLignevirementArray1", obj, true);
    }
    public void removeFromTLignevirementArray1(nc.ccas.gasel.model.v1.LigneVirementV1 obj) {
        removeToManyTarget("tLignevirementArray1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.LigneVirementV1> getTLignevirementArray1() {
        return (List<LigneVirementV1>)readProperty("tLignevirementArray1");
    }
    
    
}
