package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.BudgetImputationV1;

/** Class _BudgetImputationAnnuelV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _BudgetImputationAnnuelV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -5108394195170279813L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String EST_DIVISE_EN_BUDGET_TYPE_PUBLIC_PROPERTY = "estDiviseEnBudgetTypePublic";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String BUDGET_PROPERTY = "Budget";
    public static final String A_POUR_IMPUTATION_PROPERTY = "aPourImputation";
    public static final String EST_DANS_BUDGET_ANNUEL_PROPERTY = "estDansBudgetAnnuel";
    public static final String T_BUDGETIMPUTATION_ARRAY_PROPERTY = "tBudgetimputationArray";

    public static final String T_BUDGET_ID_PK_COLUMN = "t_budget_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setEstDiviseEnBudgetTypePublic(String estDiviseEnBudgetTypePublic) {
        writeProperty("estDiviseEnBudgetTypePublic", estDiviseEnBudgetTypePublic);
    }
    public String getEstDiviseEnBudgetTypePublic() {
        return (String)readProperty("estDiviseEnBudgetTypePublic");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setBudget(nc.ccas.gasel.model.v1.BudgetV1 Budget) {
        setToOneTarget("Budget", Budget, true);
    }

    public nc.ccas.gasel.model.v1.BudgetV1 getBudget() {
        return (nc.ccas.gasel.model.v1.BudgetV1)readProperty("Budget");
    } 
    
    
    public void setAPourImputation(nc.ccas.gasel.model.v1.ImputationV1 aPourImputation) {
        setToOneTarget("aPourImputation", aPourImputation, true);
    }

    public nc.ccas.gasel.model.v1.ImputationV1 getAPourImputation() {
        return (nc.ccas.gasel.model.v1.ImputationV1)readProperty("aPourImputation");
    } 
    
    
    public void setEstDansBudgetAnnuel(nc.ccas.gasel.model.v1.BudgetAnnuelV1 estDansBudgetAnnuel) {
        setToOneTarget("estDansBudgetAnnuel", estDansBudgetAnnuel, true);
    }

    public nc.ccas.gasel.model.v1.BudgetAnnuelV1 getEstDansBudgetAnnuel() {
        return (nc.ccas.gasel.model.v1.BudgetAnnuelV1)readProperty("estDansBudgetAnnuel");
    } 
    
    
    public void addToTBudgetimputationArray(nc.ccas.gasel.model.v1.BudgetImputationV1 obj) {
        addToManyTarget("tBudgetimputationArray", obj, true);
    }
    public void removeFromTBudgetimputationArray(nc.ccas.gasel.model.v1.BudgetImputationV1 obj) {
        removeToManyTarget("tBudgetimputationArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.BudgetImputationV1> getTBudgetimputationArray() {
        return (List<BudgetImputationV1>)readProperty("tBudgetimputationArray");
    }
    
    
}
