package nc.ccas.gasel.model.v1.auto;

/** Class _BudgetTypePublicV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _BudgetTypePublicV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2690923166943988857L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String POUR_TYPE_PUBLIC_ID_PROPERTY = "pourTypePublicId";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String BUDGET_PROPERTY = "Budget";
    public static final String EST_DANS_BUDGET_SECTEUR_AIDE_PROPERTY = "estDansBudgetSecteurAide";

    public static final String T_BUDGET_ID_PK_COLUMN = "t_budget_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setPourTypePublicId(Integer pourTypePublicId) {
        writeProperty("pourTypePublicId", pourTypePublicId);
    }
    public Integer getPourTypePublicId() {
        return (Integer)readProperty("pourTypePublicId");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setBudget(nc.ccas.gasel.model.v1.BudgetV1 Budget) {
        setToOneTarget("Budget", Budget, true);
    }

    public nc.ccas.gasel.model.v1.BudgetV1 getBudget() {
        return (nc.ccas.gasel.model.v1.BudgetV1)readProperty("Budget");
    } 
    
    
    public void setEstDansBudgetSecteurAide(nc.ccas.gasel.model.v1.BudgetSecteurAideV1 estDansBudgetSecteurAide) {
        setToOneTarget("estDansBudgetSecteurAide", estDansBudgetSecteurAide, true);
    }

    public nc.ccas.gasel.model.v1.BudgetSecteurAideV1 getEstDansBudgetSecteurAide() {
        return (nc.ccas.gasel.model.v1.BudgetSecteurAideV1)readProperty("estDansBudgetSecteurAide");
    } 
    
    
}
