package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.AdministreV1;

/** Class _CarteSejourV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _CarteSejourV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 625456243273948399L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String DATE_VALIDITE_PROPERTY = "dateValidite";
    public static final String DATE_VALIDITE_PERMIS_PROPERTY = "dateValiditePermis";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String NUMERO_PERMIS_TRAVAIL_PROPERTY = "numeroPermisTravail";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String T_ADMINISTRE_ARRAY_PROPERTY = "tAdministreArray";

    public static final String T_CARTESEJOUR_ID_PK_COLUMN = "t_cartesejour_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setDateValidite(java.util.Date dateValidite) {
        writeProperty("dateValidite", dateValidite);
    }
    public java.util.Date getDateValidite() {
        return (java.util.Date)readProperty("dateValidite");
    }
    
    
    public void setDateValiditePermis(java.util.Date dateValiditePermis) {
        writeProperty("dateValiditePermis", dateValiditePermis);
    }
    public java.util.Date getDateValiditePermis() {
        return (java.util.Date)readProperty("dateValiditePermis");
    }
    
    
    public void setNumero(String numero) {
        writeProperty("numero", numero);
    }
    public String getNumero() {
        return (String)readProperty("numero");
    }
    
    
    public void setNumeroPermisTravail(String numeroPermisTravail) {
        writeProperty("numeroPermisTravail", numeroPermisTravail);
    }
    public String getNumeroPermisTravail() {
        return (String)readProperty("numeroPermisTravail");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void addToTAdministreArray(nc.ccas.gasel.model.v1.AdministreV1 obj) {
        addToManyTarget("tAdministreArray", obj, true);
    }
    public void removeFromTAdministreArray(nc.ccas.gasel.model.v1.AdministreV1 obj) {
        removeToManyTarget("tAdministreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.AdministreV1> getTAdministreArray() {
        return (List<AdministreV1>)readProperty("tAdministreArray");
    }
    
    
}
