package nc.ccas.gasel.model.v1.auto;

/** Class _ChargeOrganismeV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ChargeOrganismeV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -8832064213602184998L;
	public static final String DATEMODIFICATION_PROPERTY = "datemodification";
    public static final String MONTANTTOTAL_PROPERTY = "montanttotal";
    public static final String NOMORGANISME_PROPERTY = "nomorganisme";
    public static final String TERME_PROPERTY = "terme";
    public static final String USERIDMODIF_PROPERTY = "useridmodif";
    public static final String TO_TCHARGE_PROPERTY = "toTCharge";

    public static final String T_CHARGE_ID_PK_COLUMN = "t_charge_id";

    public void setDatemodification(java.util.Date datemodification) {
        writeProperty("datemodification", datemodification);
    }
    public java.util.Date getDatemodification() {
        return (java.util.Date)readProperty("datemodification");
    }
    
    
    public void setMontanttotal(Double montanttotal) {
        writeProperty("montanttotal", montanttotal);
    }
    public Double getMontanttotal() {
        return (Double)readProperty("montanttotal");
    }
    
    
    public void setNomorganisme(String nomorganisme) {
        writeProperty("nomorganisme", nomorganisme);
    }
    public String getNomorganisme() {
        return (String)readProperty("nomorganisme");
    }
    
    
    public void setTerme(String terme) {
        writeProperty("terme", terme);
    }
    public String getTerme() {
        return (String)readProperty("terme");
    }
    
    
    public void setUseridmodif(String useridmodif) {
        writeProperty("useridmodif", useridmodif);
    }
    public String getUseridmodif() {
        return (String)readProperty("useridmodif");
    }
    
    
    public void setToTCharge(nc.ccas.gasel.model.v1.ChargeV1 toTCharge) {
        setToOneTarget("toTCharge", toTCharge, true);
    }

    public nc.ccas.gasel.model.v1.ChargeV1 getToTCharge() {
        return (nc.ccas.gasel.model.v1.ChargeV1)readProperty("toTCharge");
    } 
    
    
}
