package nc.ccas.gasel.model.v1.auto;

/** Class _ChargeV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ChargeV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5452772911012028825L;
	public static final String DATE_DEBUT_PROPERTY = "dateDebut";
    public static final String DATE_FIN_PROPERTY = "dateFin";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String MONTANT_PROPERTY = "montant";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String EST_DEFINIE_PAR_PROPERTY = "estDefiniePar";
    public static final String THE_ADMINISTRE_PROPERTY = "theAdministre";
    public static final String TO_TCHARGEORGANISME_PROPERTY = "toTChargeorganisme";

    public static final String T_CHARGE_ID_PK_COLUMN = "t_charge_id";

    public void setDateDebut(java.util.Date dateDebut) {
        writeProperty("dateDebut", dateDebut);
    }
    public java.util.Date getDateDebut() {
        return (java.util.Date)readProperty("dateDebut");
    }
    
    
    public void setDateFin(java.util.Date dateFin) {
        writeProperty("dateFin", dateFin);
    }
    public java.util.Date getDateFin() {
        return (java.util.Date)readProperty("dateFin");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setMontant(Double montant) {
        writeProperty("montant", montant);
    }
    public Double getMontant() {
        return (Double)readProperty("montant");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setEstDefiniePar(nc.ccas.gasel.model.v1.TypeChargeV1 estDefiniePar) {
        setToOneTarget("estDefiniePar", estDefiniePar, true);
    }

    public nc.ccas.gasel.model.v1.TypeChargeV1 getEstDefiniePar() {
        return (nc.ccas.gasel.model.v1.TypeChargeV1)readProperty("estDefiniePar");
    } 
    
    
    public void setTheAdministre(nc.ccas.gasel.model.v1.AdministreV1 theAdministre) {
        setToOneTarget("theAdministre", theAdministre, true);
    }

    public nc.ccas.gasel.model.v1.AdministreV1 getTheAdministre() {
        return (nc.ccas.gasel.model.v1.AdministreV1)readProperty("theAdministre");
    } 
    
    
    public void setToTChargeorganisme(nc.ccas.gasel.model.v1.ChargeOrganismeV1 toTChargeorganisme) {
        setToOneTarget("toTChargeorganisme", toTChargeorganisme, true);
    }

    public nc.ccas.gasel.model.v1.ChargeOrganismeV1 getToTChargeorganisme() {
        return (nc.ccas.gasel.model.v1.ChargeOrganismeV1)readProperty("toTChargeorganisme");
    } 
    
    
}
