package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.AssignationGroupeV1;

/** Class _CompteV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _CompteV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4970195897618630692L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String DERNIERE_CONNEXION_PROPERTY = "derniereConnexion";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String T_ASSIGNATIONGROUPE_ARRAY_PROPERTY = "tAssignationgroupeArray";

    public static final String T_COMPTE_ID_PK_COLUMN = "t_compte_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setDerniereConnexion(java.util.Date derniereConnexion) {
        writeProperty("derniereConnexion", derniereConnexion);
    }
    public java.util.Date getDerniereConnexion() {
        return (java.util.Date)readProperty("derniereConnexion");
    }
    
    
    public void setUserId(String userId) {
        writeProperty("userId", userId);
    }
    public String getUserId() {
        return (String)readProperty("userId");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void addToTAssignationgroupeArray(nc.ccas.gasel.model.v1.AssignationGroupeV1 obj) {
        addToManyTarget("tAssignationgroupeArray", obj, true);
    }
    public void removeFromTAssignationgroupeArray(nc.ccas.gasel.model.v1.AssignationGroupeV1 obj) {
        removeToManyTarget("tAssignationgroupeArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.AssignationGroupeV1> getTAssignationgroupeArray() {
        return (List<AssignationGroupeV1>)readProperty("tAssignationgroupeArray");
    }
    
    
}
