package nc.ccas.gasel.model.v1.auto;

/** Class _ConstanteV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ConstanteV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4152256365703586694L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String KEY_CST_PROPERTY = "keyCst";
    public static final String LABEL_PROPERTY = "label";
    public static final String TYPE_VALEUR_PROPERTY = "typeValeur";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String VALEUR_PROPERTY = "valeur";

    public static final String T_CONSTANTE_ID_PK_COLUMN = "t_constante_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setKeyCst(String keyCst) {
        writeProperty("keyCst", keyCst);
    }
    public String getKeyCst() {
        return (String)readProperty("keyCst");
    }
    
    
    public void setLabel(String label) {
        writeProperty("label", label);
    }
    public String getLabel() {
        return (String)readProperty("label");
    }
    
    
    public void setTypeValeur(String typeValeur) {
        writeProperty("typeValeur", typeValeur);
    }
    public String getTypeValeur() {
        return (String)readProperty("typeValeur");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setValeur(String valeur) {
        writeProperty("valeur", valeur);
    }
    public String getValeur() {
        return (String)readProperty("valeur");
    }
    
    
}
