package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.AdministreV1;

/** Class _CouvertureSocialeV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _CouvertureSocialeV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1858101240148175609L;
	public static final String DATE_FIN_VALIDITE_PROPERTY = "dateFinValidite";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String A_TYPE_COUVERTURE_SOCIALE_PROPERTY = "aTypeCouvertureSociale";
    public static final String T_ADMINISTRE_ARRAY_PROPERTY = "tAdministreArray";

    public static final String T_COUVERTURESOCIALE_ID_PK_COLUMN = "t_couverturesociale_id";

    public void setDateFinValidite(java.util.Date dateFinValidite) {
        writeProperty("dateFinValidite", dateFinValidite);
    }
    public java.util.Date getDateFinValidite() {
        return (java.util.Date)readProperty("dateFinValidite");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setNumero(String numero) {
        writeProperty("numero", numero);
    }
    public String getNumero() {
        return (String)readProperty("numero");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setATypeCouvertureSociale(nc.ccas.gasel.model.v1.TypeCouvertureSocialeV1 aTypeCouvertureSociale) {
        setToOneTarget("aTypeCouvertureSociale", aTypeCouvertureSociale, true);
    }

    public nc.ccas.gasel.model.v1.TypeCouvertureSocialeV1 getATypeCouvertureSociale() {
        return (nc.ccas.gasel.model.v1.TypeCouvertureSocialeV1)readProperty("aTypeCouvertureSociale");
    } 
    
    
    public void addToTAdministreArray(nc.ccas.gasel.model.v1.AdministreV1 obj) {
        addToManyTarget("tAdministreArray", obj, true);
    }
    public void removeFromTAdministreArray(nc.ccas.gasel.model.v1.AdministreV1 obj) {
        removeToManyTarget("tAdministreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.AdministreV1> getTAdministreArray() {
        return (List<AdministreV1>)readProperty("tAdministreArray");
    }
    
    
}
