package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.AdresseV1;
import nc.ccas.gasel.model.v1.AideV1;
import nc.ccas.gasel.model.v1.PersonneV1;

/** Class _DossierV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _DossierV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -8976358737640697830L;
	public static final String DATE_ACTUALISATION_PROPERTY = "dateActualisation";
    public static final String DATE_ARRIVEE_DANS_COMMUNE_PROPERTY = "dateArriveeDansCommune";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String DATE_OUVERTURE_PROPERTY = "dateOuverture";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String ADRESSE_HABITATION_PROPERTY = "adresseHabitation";
    public static final String ADRESSE_POSTALE_PROPERTY = "adressePostale";
    public static final String ADRESSES_PROPERTY = "adresses";
    public static final String AIDES_PROPERTY = "aides";
    public static final String PERSONNES_PROPERTY = "personnes";
    public static final String TYPE_HABITAT_PROPERTY = "typeHabitat";
    public static final String TYPE_PUBLIC_PROPERTY = "typePublic";

    public static final String T_DOSSIER_ID_PK_COLUMN = "t_dossier_id";

    public void setDateActualisation(java.util.Date dateActualisation) {
        writeProperty("dateActualisation", dateActualisation);
    }
    public java.util.Date getDateActualisation() {
        return (java.util.Date)readProperty("dateActualisation");
    }
    
    
    public void setDateArriveeDansCommune(java.util.Date dateArriveeDansCommune) {
        writeProperty("dateArriveeDansCommune", dateArriveeDansCommune);
    }
    public java.util.Date getDateArriveeDansCommune() {
        return (java.util.Date)readProperty("dateArriveeDansCommune");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setDateOuverture(java.util.Date dateOuverture) {
        writeProperty("dateOuverture", dateOuverture);
    }
    public java.util.Date getDateOuverture() {
        return (java.util.Date)readProperty("dateOuverture");
    }
    
    
    public void setNumero(String numero) {
        writeProperty("numero", numero);
    }
    public String getNumero() {
        return (String)readProperty("numero");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setAdresseHabitation(nc.ccas.gasel.model.v1.AdresseV1 adresseHabitation) {
        setToOneTarget("adresseHabitation", adresseHabitation, true);
    }

    public nc.ccas.gasel.model.v1.AdresseV1 getAdresseHabitation() {
        return (nc.ccas.gasel.model.v1.AdresseV1)readProperty("adresseHabitation");
    } 
    
    
    public void setAdressePostale(nc.ccas.gasel.model.v1.AdresseV1 adressePostale) {
        setToOneTarget("adressePostale", adressePostale, true);
    }

    public nc.ccas.gasel.model.v1.AdresseV1 getAdressePostale() {
        return (nc.ccas.gasel.model.v1.AdresseV1)readProperty("adressePostale");
    } 
    
    
    public void addToAdresses(nc.ccas.gasel.model.v1.AdresseV1 obj) {
        addToManyTarget("adresses", obj, true);
    }
    public void removeFromAdresses(nc.ccas.gasel.model.v1.AdresseV1 obj) {
        removeToManyTarget("adresses", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.AdresseV1> getAdresses() {
        return (List<AdresseV1>)readProperty("adresses");
    }
    
    
    public void addToAides(nc.ccas.gasel.model.v1.AideV1 obj) {
        addToManyTarget("aides", obj, true);
    }
    public void removeFromAides(nc.ccas.gasel.model.v1.AideV1 obj) {
        removeToManyTarget("aides", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.AideV1> getAides() {
        return (List<AideV1>)readProperty("aides");
    }
    
    
    public void addToPersonnes(nc.ccas.gasel.model.v1.PersonneV1 obj) {
        addToManyTarget("personnes", obj, true);
    }
    public void removeFromPersonnes(nc.ccas.gasel.model.v1.PersonneV1 obj) {
        removeToManyTarget("personnes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.PersonneV1> getPersonnes() {
        return (List<PersonneV1>)readProperty("personnes");
    }
    
    
    public void setTypeHabitat(nc.ccas.gasel.model.v1.TypeHabitatV1 typeHabitat) {
        setToOneTarget("typeHabitat", typeHabitat, true);
    }

    public nc.ccas.gasel.model.v1.TypeHabitatV1 getTypeHabitat() {
        return (nc.ccas.gasel.model.v1.TypeHabitatV1)readProperty("typeHabitat");
    } 
    
    
    public void setTypePublic(nc.ccas.gasel.model.v1.TypePublicV1 typePublic) {
        setToOneTarget("typePublic", typePublic, true);
    }

    public nc.ccas.gasel.model.v1.TypePublicV1 getTypePublic() {
        return (nc.ccas.gasel.model.v1.TypePublicV1)readProperty("typePublic");
    } 
    
    
}
