package nc.ccas.gasel.model.v1.auto;

/** Class _EnumerationV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _EnumerationV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5722496197617058746L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String KEY_PROPERTY = "key";
    public static final String LABEL_PROPERTY = "label";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";

    public static final String T_ENUM_ID_PK_COLUMN = "t_enum_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setKey(String key) {
        writeProperty("key", key);
    }
    public String getKey() {
        return (String)readProperty("key");
    }
    
    
    public void setLabel(String label) {
        writeProperty("label", label);
    }
    public String getLabel() {
        return (String)readProperty("label");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
}
