package nc.ccas.gasel.model.v1.auto;

/** Class _FournisseurV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _FournisseurV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2604218135951671479L;
	public static final String CODE_PROPERTY = "code";
    public static final String DATEMODIFICATION_PROPERTY = "datemodification";
    public static final String NOM_PROPERTY = "nom";

    public static final String T_FOURNISSEUR_ID_PK_COLUMN = "t_fournisseur_id";

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }
    
    
    public void setDatemodification(java.util.Date datemodification) {
        writeProperty("datemodification", datemodification);
    }
    public java.util.Date getDatemodification() {
        return (java.util.Date)readProperty("datemodification");
    }
    
    
    public void setNom(String nom) {
        writeProperty("nom", nom);
    }
    public String getNom() {
        return (String)readProperty("nom");
    }
    
    
}
