package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.AssignationGroupeV1;
import nc.ccas.gasel.model.v1.HabilitationBoutonV1;
import nc.ccas.gasel.model.v1.HabilitationComposantV1;

/** Class _GroupeV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _GroupeV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3183680106226792643L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NOM_PROPERTY = "nom";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String T_ASSIGNATIONGROUPE_ARRAY_PROPERTY = "tAssignationgroupeArray";
    public static final String T_HABILITATIONBOUTON_ARRAY_PROPERTY = "tHabilitationboutonArray";
    public static final String T_HABILITATIONCOMPOSANT_ARRAY_PROPERTY = "tHabilitationcomposantArray";

    public static final String T_GROUPE_ID_PK_COLUMN = "t_groupe_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setNom(String nom) {
        writeProperty("nom", nom);
    }
    public String getNom() {
        return (String)readProperty("nom");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void addToTAssignationgroupeArray(nc.ccas.gasel.model.v1.AssignationGroupeV1 obj) {
        addToManyTarget("tAssignationgroupeArray", obj, true);
    }
    public void removeFromTAssignationgroupeArray(nc.ccas.gasel.model.v1.AssignationGroupeV1 obj) {
        removeToManyTarget("tAssignationgroupeArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.AssignationGroupeV1> getTAssignationgroupeArray() {
        return (List<AssignationGroupeV1>)readProperty("tAssignationgroupeArray");
    }
    
    
    public void addToTHabilitationboutonArray(nc.ccas.gasel.model.v1.HabilitationBoutonV1 obj) {
        addToManyTarget("tHabilitationboutonArray", obj, true);
    }
    public void removeFromTHabilitationboutonArray(nc.ccas.gasel.model.v1.HabilitationBoutonV1 obj) {
        removeToManyTarget("tHabilitationboutonArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.HabilitationBoutonV1> getTHabilitationboutonArray() {
        return (List<HabilitationBoutonV1>)readProperty("tHabilitationboutonArray");
    }
    
    
    public void addToTHabilitationcomposantArray(nc.ccas.gasel.model.v1.HabilitationComposantV1 obj) {
        addToManyTarget("tHabilitationcomposantArray", obj, true);
    }
    public void removeFromTHabilitationcomposantArray(nc.ccas.gasel.model.v1.HabilitationComposantV1 obj) {
        removeToManyTarget("tHabilitationcomposantArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.HabilitationComposantV1> getTHabilitationcomposantArray() {
        return (List<HabilitationComposantV1>)readProperty("tHabilitationcomposantArray");
    }
    
    
}
