package nc.ccas.gasel.model.v1.auto;

/** Class _HabilitationComposantV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _HabilitationComposantV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5775674683554910704L;
	public static final String ACCESSIBLE_PROPERTY = "accessible";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String VISIBLE_PROPERTY = "visible";
    public static final String COMPOSANT_PROPERTY = "composant";
    public static final String GROUPE_PROPERTY = "groupe";

    public static final String T_HABILITATIONCOMPOSANT_ID_PK_COLUMN = "t_habilitationcomposant_id";

    public void setAccessible(String accessible) {
        writeProperty("accessible", accessible);
    }
    public String getAccessible() {
        return (String)readProperty("accessible");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setVisible(String visible) {
        writeProperty("visible", visible);
    }
    public String getVisible() {
        return (String)readProperty("visible");
    }
    
    
    public void setComposant(nc.ccas.gasel.model.v1.ComposantV1 composant) {
        setToOneTarget("composant", composant, true);
    }

    public nc.ccas.gasel.model.v1.ComposantV1 getComposant() {
        return (nc.ccas.gasel.model.v1.ComposantV1)readProperty("composant");
    } 
    
    
    public void setGroupe(nc.ccas.gasel.model.v1.GroupeV1 groupe) {
        setToOneTarget("groupe", groupe, true);
    }

    public nc.ccas.gasel.model.v1.GroupeV1 getGroupe() {
        return (nc.ccas.gasel.model.v1.GroupeV1)readProperty("groupe");
    } 
    
    
}
