package nc.ccas.gasel.model.v1.auto;

/** Class _HabilitationBoutonV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _HabilitationBoutonV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -173785906809234948L;
	public static final String ACCESSIBLE_PROPERTY = "accessible";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String VISIBLE_PROPERTY = "visible";
    public static final String BOUTON_PROPERTY = "bouton";
    public static final String GROUPE_PROPERTY = "groupe";

    public static final String T_HABILITATIONBOUTON_ID_PK_COLUMN = "t_habilitationbouton_id";

    public void setAccessible(String accessible) {
        writeProperty("accessible", accessible);
    }
    public String getAccessible() {
        return (String)readProperty("accessible");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setVisible(String visible) {
        writeProperty("visible", visible);
    }
    public String getVisible() {
        return (String)readProperty("visible");
    }
    
    
    public void setBouton(nc.ccas.gasel.model.v1.BoutonV1 bouton) {
        setToOneTarget("bouton", bouton, true);
    }

    public nc.ccas.gasel.model.v1.BoutonV1 getBouton() {
        return (nc.ccas.gasel.model.v1.BoutonV1)readProperty("bouton");
    } 
    
    
    public void setGroupe(nc.ccas.gasel.model.v1.GroupeV1 groupe) {
        setToOneTarget("groupe", groupe, true);
    }

    public nc.ccas.gasel.model.v1.GroupeV1 getGroupe() {
        return (nc.ccas.gasel.model.v1.GroupeV1)readProperty("groupe");
    } 
    
    
}
