package nc.ccas.gasel.model.v1.auto;

/** Class _LigneVirementV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _LigneVirementV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6125331756145094605L;
	public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String DATE_VIREMENT_PROPERTY = "dateVirement";
    public static final String MONTANT_PROPERTY = "montant";
    public static final String TYPE_VIREMENT_PROPERTY = "typeVirement";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String DE_BUDGET_PROPERTY = "deBudget";
    public static final String VERS_BUDGET_PROPERTY = "versBudget";

    public static final String T_LIGNEVIREMENT_ID_PK_COLUMN = "t_lignevirement_id";

    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setDateVirement(java.util.Date dateVirement) {
        writeProperty("dateVirement", dateVirement);
    }
    public java.util.Date getDateVirement() {
        return (java.util.Date)readProperty("dateVirement");
    }
    
    
    public void setMontant(Double montant) {
        writeProperty("montant", montant);
    }
    public Double getMontant() {
        return (Double)readProperty("montant");
    }
    
    
    public void setTypeVirement(String typeVirement) {
        writeProperty("typeVirement", typeVirement);
    }
    public String getTypeVirement() {
        return (String)readProperty("typeVirement");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setDeBudget(nc.ccas.gasel.model.v1.BudgetV1 deBudget) {
        setToOneTarget("deBudget", deBudget, true);
    }

    public nc.ccas.gasel.model.v1.BudgetV1 getDeBudget() {
        return (nc.ccas.gasel.model.v1.BudgetV1)readProperty("deBudget");
    } 
    
    
    public void setVersBudget(nc.ccas.gasel.model.v1.BudgetV1 versBudget) {
        setToOneTarget("versBudget", versBudget, true);
    }

    public nc.ccas.gasel.model.v1.BudgetV1 getVersBudget() {
        return (nc.ccas.gasel.model.v1.BudgetV1)readProperty("versBudget");
    } 
    
    
}
