package nc.ccas.gasel.model.v1.auto;

import java.util.List;

import nc.ccas.gasel.model.v1.AdresseV1;

/** Class _NumeroV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _NumeroV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4485568482331470621L;
	public static final String DATEMODIFICATION_PROPERTY = "datemodification";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String NUMERODOSSIER_PROPERTY = "numerodossier";
    public static final String USERIDMODIF_PROPERTY = "useridmodif";
    public static final String T_ADRESSE_ARRAY_PROPERTY = "tAdresseArray";

    public static final String T_NUMERO_ID_PK_COLUMN = "t_numero_id";

    public void setDatemodification(java.util.Date datemodification) {
        writeProperty("datemodification", datemodification);
    }
    public java.util.Date getDatemodification() {
        return (java.util.Date)readProperty("datemodification");
    }
    
    
    public void setNumero(String numero) {
        writeProperty("numero", numero);
    }
    public String getNumero() {
        return (String)readProperty("numero");
    }
    
    
    public void setNumerodossier(String numerodossier) {
        writeProperty("numerodossier", numerodossier);
    }
    public String getNumerodossier() {
        return (String)readProperty("numerodossier");
    }
    
    
    public void setUseridmodif(String useridmodif) {
        writeProperty("useridmodif", useridmodif);
    }
    public String getUseridmodif() {
        return (String)readProperty("useridmodif");
    }
    
    
    public void addToTAdresseArray(nc.ccas.gasel.model.v1.AdresseV1 obj) {
        addToManyTarget("tAdresseArray", obj, true);
    }
    public void removeFromTAdresseArray(nc.ccas.gasel.model.v1.AdresseV1 obj) {
        removeToManyTarget("tAdresseArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.v1.AdresseV1> getTAdresseArray() {
        return (List<AdresseV1>)readProperty("tAdresseArray");
    }
    
    
}
