package nc.ccas.gasel.model.v1.auto;

/** Class _PersonneV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _PersonneV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 366562624848935189L;
	public static final String DATE_ARRIVEE_SUR_TERRITOIRE_PROPERTY = "dateArriveeSurTerritoire";
    public static final String DATE_DECES_PROPERTY = "dateDeces";
    public static final String DATE_ENTREE_DANS_FOYER_PROPERTY = "dateEntreeDansFoyer";
    public static final String DATE_MODIFICATION_PROPERTY = "dateModification";
    public static final String DATE_NAISSANCE_PROPERTY = "dateNaissance";
    public static final String DATE_SORTIE_DU_FOYER_PROPERTY = "dateSortieDuFoyer";
    public static final String DESIGNATION_PROPERTY = "designation";
    public static final String EMAIL_PROPERTY = "email";
    public static final String EST_NEE_DANS_ID_PROPERTY = "estNeeDansId";
    public static final String EST_NEE_DANS_VILLE_ETRANGERE_ID_PROPERTY = "estNeeDansVilleEtrangereId";
    public static final String EST_NEE_DANS_VILLE_ETRANGERE_ID2_PROPERTY = "estNeeDansVilleEtrangereId2";
    public static final String MATADM_PROPERTY = "matadm";
    public static final String NATIONALITE_PROPERTY = "nationalite";
    public static final String NOM_PROPERTY = "nom";
    public static final String NOM_JEUNE_FILLE_PROPERTY = "nomJeuneFille";
    public static final String NOM_USAGE_PROPERTY = "nomUsage";
    public static final String PRENOM_PROPERTY = "prenom";
    public static final String PRENOM_USAGE_PROPERTY = "prenomUsage";
    public static final String SEXE_PROPERTY = "sexe";
    public static final String TELEPHONE_FIXE_PROPERTY = "telephoneFixe";
    public static final String TELEPHONE_PORTABLE_PROPERTY = "telephonePortable";
    public static final String USER_ID_MODIF_PROPERTY = "userIdModif";
    public static final String ADMINISTRE_PROPERTY = "Administre";
    public static final String PERSONNE_NON_ACHARGE_PROPERTY = "PersonneNonACharge";
    public static final String EST_CONCERNEE_PAR_PROPERTY = "estConcerneePar";

    public static final String T_PERSONNE_ID_PK_COLUMN = "t_personne_id";

    public void setDateArriveeSurTerritoire(java.util.Date dateArriveeSurTerritoire) {
        writeProperty("dateArriveeSurTerritoire", dateArriveeSurTerritoire);
    }
    public java.util.Date getDateArriveeSurTerritoire() {
        return (java.util.Date)readProperty("dateArriveeSurTerritoire");
    }
    
    
    public void setDateDeces(java.util.Date dateDeces) {
        writeProperty("dateDeces", dateDeces);
    }
    public java.util.Date getDateDeces() {
        return (java.util.Date)readProperty("dateDeces");
    }
    
    
    public void setDateEntreeDansFoyer(java.util.Date dateEntreeDansFoyer) {
        writeProperty("dateEntreeDansFoyer", dateEntreeDansFoyer);
    }
    public java.util.Date getDateEntreeDansFoyer() {
        return (java.util.Date)readProperty("dateEntreeDansFoyer");
    }
    
    
    public void setDateModification(java.util.Date dateModification) {
        writeProperty("dateModification", dateModification);
    }
    public java.util.Date getDateModification() {
        return (java.util.Date)readProperty("dateModification");
    }
    
    
    public void setDateNaissance(java.util.Date dateNaissance) {
        writeProperty("dateNaissance", dateNaissance);
    }
    public java.util.Date getDateNaissance() {
        return (java.util.Date)readProperty("dateNaissance");
    }
    
    
    public void setDateSortieDuFoyer(java.util.Date dateSortieDuFoyer) {
        writeProperty("dateSortieDuFoyer", dateSortieDuFoyer);
    }
    public java.util.Date getDateSortieDuFoyer() {
        return (java.util.Date)readProperty("dateSortieDuFoyer");
    }
    
    
    public void setDesignation(String designation) {
        writeProperty("designation", designation);
    }
    public String getDesignation() {
        return (String)readProperty("designation");
    }
    
    
    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }
    
    
    public void setEstNeeDansId(Integer estNeeDansId) {
        writeProperty("estNeeDansId", estNeeDansId);
    }
    public Integer getEstNeeDansId() {
        return (Integer)readProperty("estNeeDansId");
    }
    
    
    public void setEstNeeDansVilleEtrangereId(Integer estNeeDansVilleEtrangereId) {
        writeProperty("estNeeDansVilleEtrangereId", estNeeDansVilleEtrangereId);
    }
    public Integer getEstNeeDansVilleEtrangereId() {
        return (Integer)readProperty("estNeeDansVilleEtrangereId");
    }
    
    
    public void setEstNeeDansVilleEtrangereId2(Integer estNeeDansVilleEtrangereId2) {
        writeProperty("estNeeDansVilleEtrangereId2", estNeeDansVilleEtrangereId2);
    }
    public Integer getEstNeeDansVilleEtrangereId2() {
        return (Integer)readProperty("estNeeDansVilleEtrangereId2");
    }
    
    
    public void setMatadm(java.math.BigDecimal matadm) {
        writeProperty("matadm", matadm);
    }
    public java.math.BigDecimal getMatadm() {
        return (java.math.BigDecimal)readProperty("matadm");
    }
    
    
    public void setNationalite(String nationalite) {
        writeProperty("nationalite", nationalite);
    }
    public String getNationalite() {
        return (String)readProperty("nationalite");
    }
    
    
    public void setNom(String nom) {
        writeProperty("nom", nom);
    }
    public String getNom() {
        return (String)readProperty("nom");
    }
    
    
    public void setNomJeuneFille(String nomJeuneFille) {
        writeProperty("nomJeuneFille", nomJeuneFille);
    }
    public String getNomJeuneFille() {
        return (String)readProperty("nomJeuneFille");
    }
    
    
    public void setNomUsage(String nomUsage) {
        writeProperty("nomUsage", nomUsage);
    }
    public String getNomUsage() {
        return (String)readProperty("nomUsage");
    }
    
    
    public void setPrenom(String prenom) {
        writeProperty("prenom", prenom);
    }
    public String getPrenom() {
        return (String)readProperty("prenom");
    }
    
    
    public void setPrenomUsage(String prenomUsage) {
        writeProperty("prenomUsage", prenomUsage);
    }
    public String getPrenomUsage() {
        return (String)readProperty("prenomUsage");
    }
    
    
    public void setSexe(String sexe) {
        writeProperty("sexe", sexe);
    }
    public String getSexe() {
        return (String)readProperty("sexe");
    }
    
    
    public void setTelephoneFixe(String telephoneFixe) {
        writeProperty("telephoneFixe", telephoneFixe);
    }
    public String getTelephoneFixe() {
        return (String)readProperty("telephoneFixe");
    }
    
    
    public void setTelephonePortable(String telephonePortable) {
        writeProperty("telephonePortable", telephonePortable);
    }
    public String getTelephonePortable() {
        return (String)readProperty("telephonePortable");
    }
    
    
    public void setUserIdModif(String userIdModif) {
        writeProperty("userIdModif", userIdModif);
    }
    public String getUserIdModif() {
        return (String)readProperty("userIdModif");
    }
    
    
    public void setAdministre(nc.ccas.gasel.model.v1.AdministreV1 Administre) {
        setToOneTarget("Administre", Administre, true);
    }

    public nc.ccas.gasel.model.v1.AdministreV1 getAdministre() {
        return (nc.ccas.gasel.model.v1.AdministreV1)readProperty("Administre");
    } 
    
    
    public void setPersonneNonACharge(nc.ccas.gasel.model.v1.PersonneNonAChargeV1 PersonneNonACharge) {
        setToOneTarget("PersonneNonACharge", PersonneNonACharge, true);
    }

    public nc.ccas.gasel.model.v1.PersonneNonAChargeV1 getPersonneNonACharge() {
        return (nc.ccas.gasel.model.v1.PersonneNonAChargeV1)readProperty("PersonneNonACharge");
    } 
    
    
    public void setEstConcerneePar(nc.ccas.gasel.model.v1.DossierV1 estConcerneePar) {
        setToOneTarget("estConcerneePar", estConcerneePar, true);
    }

    public nc.ccas.gasel.model.v1.DossierV1 getEstConcerneePar() {
        return (nc.ccas.gasel.model.v1.DossierV1)readProperty("estConcerneePar");
    } 
    
    
}
