package nc.ccas.gasel.model.paph.auto;

import java.util.List;

import nc.ccas.gasel.model.paph.DemandeTaxi;

/** Class _AvisCommissionTaxi was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AvisCommissionTaxi extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 2499226827966655560L;
	public static final String DATE_PROPERTY = "date";
    public static final String NOM_PROPERTY = "nom";
    public static final String VALIDE_PROPERTY = "valide";
    public static final String DEMANDES_TAXI_PROPERTY = "demandesTaxi";

    public static final String ID_PK_COLUMN = "id";

    public void setDate(java.util.Date date) {
        writeProperty("date", date);
    }
    public java.util.Date getDate() {
        return (java.util.Date)readProperty("date");
    }
    
    
    public void setNom(String nom) {
        writeProperty("nom", nom);
    }
    public String getNom() {
        return (String)readProperty("nom");
    }
    
    
    public void setValide(Boolean valide) {
        writeProperty("valide", valide);
    }
    public Boolean getValide() {
        return (Boolean)readProperty("valide");
    }
    
    
    public void addToDemandesTaxi(nc.ccas.gasel.model.paph.DemandeTaxi obj) {
        addToManyTarget("demandesTaxi", obj, true);
    }
    public void removeFromDemandesTaxi(nc.ccas.gasel.model.paph.DemandeTaxi obj) {
        removeToManyTarget("demandesTaxi", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.paph.DemandeTaxi> getDemandesTaxi() {
        return (List<DemandeTaxi>)readProperty("demandesTaxi");
    }
    
    
}
