package nc.ccas.gasel.model.paph.auto;

import java.util.List;

import nc.ccas.gasel.model.paph.SerieTickets;

/** Class _DemandeTaxi was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _DemandeTaxi extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 8753900289576306003L;
	public static final String DATE_DEMANDE_PROPERTY = "dateDemande";
    public static final String DATE_ENTREE_PROPERTY = "dateEntree";
    public static final String DATE_FIN_VALIDITE_PROPERTY = "dateFinValidite";
    public static final String DEROGATION_PROPERTY = "derogation";
    public static final String NECESSITE_ACCOMPAGNATEUR_PROPERTY = "necessiteAccompagnateur";
    public static final String TELEPHONE_PROPERTY = "telephone";
    public static final String ADRESSE_PROPERTY = "adresse";
    public static final String COMMISSION_PROPERTY = "commission";
    public static final String DOSSIER_PROPERTY = "dossier";
    public static final String MOTIF_DEROGATION_PROPERTY = "motifDerogation";
    public static final String SERIES_TICKETS_PROPERTY = "seriesTickets";
    public static final String TYPE_HANDICAP_PROPERTY = "typeHandicap";

    public static final String ID_PK_COLUMN = "id";

    public void setDateDemande(java.util.Date dateDemande) {
        writeProperty("dateDemande", dateDemande);
    }
    public java.util.Date getDateDemande() {
        return (java.util.Date)readProperty("dateDemande");
    }
    
    
    public void setDateEntree(java.util.Date dateEntree) {
        writeProperty("dateEntree", dateEntree);
    }
    public java.util.Date getDateEntree() {
        return (java.util.Date)readProperty("dateEntree");
    }
    
    
    public void setDateFinValidite(java.util.Date dateFinValidite) {
        writeProperty("dateFinValidite", dateFinValidite);
    }
    public java.util.Date getDateFinValidite() {
        return (java.util.Date)readProperty("dateFinValidite");
    }
    
    
    public void setDerogation(Boolean derogation) {
        writeProperty("derogation", derogation);
    }
    public Boolean getDerogation() {
        return (Boolean)readProperty("derogation");
    }
    
    
    public void setNecessiteAccompagnateur(Boolean necessiteAccompagnateur) {
        writeProperty("necessiteAccompagnateur", necessiteAccompagnateur);
    }
    public Boolean getNecessiteAccompagnateur() {
        return (Boolean)readProperty("necessiteAccompagnateur");
    }
    
    
    public void setTelephone(String telephone) {
        writeProperty("telephone", telephone);
    }
    public String getTelephone() {
        return (String)readProperty("telephone");
    }
    
    
    public void setAdresse(nc.ccas.gasel.model.core.Adresse adresse) {
        setToOneTarget("adresse", adresse, true);
    }

    public nc.ccas.gasel.model.core.Adresse getAdresse() {
        return (nc.ccas.gasel.model.core.Adresse)readProperty("adresse");
    } 
    
    
    public void setCommission(nc.ccas.gasel.model.paph.AvisCommissionTaxi commission) {
        setToOneTarget("commission", commission, true);
    }

    public nc.ccas.gasel.model.paph.AvisCommissionTaxi getCommission() {
        return (nc.ccas.gasel.model.paph.AvisCommissionTaxi)readProperty("commission");
    } 
    
    
    public void setDossier(nc.ccas.gasel.model.paph.DossierPAPH dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.paph.DossierPAPH getDossier() {
        return (nc.ccas.gasel.model.paph.DossierPAPH)readProperty("dossier");
    } 
    
    
    public void setMotifDerogation(nc.ccas.gasel.model.paph.enums.MotifDerogationPAPH motifDerogation) {
        setToOneTarget("motifDerogation", motifDerogation, true);
    }

    public nc.ccas.gasel.model.paph.enums.MotifDerogationPAPH getMotifDerogation() {
        return (nc.ccas.gasel.model.paph.enums.MotifDerogationPAPH)readProperty("motifDerogation");
    } 
    
    
    public void addToSeriesTickets(nc.ccas.gasel.model.paph.SerieTickets obj) {
        addToManyTarget("seriesTickets", obj, true);
    }
    public void removeFromSeriesTickets(nc.ccas.gasel.model.paph.SerieTickets obj) {
        removeToManyTarget("seriesTickets", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.paph.SerieTickets> getSeriesTickets() {
        return (List<SerieTickets>)readProperty("seriesTickets");
    }
    
    
    public void setTypeHandicap(nc.ccas.gasel.model.paph.enums.Handicap typeHandicap) {
        setToOneTarget("typeHandicap", typeHandicap, true);
    }

    public nc.ccas.gasel.model.paph.enums.Handicap getTypeHandicap() {
        return (nc.ccas.gasel.model.paph.enums.Handicap)readProperty("typeHandicap");
    } 
    
    
}
