package nc.ccas.gasel.model.paph.auto;

/** Class _DeplacementTaxi was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _DeplacementTaxi extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 71566813272930415L;
	public static final String DATE_PROPERTY = "date";
    public static final String LIEU_PROPERTY = "lieu";
    public static final String MONTANT_COURSE_PROPERTY = "montantCourse";
    public static final String NB_PERSONNES_TRANSPORTEES_PROPERTY = "nbPersonnesTransportees";
    public static final String NUMERO_FACTURE_PROPERTY = "numeroFacture";
    public static final String NUMERO_SERIE_TICKET_PROPERTY = "numeroSerieTicket";
    public static final String NUMERO_TICKET_PROPERTY = "numeroTicket";
    public static final String PARTICIPATION_CCAS_PROPERTY = "participationCCAS";
    public static final String PARTICIPATION_USAGER_PROPERTY = "participationUsager";
    public static final String DOSSIER_PROPERTY = "dossier";
    public static final String NATURE_PROPERTY = "nature";

    public static final String ID_PK_COLUMN = "id";

    public void setDate(java.util.Date date) {
        writeProperty("date", date);
    }
    public java.util.Date getDate() {
        return (java.util.Date)readProperty("date");
    }
    
    
    public void setLieu(String lieu) {
        writeProperty("lieu", lieu);
    }
    public String getLieu() {
        return (String)readProperty("lieu");
    }
    
    
    public void setMontantCourse(Integer montantCourse) {
        writeProperty("montantCourse", montantCourse);
    }
    public Integer getMontantCourse() {
        return (Integer)readProperty("montantCourse");
    }
    
    
    public void setNbPersonnesTransportees(Integer nbPersonnesTransportees) {
        writeProperty("nbPersonnesTransportees", nbPersonnesTransportees);
    }
    public Integer getNbPersonnesTransportees() {
        return (Integer)readProperty("nbPersonnesTransportees");
    }
    
    
    public void setNumeroFacture(String numeroFacture) {
        writeProperty("numeroFacture", numeroFacture);
    }
    public String getNumeroFacture() {
        return (String)readProperty("numeroFacture");
    }
    
    
    public void setNumeroSerieTicket(Integer numeroSerieTicket) {
        writeProperty("numeroSerieTicket", numeroSerieTicket);
    }
    public Integer getNumeroSerieTicket() {
        return (Integer)readProperty("numeroSerieTicket");
    }
    
    
    public void setNumeroTicket(Integer numeroTicket) {
        writeProperty("numeroTicket", numeroTicket);
    }
    public Integer getNumeroTicket() {
        return (Integer)readProperty("numeroTicket");
    }
    
    
    public void setParticipationCCAS(Integer participationCCAS) {
        writeProperty("participationCCAS", participationCCAS);
    }
    public Integer getParticipationCCAS() {
        return (Integer)readProperty("participationCCAS");
    }
    
    
    public void setParticipationUsager(Integer participationUsager) {
        writeProperty("participationUsager", participationUsager);
    }
    public Integer getParticipationUsager() {
        return (Integer)readProperty("participationUsager");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.paph.DossierPAPH dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.paph.DossierPAPH getDossier() {
        return (nc.ccas.gasel.model.paph.DossierPAPH)readProperty("dossier");
    } 
    
    
    public void setNature(nc.ccas.gasel.model.paph.enums.NatureDeplacementTaxi nature) {
        setToOneTarget("nature", nature, true);
    }

    public nc.ccas.gasel.model.paph.enums.NatureDeplacementTaxi getNature() {
        return (nc.ccas.gasel.model.paph.enums.NatureDeplacementTaxi)readProperty("nature");
    } 
    
    
}
