package nc.ccas.gasel.model.paph.auto;

import java.util.List;

import nc.ccas.gasel.model.paph.AccompagnementPAPH;
import nc.ccas.gasel.model.paph.DemandeTaxi;
import nc.ccas.gasel.model.paph.DeplacementTaxi;
import nc.ccas.gasel.model.paph.HandicapPAPH;
import nc.ccas.gasel.model.paph.ProcurationPAPH;
import nc.ccas.gasel.model.paph.SpecificiteCartePAPH;

/** Class _DossierPAPH was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _DossierPAPH extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6740335268282449214L;
	public static final String AIDES_PROVISOIRES_PROPERTY = "aidesProvisoires";
    public static final String ARCHIVAGE_PROPERTY = "archivage";
    public static final String BESOIN_LOGEMENT_PROPERTY = "besoinLogement";
    public static final String BESOIN_MOBILIER_PROPERTY = "besoinMobilier";
    public static final String CORH_PROPERTY = "corh";
    public static final String DATE_CREATION_PROPERTY = "dateCreation";
    public static final String EST_HANDICAPE_PROPERTY = "estHandicape";
    public static final String FIN_CORH_PROPERTY = "finCorh";
    public static final String MODIF_DATE_PROPERTY = "modifDate";
    public static final String NOMBRE_ENFANTS_PROPERTY = "nombreEnfants";
    public static final String PASSAGE_HANDICAPEE_PROPERTY = "passageHandicapee";
    public static final String PASSAGE_PERMANENT_PROPERTY = "passagePermanent";
    public static final String REVENU_NET_MENSUEL_PROPERTY = "revenuNetMensuel";
    public static final String SOUS_CURATELLE_PROPERTY = "sousCuratelle";
    public static final String SOUS_TUTELLE_PROPERTY = "sousTutelle";
    public static final String ACCOMPAGNEMENTS_PROPERTY = "accompagnements";
    public static final String DEMANDES_TAXI_PROPERTY = "demandesTaxi";
    public static final String DEPLACEMENTS_TAXI_PROPERTY = "deplacementsTaxi";
    public static final String DOSSIER_PROPERTY = "dossier";
    public static final String HANDICAPS_PROPERTY = "handicaps";
    public static final String MODIF_UTILISATEUR_PROPERTY = "modifUtilisateur";
    public static final String PERSONNE_PROPERTY = "personne";
    public static final String PROCURATIONS_PROPERTY = "procurations";
    public static final String SITUATION_SOCIALE_PROPERTY = "situationSociale";
    public static final String SPECIFICITES_CARTE_PROPERTY = "specificitesCarte";
    public static final String STATUT_OCCUPATION_PROPERTY = "statutOccupation";

    public static final String ID_PK_COLUMN = "id";

    public void setAidesProvisoires(Boolean aidesProvisoires) {
        writeProperty("aidesProvisoires", aidesProvisoires);
    }
    public Boolean getAidesProvisoires() {
        return (Boolean)readProperty("aidesProvisoires");
    }
    
    
    public void setArchivage(java.util.Date archivage) {
        writeProperty("archivage", archivage);
    }
    public java.util.Date getArchivage() {
        return (java.util.Date)readProperty("archivage");
    }
    
    
    public void setBesoinLogement(Boolean besoinLogement) {
        writeProperty("besoinLogement", besoinLogement);
    }
    public Boolean getBesoinLogement() {
        return (Boolean)readProperty("besoinLogement");
    }
    
    
    public void setBesoinMobilier(Boolean besoinMobilier) {
        writeProperty("besoinMobilier", besoinMobilier);
    }
    public Boolean getBesoinMobilier() {
        return (Boolean)readProperty("besoinMobilier");
    }
    
    
    public void setCorh(Boolean corh) {
        writeProperty("corh", corh);
    }
    public Boolean getCorh() {
        return (Boolean)readProperty("corh");
    }
    
    
    public void setDateCreation(java.util.Date dateCreation) {
        writeProperty("dateCreation", dateCreation);
    }
    public java.util.Date getDateCreation() {
        return (java.util.Date)readProperty("dateCreation");
    }
    
    
    public void setEstHandicape(Boolean estHandicape) {
        writeProperty("estHandicape", estHandicape);
    }
    public Boolean getEstHandicape() {
        return (Boolean)readProperty("estHandicape");
    }
    
    
    public void setFinCorh(java.util.Date finCorh) {
        writeProperty("finCorh", finCorh);
    }
    public java.util.Date getFinCorh() {
        return (java.util.Date)readProperty("finCorh");
    }
    
    
    public void setModifDate(java.util.Date modifDate) {
        writeProperty("modifDate", modifDate);
    }
    public java.util.Date getModifDate() {
        return (java.util.Date)readProperty("modifDate");
    }
    
    
    public void setNombreEnfants(Integer nombreEnfants) {
        writeProperty("nombreEnfants", nombreEnfants);
    }
    public Integer getNombreEnfants() {
        return (Integer)readProperty("nombreEnfants");
    }
    
    
    public void setPassageHandicapee(java.util.Date passageHandicapee) {
        writeProperty("passageHandicapee", passageHandicapee);
    }
    public java.util.Date getPassageHandicapee() {
        return (java.util.Date)readProperty("passageHandicapee");
    }
    
    
    public void setPassagePermanent(java.util.Date passagePermanent) {
        writeProperty("passagePermanent", passagePermanent);
    }
    public java.util.Date getPassagePermanent() {
        return (java.util.Date)readProperty("passagePermanent");
    }
    
    
    public void setRevenuNetMensuel(Integer revenuNetMensuel) {
        writeProperty("revenuNetMensuel", revenuNetMensuel);
    }
    public Integer getRevenuNetMensuel() {
        return (Integer)readProperty("revenuNetMensuel");
    }
    
    
    public void setSousCuratelle(Boolean sousCuratelle) {
        writeProperty("sousCuratelle", sousCuratelle);
    }
    public Boolean getSousCuratelle() {
        return (Boolean)readProperty("sousCuratelle");
    }
    
    
    public void setSousTutelle(Boolean sousTutelle) {
        writeProperty("sousTutelle", sousTutelle);
    }
    public Boolean getSousTutelle() {
        return (Boolean)readProperty("sousTutelle");
    }
    
    
    public void addToAccompagnements(nc.ccas.gasel.model.paph.AccompagnementPAPH obj) {
        addToManyTarget("accompagnements", obj, true);
    }
    public void removeFromAccompagnements(nc.ccas.gasel.model.paph.AccompagnementPAPH obj) {
        removeToManyTarget("accompagnements", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.paph.AccompagnementPAPH> getAccompagnements() {
        return (List<AccompagnementPAPH>)readProperty("accompagnements");
    }
    
    
    public void addToDemandesTaxi(nc.ccas.gasel.model.paph.DemandeTaxi obj) {
        addToManyTarget("demandesTaxi", obj, true);
    }
    public void removeFromDemandesTaxi(nc.ccas.gasel.model.paph.DemandeTaxi obj) {
        removeToManyTarget("demandesTaxi", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.paph.DemandeTaxi> getDemandesTaxi() {
        return (List<DemandeTaxi>)readProperty("demandesTaxi");
    }
    
    
    public void addToDeplacementsTaxi(nc.ccas.gasel.model.paph.DeplacementTaxi obj) {
        addToManyTarget("deplacementsTaxi", obj, true);
    }
    public void removeFromDeplacementsTaxi(nc.ccas.gasel.model.paph.DeplacementTaxi obj) {
        removeToManyTarget("deplacementsTaxi", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.paph.DeplacementTaxi> getDeplacementsTaxi() {
        return (List<DeplacementTaxi>)readProperty("deplacementsTaxi");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.paph.AspectDossierPAPH dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.paph.AspectDossierPAPH getDossier() {
        return (nc.ccas.gasel.model.paph.AspectDossierPAPH)readProperty("dossier");
    } 
    
    
    public void addToHandicaps(nc.ccas.gasel.model.paph.HandicapPAPH obj) {
        addToManyTarget("handicaps", obj, true);
    }
    public void removeFromHandicaps(nc.ccas.gasel.model.paph.HandicapPAPH obj) {
        removeToManyTarget("handicaps", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.paph.HandicapPAPH> getHandicaps() {
        return (List<HandicapPAPH>)readProperty("handicaps");
    }
    
    
    public void setModifUtilisateur(nc.ccas.gasel.model.core.Utilisateur modifUtilisateur) {
        setToOneTarget("modifUtilisateur", modifUtilisateur, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getModifUtilisateur() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("modifUtilisateur");
    } 
    
    
    public void setPersonne(nc.ccas.gasel.model.core.Personne personne) {
        setToOneTarget("personne", personne, true);
    }

    public nc.ccas.gasel.model.core.Personne getPersonne() {
        return (nc.ccas.gasel.model.core.Personne)readProperty("personne");
    } 
    
    
    public void addToProcurations(nc.ccas.gasel.model.paph.ProcurationPAPH obj) {
        addToManyTarget("procurations", obj, true);
    }
    public void removeFromProcurations(nc.ccas.gasel.model.paph.ProcurationPAPH obj) {
        removeToManyTarget("procurations", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.paph.ProcurationPAPH> getProcurations() {
        return (List<ProcurationPAPH>)readProperty("procurations");
    }
    
    
    public void setSituationSociale(nc.ccas.gasel.model.paph.enums.SituationSociale situationSociale) {
        setToOneTarget("situationSociale", situationSociale, true);
    }

    public nc.ccas.gasel.model.paph.enums.SituationSociale getSituationSociale() {
        return (nc.ccas.gasel.model.paph.enums.SituationSociale)readProperty("situationSociale");
    } 
    
    
    public void addToSpecificitesCarte(nc.ccas.gasel.model.paph.SpecificiteCartePAPH obj) {
        addToManyTarget("specificitesCarte", obj, true);
    }
    public void removeFromSpecificitesCarte(nc.ccas.gasel.model.paph.SpecificiteCartePAPH obj) {
        removeToManyTarget("specificitesCarte", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.paph.SpecificiteCartePAPH> getSpecificitesCarte() {
        return (List<SpecificiteCartePAPH>)readProperty("specificitesCarte");
    }
    
    
    public void setStatutOccupation(nc.ccas.gasel.model.paph.enums.StatutOccupation statutOccupation) {
        setToOneTarget("statutOccupation", statutOccupation, true);
    }

    public nc.ccas.gasel.model.paph.enums.StatutOccupation getStatutOccupation() {
        return (nc.ccas.gasel.model.paph.enums.StatutOccupation)readProperty("statutOccupation");
    } 
    
    
}
