package nc.ccas.gasel.model.paph.auto;

/** Class _HandicapPAPH was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _HandicapPAPH extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -1994854448729278564L;
	public static final String DOSSIER_PROPERTY = "dossier";
    public static final String HANDICAP_PROPERTY = "handicap";
    public static final String TAUX_PROPERTY = "taux";

    public static final String DOSSIER_ID_PK_COLUMN = "dossier_id";
    public static final String HANDICAP_ID_PK_COLUMN = "handicap_id";

    public void setDossier(nc.ccas.gasel.model.paph.DossierPAPH dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.paph.DossierPAPH getDossier() {
        return (nc.ccas.gasel.model.paph.DossierPAPH)readProperty("dossier");
    } 
    
    
    public void setHandicap(nc.ccas.gasel.model.paph.enums.Handicap handicap) {
        setToOneTarget("handicap", handicap, true);
    }

    public nc.ccas.gasel.model.paph.enums.Handicap getHandicap() {
        return (nc.ccas.gasel.model.paph.enums.Handicap)readProperty("handicap");
    } 
    
    
    public void setTaux(nc.ccas.gasel.model.paph.enums.TauxHandicap taux) {
        setToOneTarget("taux", taux, true);
    }

    public nc.ccas.gasel.model.paph.enums.TauxHandicap getTaux() {
        return (nc.ccas.gasel.model.paph.enums.TauxHandicap)readProperty("taux");
    } 
    
    
}
