package nc.ccas.gasel.model.paph.auto;

import java.util.List;

import nc.ccas.gasel.model.paph.ObjectifProbPAPH;

/** Class _ObjectifPAPH was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ObjectifPAPH extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -5213039136464018090L;
	public static final String ECHEANCE_PROPERTY = "echeance";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String ACCOMPAGNEMENT_PROPERTY = "accompagnement";
    public static final String PROBLEMATIQUES_PROPERTY = "problematiques";

    public static final String ID_PK_COLUMN = "id";

    public void setEcheance(java.util.Date echeance) {
        writeProperty("echeance", echeance);
    }
    public java.util.Date getEcheance() {
        return (java.util.Date)readProperty("echeance");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setAccompagnement(nc.ccas.gasel.model.paph.AccompagnementPAPH accompagnement) {
        setToOneTarget("accompagnement", accompagnement, true);
    }

    public nc.ccas.gasel.model.paph.AccompagnementPAPH getAccompagnement() {
        return (nc.ccas.gasel.model.paph.AccompagnementPAPH)readProperty("accompagnement");
    } 
    
    
    public void addToProblematiques(nc.ccas.gasel.model.paph.ObjectifProbPAPH obj) {
        addToManyTarget("problematiques", obj, true);
    }
    public void removeFromProblematiques(nc.ccas.gasel.model.paph.ObjectifProbPAPH obj) {
        removeToManyTarget("problematiques", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.paph.ObjectifProbPAPH> getProblematiques() {
        return (List<ObjectifProbPAPH>)readProperty("problematiques");
    }
    
    
}
