package nc.ccas.gasel.model.paph.auto;

/** Class _ProcurationPAPH was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ProcurationPAPH extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 7365586336317705887L;
	public static final String NOM_PROPERTY = "nom";
    public static final String PRENOM_PROPERTY = "prenom";
    public static final String DOSSIER_PROPERTY = "dossier";

    public static final String ID_PK_COLUMN = "id";

    public void setNom(String nom) {
        writeProperty("nom", nom);
    }
    public String getNom() {
        return (String)readProperty("nom");
    }
    
    
    public void setPrenom(String prenom) {
        writeProperty("prenom", prenom);
    }
    public String getPrenom() {
        return (String)readProperty("prenom");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.paph.DossierPAPH dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.paph.DossierPAPH getDossier() {
        return (nc.ccas.gasel.model.paph.DossierPAPH)readProperty("dossier");
    } 
    
    
}
