package nc.ccas.gasel.model.paph.auto;

/** Class _SerieTickets was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _SerieTickets extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2772643855372062377L;
	public static final String DATE_RENOUVELLEMENT_PROPERTY = "dateRenouvellement";
    public static final String DATE_TRANSMISSION_PROPERTY = "dateTransmission";
    public static final String NOMBRE_TICKETS_PROPERTY = "nombreTickets";
    public static final String NUM_DEBUT_PROPERTY = "numDebut";
    public static final String DEMANDE_TAXI_PROPERTY = "demandeTaxi";

    public static final String ID_PK_COLUMN = "id";

    public void setDateRenouvellement(java.util.Date dateRenouvellement) {
        writeProperty("dateRenouvellement", dateRenouvellement);
    }
    public java.util.Date getDateRenouvellement() {
        return (java.util.Date)readProperty("dateRenouvellement");
    }
    
    
    public void setDateTransmission(java.util.Date dateTransmission) {
        writeProperty("dateTransmission", dateTransmission);
    }
    public java.util.Date getDateTransmission() {
        return (java.util.Date)readProperty("dateTransmission");
    }
    
    
    public void setNombreTickets(Integer nombreTickets) {
        writeProperty("nombreTickets", nombreTickets);
    }
    public Integer getNombreTickets() {
        return (Integer)readProperty("nombreTickets");
    }
    
    
    public void setNumDebut(Integer numDebut) {
        writeProperty("numDebut", numDebut);
    }
    public Integer getNumDebut() {
        return (Integer)readProperty("numDebut");
    }
    
    
    public void setDemandeTaxi(nc.ccas.gasel.model.paph.DemandeTaxi demandeTaxi) {
        setToOneTarget("demandeTaxi", demandeTaxi, true);
    }

    public nc.ccas.gasel.model.paph.DemandeTaxi getDemandeTaxi() {
        return (nc.ccas.gasel.model.paph.DemandeTaxi)readProperty("demandeTaxi");
    } 
    
    
}
