package nc.ccas.gasel.model.core.docs.auto;

/** Class _RefModeleDocument was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _RefModeleDocument extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -1860809036991951487L;
	public static final String KEY_PROPERTY = "key";
    public static final String MODELE_PROPERTY = "modele";

    public static final String ID_PK_COLUMN = "id";

    public void setKey(String key) {
        writeProperty("key", key);
    }
    public String getKey() {
        return (String)readProperty("key");
    }
    
    
    public void setModele(nc.ccas.gasel.model.core.docs.ModeleDocument modele) {
        setToOneTarget("modele", modele, true);
    }

    public nc.ccas.gasel.model.core.docs.ModeleDocument getModele() {
        return (nc.ccas.gasel.model.core.docs.ModeleDocument)readProperty("modele");
    } 
    
    
}
