package nc.ccas.gasel.model.core.enums.auto;

import java.util.List;

import nc.ccas.gasel.model.core.enums.Problematique;
import nc.ccas.gasel.model.core.enums.ReponseProblematique;

/** Class _TypeProblematique was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _TypeProblematique extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6715474655271028208L;
	public static final String ACTIF_PROPERTY = "actif";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String LOCKED_PROPERTY = "locked";
    public static final String PROBLEMATIQUES_PROPERTY = "problematiques";
    public static final String REPONSES_PROPERTY = "reponses";

    public static final String ID_PK_COLUMN = "id";

    public void setActif(Boolean actif) {
        writeProperty("actif", actif);
    }
    public Boolean getActif() {
        return (Boolean)readProperty("actif");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }
    
    
    public void addToProblematiques(nc.ccas.gasel.model.core.enums.Problematique obj) {
        addToManyTarget("problematiques", obj, true);
    }
    public void removeFromProblematiques(nc.ccas.gasel.model.core.enums.Problematique obj) {
        removeToManyTarget("problematiques", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.core.enums.Problematique> getProblematiques() {
        return (List<Problematique>)readProperty("problematiques");
    }
    
    
    public void addToReponses(nc.ccas.gasel.model.core.enums.ReponseProblematique obj) {
        addToManyTarget("reponses", obj, true);
    }
    public void removeFromReponses(nc.ccas.gasel.model.core.enums.ReponseProblematique obj) {
        removeToManyTarget("reponses", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.core.enums.ReponseProblematique> getReponses() {
        return (List<ReponseProblematique>)readProperty("reponses");
    }
    
    
}
