package nc.ccas.gasel.model.mairie.auto;

/** Class _CodePostalEtranger was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _CodePostalEtranger extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5262577876848277048L;
	public static final String LIBELLE_PROPERTY = "libelle";
    public static final String PAYS_PROPERTY = "pays";

    public static final String CDPOSE_PK_COLUMN = "cdpose";
    public static final String CODPAY_PK_COLUMN = "codpay";
    public static final String SCODPA_PK_COLUMN = "scodpa";

    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setPays(nc.ccas.gasel.model.mairie.Pays pays) {
        setToOneTarget("pays", pays, true);
    }

    public nc.ccas.gasel.model.mairie.Pays getPays() {
        return (nc.ccas.gasel.model.mairie.Pays)readProperty("pays");
    } 
    
    
}
