package nc.ccas.gasel.model.mairie.auto;

import java.util.List;

import nc.ccas.gasel.model.mairie.Commune;

/** Class _Departement was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Departement extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -8573226784973461355L;
	public static final String CODE_PROPERTY = "code";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String COMMUNES_PROPERTY = "communes";

    public static final String CODDEP_PK_COLUMN = "coddep";

    public void setCode(Integer code) {
        writeProperty("code", code);
    }
    public Integer getCode() {
        return (Integer)readProperty("code");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void addToCommunes(nc.ccas.gasel.model.mairie.Commune obj) {
        addToManyTarget("communes", obj, true);
    }
    public void removeFromCommunes(nc.ccas.gasel.model.mairie.Commune obj) {
        removeToManyTarget("communes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.mairie.Commune> getCommunes() {
        return (List<Commune>)readProperty("communes");
    }
    
    
}
