package nc.ccas.gasel.model.mairie.auto;

/** Class _TypeActiviteV1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _TypeActiviteV1 extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5640218267509719543L;

	public static final String LIBPRO_PROPERTY = "libpro";

    public static final String CODPRO_PK_COLUMN = "codpro";

    public void setLibpro(String libpro) {
        writeProperty("libpro", libpro);
    }
    public String getLibpro() {
        return (String)readProperty("libpro");
    }
    
    
}
