package nc.ccas.gasel.model.mairie.auto;

/** Class _VoieQuartier was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _VoieQuartier extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -1129474547028983374L;
	public static final String CODE_COMMUNE_PROPERTY = "codeCommune";
    public static final String COMMUNE_PROPERTY = "commune";
    public static final String QUARTIER_PROPERTY = "quartier";
    public static final String VOIE_PROPERTY = "voie";

    public static final String CDVOIE_PK_COLUMN = "cdvoie";
    public static final String QUARTI_PK_COLUMN = "quarti";

    public void setCodeCommune(java.math.BigDecimal codeCommune) {
        writeProperty("codeCommune", codeCommune);
    }
    public java.math.BigDecimal getCodeCommune() {
        return (java.math.BigDecimal)readProperty("codeCommune");
    }
    
    
    public void setCommune(nc.ccas.gasel.model.mairie.Commune commune) {
        setToOneTarget("commune", commune, true);
    }

    public nc.ccas.gasel.model.mairie.Commune getCommune() {
        return (nc.ccas.gasel.model.mairie.Commune)readProperty("commune");
    } 
    
    
    public void setQuartier(nc.ccas.gasel.model.mairie.Quartier quartier) {
        setToOneTarget("quartier", quartier, true);
    }

    public nc.ccas.gasel.model.mairie.Quartier getQuartier() {
        return (nc.ccas.gasel.model.mairie.Quartier)readProperty("quartier");
    } 
    
    
    public void setVoie(nc.ccas.gasel.model.mairie.Voie voie) {
        setToOneTarget("voie", voie, true);
    }

    public nc.ccas.gasel.model.mairie.Voie getVoie() {
        return (nc.ccas.gasel.model.mairie.Voie)readProperty("voie");
    } 
    
    
}
