package nc.ccas.gasel.model.pi.auto;

import java.util.List;

import nc.ccas.gasel.model.pi.DemandeJF;

/** Class _AspectDossierPI was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AspectDossierPI extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5686199065048760922L;
	public static final String DEMANDES_PROPERTY = "demandes";
    public static final String DOSSIER_PROPERTY = "dossier";
    public static final String REFERENT_FAMILIAL_PROPERTY = "referentFamilial";

    public static final String DOSSIER_ID_PK_COLUMN = "dossier_id";

    public void addToDemandes(nc.ccas.gasel.model.pi.DemandeJF obj) {
        addToManyTarget("demandes", obj, true);
    }
    public void removeFromDemandes(nc.ccas.gasel.model.pi.DemandeJF obj) {
        removeToManyTarget("demandes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pi.DemandeJF> getDemandes() {
        return (List<DemandeJF>)readProperty("demandes");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.core.Dossier dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.core.Dossier getDossier() {
        return (nc.ccas.gasel.model.core.Dossier)readProperty("dossier");
    } 
    
    
    public void setReferentFamilial(nc.ccas.gasel.model.core.Utilisateur referentFamilial) {
        setToOneTarget("referentFamilial", referentFamilial, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getReferentFamilial() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("referentFamilial");
    } 
    
    
}
