package nc.ccas.gasel.model.pi.auto;

import java.util.List;

import nc.ccas.gasel.model.pi.DemandeJF;

/** Class _AvisCommissionJF was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AvisCommissionJF extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1081895564524404258L;
	public static final String ACTIF_PROPERTY = "actif";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String LOCKED_PROPERTY = "locked";
    public static final String VALIDANT_PROPERTY = "validant";
    public static final String DEMANDES_PROPERTY = "demandes";

    public static final String ID_PK_COLUMN = "id";

    public void setActif(Boolean actif) {
        writeProperty("actif", actif);
    }
    public Boolean getActif() {
        return (Boolean)readProperty("actif");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }
    
    
    public void setValidant(Boolean validant) {
        writeProperty("validant", validant);
    }
    public Boolean getValidant() {
        return (Boolean)readProperty("validant");
    }
    
    
    public void addToDemandes(nc.ccas.gasel.model.pi.DemandeJF obj) {
        addToManyTarget("demandes", obj, true);
    }
    public void removeFromDemandes(nc.ccas.gasel.model.pi.DemandeJF obj) {
        removeToManyTarget("demandes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pi.DemandeJF> getDemandes() {
        return (List<DemandeJF>)readProperty("demandes");
    }
    
    
}
