package nc.ccas.gasel.model.pi.auto;

/** Class _Courrier was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Courrier extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 4384171234961697206L;
	public static final String ARRIVEE_PROPERTY = "arrivee";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String DEMANDE_PROPERTY = "demande";
    public static final String TYPE_PROPERTY = "type";

    public static final String ID_PK_COLUMN = "id";

    public void setArrivee(java.util.Date arrivee) {
        writeProperty("arrivee", arrivee);
    }
    public java.util.Date getArrivee() {
        return (java.util.Date)readProperty("arrivee");
    }
    
    
    public void setNumero(Integer numero) {
        writeProperty("numero", numero);
    }
    public Integer getNumero() {
        return (Integer)readProperty("numero");
    }
    
    
    public void setDemande(nc.ccas.gasel.model.pi.DemandeJF demande) {
        setToOneTarget("demande", demande, true);
    }

    public nc.ccas.gasel.model.pi.DemandeJF getDemande() {
        return (nc.ccas.gasel.model.pi.DemandeJF)readProperty("demande");
    } 
    
    
    public void setType(nc.ccas.gasel.model.pi.enums.TypeCourrierJF type) {
        setToOneTarget("type", type, true);
    }

    public nc.ccas.gasel.model.pi.enums.TypeCourrierJF getType() {
        return (nc.ccas.gasel.model.pi.enums.TypeCourrierJF)readProperty("type");
    } 
    
    
}
