package nc.ccas.gasel.model.pi.auto;

import java.util.List;

import nc.ccas.gasel.model.pi.JardinFamilial;

/** Class _Lieu was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Lieu extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -484542552564803426L;
	public static final String ACTIF_PROPERTY = "actif";
    public static final String CODE_QUARTIER_PROPERTY = "codeQuartier";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String LOCKED_PROPERTY = "locked";
    public static final String JARDINS_PROPERTY = "jardins";

    public static final String ID_PK_COLUMN = "id";

    public void setActif(Boolean actif) {
        writeProperty("actif", actif);
    }
    public Boolean getActif() {
        return (Boolean)readProperty("actif");
    }
    
    
    public void setCodeQuartier(String codeQuartier) {
        writeProperty("codeQuartier", codeQuartier);
    }
    public String getCodeQuartier() {
        return (String)readProperty("codeQuartier");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }
    
    
    public void addToJardins(nc.ccas.gasel.model.pi.JardinFamilial obj) {
        addToManyTarget("jardins", obj, true);
    }
    public void removeFromJardins(nc.ccas.gasel.model.pi.JardinFamilial obj) {
        removeToManyTarget("jardins", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pi.JardinFamilial> getJardins() {
        return (List<JardinFamilial>)readProperty("jardins");
    }
    
    
}
