package nc.ccas.gasel.model.pi.auto;

/** Class _Paiement was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Paiement extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 4865925036743636910L;
	public static final String DEBUT_PROPERTY = "debut";
    public static final String FIN_PROPERTY = "fin";
    public static final String MONTANT_PROPERTY = "montant";
    public static final String NUM_RECU_PROPERTY = "numRecu";
    public static final String NUM_TITRE_RECETTE_PROPERTY = "numTitreRecette";
    public static final String ATTRIBUTION_PROPERTY = "attribution";

    public static final String ID_PK_COLUMN = "id";

    public void setDebut(java.util.Date debut) {
        writeProperty("debut", debut);
    }
    public java.util.Date getDebut() {
        return (java.util.Date)readProperty("debut");
    }
    
    
    public void setFin(java.util.Date fin) {
        writeProperty("fin", fin);
    }
    public java.util.Date getFin() {
        return (java.util.Date)readProperty("fin");
    }
    
    
    public void setMontant(Double montant) {
        writeProperty("montant", montant);
    }
    public Double getMontant() {
        return (Double)readProperty("montant");
    }
    
    
    public void setNumRecu(String numRecu) {
        writeProperty("numRecu", numRecu);
    }
    public String getNumRecu() {
        return (String)readProperty("numRecu");
    }
    
    
    public void setNumTitreRecette(String numTitreRecette) {
        writeProperty("numTitreRecette", numTitreRecette);
    }
    public String getNumTitreRecette() {
        return (String)readProperty("numTitreRecette");
    }
    
    
    public void setAttribution(nc.ccas.gasel.model.pi.AttributionJF attribution) {
        setToOneTarget("attribution", attribution, true);
    }

    public nc.ccas.gasel.model.pi.AttributionJF getAttribution() {
        return (nc.ccas.gasel.model.pi.AttributionJF)readProperty("attribution");
    } 
    
    
}
