package nc.ccas.gasel.model.pi.auto;

import java.util.List;

import nc.ccas.gasel.model.pi.AttributionJF;

/** Class _Parcelle was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Parcelle extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 4521047172467294053L;
	public static final String NUMERO_PROPERTY = "numero";
    public static final String ATTRIBUTIONS_PROPERTY = "attributions";
    public static final String JARDIN_PROPERTY = "jardin";

    public static final String ID_PK_COLUMN = "id";

    public void setNumero(Integer numero) {
        writeProperty("numero", numero);
    }
    public Integer getNumero() {
        return (Integer)readProperty("numero");
    }
    
    
    public void addToAttributions(nc.ccas.gasel.model.pi.AttributionJF obj) {
        addToManyTarget("attributions", obj, true);
    }
    public void removeFromAttributions(nc.ccas.gasel.model.pi.AttributionJF obj) {
        removeToManyTarget("attributions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.pi.AttributionJF> getAttributions() {
        return (List<AttributionJF>)readProperty("attributions");
    }
    
    
    public void setJardin(nc.ccas.gasel.model.pi.JardinFamilial jardin) {
        setToOneTarget("jardin", jardin, true);
    }

    public nc.ccas.gasel.model.pi.JardinFamilial getJardin() {
        return (nc.ccas.gasel.model.pi.JardinFamilial)readProperty("jardin");
    } 
    
    
}
