package nc.ccas.gasel.model.aides.auto;

/** Class _AideOM was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AideOM extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1177882273295673068L;
	public static final String NUMERO_FACTURE_PROPERTY = "numeroFacture";
    public static final String NUMERO_REDEVABLE_PROPERTY = "numeroRedevable";
    public static final String PERIODE_PRESTATION_PROPERTY = "periodePrestation";

    public static final String ID_PK_COLUMN = "id";

    public void setNumeroFacture(String numeroFacture) {
        writeProperty("numeroFacture", numeroFacture);
    }
    public String getNumeroFacture() {
        return (String)readProperty("numeroFacture");
    }
    
    
    public void setNumeroRedevable(String numeroRedevable) {
        writeProperty("numeroRedevable", numeroRedevable);
    }
    public String getNumeroRedevable() {
        return (String)readProperty("numeroRedevable");
    }
    
    
    public void setPeriodePrestation(String periodePrestation) {
        writeProperty("periodePrestation", periodePrestation);
    }
    public String getPeriodePrestation() {
        return (String)readProperty("periodePrestation");
    }
    
    
}
