package nc.ccas.gasel.model.aides.auto;

import java.util.List;

/** Class _Aide was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Aide extends org.apache.cayenne.CayenneDataObject {

    public static final String DATE_COMMISSION_PROPERTY = "dateCommission";
    public static final String DEBUT_PROPERTY = "debut";
    public static final String FIN_PROPERTY = "fin";
    public static final String MODIF_DATE_PROPERTY = "modifDate";
    public static final String MONTANT_PROPERTY = "montant";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String QUANTITE_MENSUELLE_PROPERTY = "quantiteMensuelle";
    public static final String BONS_PROPERTY = "bons";
    public static final String DOSSIER_PROPERTY = "dossier";
    public static final String EAU_PROPERTY = "eau";
    public static final String MODIF_UTILISATEUR_PROPERTY = "modifUtilisateur";
    public static final String MONTANTS_PROPERTY = "montants";
    public static final String NATURE_PROPERTY = "nature";
    public static final String ORDURES_MENAGERES_PROPERTY = "orduresMenageres";
    public static final String PUBLIC_PROPERTY = "public";
    public static final String STATUT_PROPERTY = "statut";

    public static final String ID_PK_COLUMN = "id";

    public void setDateCommission(java.util.Date dateCommission) {
        writeProperty("dateCommission", dateCommission);
    }
    public java.util.Date getDateCommission() {
        return (java.util.Date)readProperty("dateCommission");
    }
    
    
    public void setDebut(java.util.Date debut) {
        writeProperty("debut", debut);
    }
    public java.util.Date getDebut() {
        return (java.util.Date)readProperty("debut");
    }
    
    
    public void setFin(java.util.Date fin) {
        writeProperty("fin", fin);
    }
    public java.util.Date getFin() {
        return (java.util.Date)readProperty("fin");
    }
    
    
    public void setModifDate(java.util.Date modifDate) {
        writeProperty("modifDate", modifDate);
    }
    public java.util.Date getModifDate() {
        return (java.util.Date)readProperty("modifDate");
    }
    
    
    public void setMontant(Integer montant) {
        writeProperty("montant", montant);
    }
    public Integer getMontant() {
        return (Integer)readProperty("montant");
    }
    
    
    public void setNumero(String numero) {
        writeProperty("numero", numero);
    }
    public String getNumero() {
        return (String)readProperty("numero");
    }
    
    
    public void setQuantiteMensuelle(Integer quantiteMensuelle) {
        writeProperty("quantiteMensuelle", quantiteMensuelle);
    }
    public Integer getQuantiteMensuelle() {
        return (Integer)readProperty("quantiteMensuelle");
    }
    
    
    public void addToBons(nc.ccas.gasel.model.aides.Bon obj) {
        addToManyTarget("bons", obj, true);
    }
    public void removeFromBons(nc.ccas.gasel.model.aides.Bon obj) {
        removeToManyTarget("bons", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.aides.Bon> getBons() {
        return (List)readProperty("bons");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.aides.AspectAides dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.aides.AspectAides getDossier() {
        return (nc.ccas.gasel.model.aides.AspectAides)readProperty("dossier");
    } 
    
    
    public void setEau(nc.ccas.gasel.model.aides.AideEau eau) {
        setToOneTarget("eau", eau, true);
    }

    public nc.ccas.gasel.model.aides.AideEau getEau() {
        return (nc.ccas.gasel.model.aides.AideEau)readProperty("eau");
    } 
    
    
    public void setModifUtilisateur(nc.ccas.gasel.model.core.Utilisateur modifUtilisateur) {
        setToOneTarget("modifUtilisateur", modifUtilisateur, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getModifUtilisateur() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("modifUtilisateur");
    } 
    
    
    public void addToMontants(nc.ccas.gasel.model.vues.AideResumeMontants obj) {
        addToManyTarget("montants", obj, true);
    }
    public void removeFromMontants(nc.ccas.gasel.model.vues.AideResumeMontants obj) {
        removeToManyTarget("montants", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.vues.AideResumeMontants> getMontants() {
        return (List)readProperty("montants");
    }
    
    
    public void setNature(nc.ccas.gasel.model.budget.NatureAide nature) {
        setToOneTarget("nature", nature, true);
    }

    public nc.ccas.gasel.model.budget.NatureAide getNature() {
        return (nc.ccas.gasel.model.budget.NatureAide)readProperty("nature");
    } 
    
    
    public void setOrduresMenageres(nc.ccas.gasel.model.aides.AideOM orduresMenageres) {
        setToOneTarget("orduresMenageres", orduresMenageres, true);
    }

    public nc.ccas.gasel.model.aides.AideOM getOrduresMenageres() {
        return (nc.ccas.gasel.model.aides.AideOM)readProperty("orduresMenageres");
    } 
    
    
    public void setPublic(nc.ccas.gasel.model.core.enums.TypePublic _public) {
        setToOneTarget("public", _public, true);
    }

    public nc.ccas.gasel.model.core.enums.TypePublic getPublic() {
        return (nc.ccas.gasel.model.core.enums.TypePublic)readProperty("public");
    } 
    
    
    public void setStatut(nc.ccas.gasel.model.aides.StatutAide statut) {
        setToOneTarget("statut", statut, true);
    }

    public nc.ccas.gasel.model.aides.StatutAide getStatut() {
        return (nc.ccas.gasel.model.aides.StatutAide)readProperty("statut");
    } 
    
    
}
