package nc.ccas.gasel.model.aides.auto;

/** Class _AideRefusee was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AideRefusee extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -8602414071563887290L;
	public static final String DEMANDE_PROPERTY = "demande";
    public static final String REFUS_PROPERTY = "refus";
    public static final String DOSSIER_PROPERTY = "dossier";
    public static final String MOTIF_PROPERTY = "motif";
    public static final String NATURE_DEMANDE_PROPERTY = "natureDemande";

    public static final String ID_PK_COLUMN = "id";

    public void setDemande(java.util.Date demande) {
        writeProperty("demande", demande);
    }
    public java.util.Date getDemande() {
        return (java.util.Date)readProperty("demande");
    }
    
    
    public void setRefus(java.util.Date refus) {
        writeProperty("refus", refus);
    }
    public java.util.Date getRefus() {
        return (java.util.Date)readProperty("refus");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.aides.AspectAides dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.aides.AspectAides getDossier() {
        return (nc.ccas.gasel.model.aides.AspectAides)readProperty("dossier");
    } 
    
    
    public void setMotif(nc.ccas.gasel.model.aides.MotifRefusAide motif) {
        setToOneTarget("motif", motif, true);
    }

    public nc.ccas.gasel.model.aides.MotifRefusAide getMotif() {
        return (nc.ccas.gasel.model.aides.MotifRefusAide)readProperty("motif");
    } 
    
    
    public void setNatureDemande(nc.ccas.gasel.model.budget.NatureAide natureDemande) {
        setToOneTarget("natureDemande", natureDemande, true);
    }

    public nc.ccas.gasel.model.budget.NatureAide getNatureDemande() {
        return (nc.ccas.gasel.model.budget.NatureAide)readProperty("natureDemande");
    } 
    
    
}
