package nc.ccas.gasel.model.aides.auto;

import java.util.List;

import nc.ccas.gasel.model.aides.UsageBon;

/** Class _Arrete was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Arrete extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2907280652522614185L;
	public static final String CHAMP_PROPERTY = "champ";
    public static final String CREATION_PROPERTY = "creation";
    public static final String EDITE_PROPERTY = "edite";
    public static final String MODIF_DATE_PROPERTY = "modifDate";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String REFERENCE_FICHIER_PROPERTY = "referenceFichier";
    public static final String BONS_VALIDES_PROPERTY = "bonsValides";
    public static final String MODIF_UTILISATEUR_PROPERTY = "modifUtilisateur";
    public static final String TYPE_PROPERTY = "type";

    public static final String ID_PK_COLUMN = "id";

    public void setChamp(String champ) {
        writeProperty("champ", champ);
    }
    public String getChamp() {
        return (String)readProperty("champ");
    }
    
    
    public void setCreation(java.util.Date creation) {
        writeProperty("creation", creation);
    }
    public java.util.Date getCreation() {
        return (java.util.Date)readProperty("creation");
    }
    
    
    public void setEdite(Boolean edite) {
        writeProperty("edite", edite);
    }
    public Boolean getEdite() {
        return (Boolean)readProperty("edite");
    }
    
    
    public void setModifDate(java.util.Date modifDate) {
        writeProperty("modifDate", modifDate);
    }
    public java.util.Date getModifDate() {
        return (java.util.Date)readProperty("modifDate");
    }
    
    
    public void setNumero(String numero) {
        writeProperty("numero", numero);
    }
    public String getNumero() {
        return (String)readProperty("numero");
    }
    
    
    public void setReferenceFichier(String referenceFichier) {
        writeProperty("referenceFichier", referenceFichier);
    }
    public String getReferenceFichier() {
        return (String)readProperty("referenceFichier");
    }
    
    
    public void addToBonsValides(nc.ccas.gasel.model.aides.UsageBon obj) {
        addToManyTarget("bonsValides", obj, true);
    }
    public void removeFromBonsValides(nc.ccas.gasel.model.aides.UsageBon obj) {
        removeToManyTarget("bonsValides", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.aides.UsageBon> getBonsValides() {
        return (List<UsageBon>)readProperty("bonsValides");
    }
    
    
    public void setModifUtilisateur(nc.ccas.gasel.model.core.Utilisateur modifUtilisateur) {
        setToOneTarget("modifUtilisateur", modifUtilisateur, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getModifUtilisateur() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("modifUtilisateur");
    } 
    
    
    public void setType(nc.ccas.gasel.model.aides.TypeArrete type) {
        setToOneTarget("type", type, true);
    }

    public nc.ccas.gasel.model.aides.TypeArrete getType() {
        return (nc.ccas.gasel.model.aides.TypeArrete)readProperty("type");
    } 
    
    
}
