package nc.ccas.gasel.model.aides.auto;

import java.util.List;

import nc.ccas.gasel.model.aides.Aide;
import nc.ccas.gasel.model.aides.AideRefusee;

/** Class _AspectAides was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _AspectAides extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -1701870769121951009L;
	public static final String AIDES_PROPERTY = "aides";
    public static final String AIDES_REFUSEES_PROPERTY = "aidesRefusees";
    public static final String DOSSIER_PROPERTY = "dossier";

    public static final String DOSSIER_ID_PK_COLUMN = "dossier_id";

    public void addToAides(nc.ccas.gasel.model.aides.Aide obj) {
        addToManyTarget("aides", obj, true);
    }
    public void removeFromAides(nc.ccas.gasel.model.aides.Aide obj) {
        removeToManyTarget("aides", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.aides.Aide> getAides() {
        return (List<Aide>)readProperty("aides");
    }
    
    
    public void addToAidesRefusees(nc.ccas.gasel.model.aides.AideRefusee obj) {
        addToManyTarget("aidesRefusees", obj, true);
    }
    public void removeFromAidesRefusees(nc.ccas.gasel.model.aides.AideRefusee obj) {
        removeToManyTarget("aidesRefusees", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.aides.AideRefusee> getAidesRefusees() {
        return (List<AideRefusee>)readProperty("aidesRefusees");
    }
    
    
    public void setDossier(nc.ccas.gasel.model.core.Dossier dossier) {
        setToOneTarget("dossier", dossier, true);
    }

    public nc.ccas.gasel.model.core.Dossier getDossier() {
        return (nc.ccas.gasel.model.core.Dossier)readProperty("dossier");
    } 
    
    
}
