package nc.ccas.gasel.model.aides.auto;

import java.util.List;

import nc.ccas.gasel.model.aides.UsageBon;

/** Class _Bon was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Bon extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1276874613689690918L;
	public static final String DEBUT_PROPERTY = "debut";
    public static final String FIN_PROPERTY = "fin";
    public static final String MODIF_DATE_PROPERTY = "modifDate";
    public static final String MONTANT_PROPERTY = "montant";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String SESSION_EDITION_PROPERTY = "sessionEdition";
    public static final String AIDE_PROPERTY = "aide";
    public static final String ETAT_PROPERTY = "etat";
    public static final String MODIF_UTILISATEUR_PROPERTY = "modifUtilisateur";
    public static final String PERSONNE_PROPERTY = "personne";
    public static final String USAGES_PROPERTY = "usages";

    public static final String ID_PK_COLUMN = "id";

    public void setDebut(java.util.Date debut) {
        writeProperty("debut", debut);
    }
    public java.util.Date getDebut() {
        return (java.util.Date)readProperty("debut");
    }
    
    
    public void setFin(java.util.Date fin) {
        writeProperty("fin", fin);
    }
    public java.util.Date getFin() {
        return (java.util.Date)readProperty("fin");
    }
    
    
    public void setModifDate(java.util.Date modifDate) {
        writeProperty("modifDate", modifDate);
    }
    public java.util.Date getModifDate() {
        return (java.util.Date)readProperty("modifDate");
    }
    
    
    public void setMontant(Integer montant) {
        writeProperty("montant", montant);
    }
    public Integer getMontant() {
        return (Integer)readProperty("montant");
    }
    
    
    public void setNumero(String numero) {
        writeProperty("numero", numero);
    }
    public String getNumero() {
        return (String)readProperty("numero");
    }
    
    
    public void setSessionEdition(String sessionEdition) {
        writeProperty("sessionEdition", sessionEdition);
    }
    public String getSessionEdition() {
        return (String)readProperty("sessionEdition");
    }
    
    
    public void setAide(nc.ccas.gasel.model.aides.Aide aide) {
        setToOneTarget("aide", aide, true);
    }

    public nc.ccas.gasel.model.aides.Aide getAide() {
        return (nc.ccas.gasel.model.aides.Aide)readProperty("aide");
    } 
    
    
    public void setEtat(nc.ccas.gasel.model.aides.EtatBon etat) {
        setToOneTarget("etat", etat, true);
    }

    public nc.ccas.gasel.model.aides.EtatBon getEtat() {
        return (nc.ccas.gasel.model.aides.EtatBon)readProperty("etat");
    } 
    
    
    public void setModifUtilisateur(nc.ccas.gasel.model.core.Utilisateur modifUtilisateur) {
        setToOneTarget("modifUtilisateur", modifUtilisateur, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getModifUtilisateur() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("modifUtilisateur");
    } 
    
    
    public void setPersonne(nc.ccas.gasel.model.core.Personne personne) {
        setToOneTarget("personne", personne, true);
    }

    public nc.ccas.gasel.model.core.Personne getPersonne() {
        return (nc.ccas.gasel.model.core.Personne)readProperty("personne");
    } 
    
    
    public void addToUsages(nc.ccas.gasel.model.aides.UsageBon obj) {
        addToManyTarget("usages", obj, true);
    }
    public void removeFromUsages(nc.ccas.gasel.model.aides.UsageBon obj) {
        removeToManyTarget("usages", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.aides.UsageBon> getUsages() {
        return (List<UsageBon>)readProperty("usages");
    }
    
    
}
