package nc.ccas.gasel.model.aides.auto;

import java.util.List;

import nc.ccas.gasel.model.aides.PartieFacture;

/** Class _Facture was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Facture extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3762798439333433736L;
	public static final String CREATION_PROPERTY = "creation";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String MODIF_DATE_PROPERTY = "modifDate";
    public static final String MONTANT_PROPERTY = "montant";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String VALIDATION_PROPERTY = "validation";
    public static final String VALIDE_PROPERTY = "valide";
    public static final String FOURNISSEUR_PROPERTY = "fournisseur";
    public static final String MODIF_UTILISATEUR_PROPERTY = "modifUtilisateur";
    public static final String PARTIES_PROPERTY = "parties";

    public static final String ID_PK_COLUMN = "id";

    public void setCreation(java.util.Date creation) {
        writeProperty("creation", creation);
    }
    public java.util.Date getCreation() {
        return (java.util.Date)readProperty("creation");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setModifDate(java.util.Date modifDate) {
        writeProperty("modifDate", modifDate);
    }
    public java.util.Date getModifDate() {
        return (java.util.Date)readProperty("modifDate");
    }
    
    
    public void setMontant(Integer montant) {
        writeProperty("montant", montant);
    }
    public Integer getMontant() {
        return (Integer)readProperty("montant");
    }
    
    
    public void setNumero(String numero) {
        writeProperty("numero", numero);
    }
    public String getNumero() {
        return (String)readProperty("numero");
    }
    
    
    public void setValidation(java.util.Date validation) {
        writeProperty("validation", validation);
    }
    public java.util.Date getValidation() {
        return (java.util.Date)readProperty("validation");
    }
    
    
    public void setValide(Boolean valide) {
        writeProperty("valide", valide);
    }
    public Boolean getValide() {
        return (Boolean)readProperty("valide");
    }
    
    
    public void setFournisseur(nc.ccas.gasel.model.mairie.FournisseurMairie fournisseur) {
        setToOneTarget("fournisseur", fournisseur, true);
    }

    public nc.ccas.gasel.model.mairie.FournisseurMairie getFournisseur() {
        return (nc.ccas.gasel.model.mairie.FournisseurMairie)readProperty("fournisseur");
    } 
    
    
    public void setModifUtilisateur(nc.ccas.gasel.model.core.Utilisateur modifUtilisateur) {
        setToOneTarget("modifUtilisateur", modifUtilisateur, true);
    }

    public nc.ccas.gasel.model.core.Utilisateur getModifUtilisateur() {
        return (nc.ccas.gasel.model.core.Utilisateur)readProperty("modifUtilisateur");
    } 
    
    
    public void addToParties(nc.ccas.gasel.model.aides.PartieFacture obj) {
        addToManyTarget("parties", obj, true);
    }
    public void removeFromParties(nc.ccas.gasel.model.aides.PartieFacture obj) {
        removeToManyTarget("parties", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.aides.PartieFacture> getParties() {
        return (List<PartieFacture>)readProperty("parties");
    }
    
    
}
