package nc.ccas.gasel.model.aides.auto;

import java.util.List;

import nc.ccas.gasel.model.aides.UsageBon;

/** Class _PartieFacture was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _PartieFacture extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3277238272914103670L;
	public static final String LIBELLE_PROPERTY = "libelle";
    public static final String BONS_PROPERTY = "bons";
    public static final String FACTURE_PROPERTY = "facture";

    public static final String ID_PK_COLUMN = "id";

    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void addToBons(nc.ccas.gasel.model.aides.UsageBon obj) {
        addToManyTarget("bons", obj, true);
    }
    public void removeFromBons(nc.ccas.gasel.model.aides.UsageBon obj) {
        removeToManyTarget("bons", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.aides.UsageBon> getBons() {
        return (List<UsageBon>)readProperty("bons");
    }
    
    
    public void setFacture(nc.ccas.gasel.model.aides.Facture facture) {
        setToOneTarget("facture", facture, true);
    }

    public nc.ccas.gasel.model.aides.Facture getFacture() {
        return (nc.ccas.gasel.model.aides.Facture)readProperty("facture");
    } 
    
    
}
