package nc.ccas.gasel.model.aides.auto;

/** Class _TypeArrete was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _TypeArrete extends org.apache.cayenne.CayenneDataObject {

    public static final String ACTIF_PROPERTY = "actif";
    public static final String ARTICLE1_PROPERTY = "article1";
    public static final String AVEC_FACTURES_PROPERTY = "avecFactures";
    public static final String INFOS_IMPUTATION_PROPERTY = "infosImputation";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String LOCKED_PROPERTY = "locked";
    public static final String TITRE_PROPERTY = "titre";

    public static final String ID_PK_COLUMN = "id";

    public void setActif(Boolean actif) {
        writeProperty("actif", actif);
    }
    public Boolean getActif() {
        return (Boolean)readProperty("actif");
    }
    
    
    public void setArticle1(String article1) {
        writeProperty("article1", article1);
    }
    public String getArticle1() {
        return (String)readProperty("article1");
    }
    
    
    public void setAvecFactures(Boolean avecFactures) {
        writeProperty("avecFactures", avecFactures);
    }
    public Boolean getAvecFactures() {
        return (Boolean)readProperty("avecFactures");
    }
    
    
    public void setInfosImputation(String infosImputation) {
        writeProperty("infosImputation", infosImputation);
    }
    public String getInfosImputation() {
        return (String)readProperty("infosImputation");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }
    
    
    public void setTitre(String titre) {
        writeProperty("titre", titre);
    }
    public String getTitre() {
        return (String)readProperty("titre");
    }
    
    
}
