package nc.ccas.gasel.model.aides.auto;

/** Class _UsageBon was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _UsageBon extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -7719146060270835269L;
	public static final String DATE_PROPERTY = "date";
    public static final String MONTANT_UTILISE_PROPERTY = "montantUtilise";
    public static final String ARRETE_PROPERTY = "arrete";
    public static final String BON_PROPERTY = "bon";
    public static final String FACTURE_PROPERTY = "facture";

    public static final String BON_ID_PK_COLUMN = "bon_id";

    public void setDate(java.util.Date date) {
        writeProperty("date", date);
    }
    public java.util.Date getDate() {
        return (java.util.Date)readProperty("date");
    }
    
    
    public void setMontantUtilise(Integer montantUtilise) {
        writeProperty("montantUtilise", montantUtilise);
    }
    public Integer getMontantUtilise() {
        return (Integer)readProperty("montantUtilise");
    }
    
    
    public void setArrete(nc.ccas.gasel.model.aides.Arrete arrete) {
        setToOneTarget("arrete", arrete, true);
    }

    public nc.ccas.gasel.model.aides.Arrete getArrete() {
        return (nc.ccas.gasel.model.aides.Arrete)readProperty("arrete");
    } 
    
    
    public void setBon(nc.ccas.gasel.model.aides.Bon bon) {
        setToOneTarget("bon", bon, true);
    }

    public nc.ccas.gasel.model.aides.Bon getBon() {
        return (nc.ccas.gasel.model.aides.Bon)readProperty("bon");
    } 
    
    
    public void setFacture(nc.ccas.gasel.model.aides.PartieFacture facture) {
        setToOneTarget("facture", facture, true);
    }

    public nc.ccas.gasel.model.aides.PartieFacture getFacture() {
        return (nc.ccas.gasel.model.aides.PartieFacture)readProperty("facture");
    } 
    
    
}
