package nc.ccas.gasel.model.budget.auto;

import java.util.List;

import nc.ccas.gasel.model.budget.BudgetSecteurAide;

/** Class _BudgetImpMensuel was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _BudgetImpMensuel extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -1500445646465488792L;
	public static final String MOIS_PROPERTY = "mois";
    public static final String MONTANT_PROPERTY = "montant";
    public static final String RESTANT_PROPERTY = "restant";
    public static final String PAR_SECTEUR_PROPERTY = "parSecteur";
    public static final String PARENT_PROPERTY = "parent";

    public static final String ID_PK_COLUMN = "id";

    public void setMois(Short mois) {
        writeProperty("mois", mois);
    }
    public Short getMois() {
        return (Short)readProperty("mois");
    }
    
    
    public void setMontant(Double montant) {
        writeProperty("montant", montant);
    }
    public Double getMontant() {
        return (Double)readProperty("montant");
    }
    
    
    public void setRestant(Double restant) {
        writeProperty("restant", restant);
    }
    public Double getRestant() {
        return (Double)readProperty("restant");
    }
    
    
    public void addToParSecteur(nc.ccas.gasel.model.budget.BudgetSecteurAide obj) {
        addToManyTarget("parSecteur", obj, true);
    }
    public void removeFromParSecteur(nc.ccas.gasel.model.budget.BudgetSecteurAide obj) {
        removeToManyTarget("parSecteur", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.budget.BudgetSecteurAide> getParSecteur() {
        return (List<BudgetSecteurAide>)readProperty("parSecteur");
    }
    
    
    public void setParent(nc.ccas.gasel.model.budget.BudgetImpAnnuel parent) {
        setToOneTarget("parent", parent, true);
    }

    public nc.ccas.gasel.model.budget.BudgetImpAnnuel getParent() {
        return (nc.ccas.gasel.model.budget.BudgetImpAnnuel)readProperty("parent");
    } 
    
    
}
