package nc.ccas.gasel.model.budget.auto;

import java.util.List;

import nc.ccas.gasel.model.budget.BudgetImpAnnuel;

/** Class _BudgetAnnuel was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _BudgetAnnuel extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1314883685437504606L;
	public static final String ANNEE_PROPERTY = "annee";
    public static final String MONTANT_PROPERTY = "montant";
    public static final String RESTANT_PROPERTY = "restant";
    public static final String VALIDATION_PROPERTY = "validation";
    public static final String BUDGETS_IMPUTATION_PROPERTY = "budgetsImputation";

    public static final String ID_PK_COLUMN = "id";

    public void setAnnee(Short annee) {
        writeProperty("annee", annee);
    }
    public Short getAnnee() {
        return (Short)readProperty("annee");
    }
    
    
    public void setMontant(Double montant) {
        writeProperty("montant", montant);
    }
    public Double getMontant() {
        return (Double)readProperty("montant");
    }
    
    
    public void setRestant(Double restant) {
        writeProperty("restant", restant);
    }
    public Double getRestant() {
        return (Double)readProperty("restant");
    }
    
    
    public void setValidation(java.util.Date validation) {
        writeProperty("validation", validation);
    }
    public java.util.Date getValidation() {
        return (java.util.Date)readProperty("validation");
    }
    
    
    public void addToBudgetsImputation(nc.ccas.gasel.model.budget.BudgetImpAnnuel obj) {
        addToManyTarget("budgetsImputation", obj, true);
    }
    public void removeFromBudgetsImputation(nc.ccas.gasel.model.budget.BudgetImpAnnuel obj) {
        removeToManyTarget("budgetsImputation", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.budget.BudgetImpAnnuel> getBudgetsImputation() {
        return (List<BudgetImpAnnuel>)readProperty("budgetsImputation");
    }
    
    
}
