package nc.ccas.gasel.model.budget.auto;

/** Class _NatureAideFournisseur was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _NatureAideFournisseur extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -5179975859141342042L;
	public static final String FOURNISSEUR_PROPERTY = "fournisseur";
    public static final String NATURE_PROPERTY = "nature";

    public static final String CODE_FOURNISSEUR_PK_COLUMN = "code_fournisseur";
    public static final String NATURE_ID_PK_COLUMN = "nature_id";

    public void setFournisseur(nc.ccas.gasel.model.mairie.FournisseurMairie fournisseur) {
        setToOneTarget("fournisseur", fournisseur, true);
    }

    public nc.ccas.gasel.model.mairie.FournisseurMairie getFournisseur() {
        return (nc.ccas.gasel.model.mairie.FournisseurMairie)readProperty("fournisseur");
    } 
    
    
    public void setNature(nc.ccas.gasel.model.budget.NatureAide nature) {
        setToOneTarget("nature", nature, true);
    }

    public nc.ccas.gasel.model.budget.NatureAide getNature() {
        return (nc.ccas.gasel.model.budget.NatureAide)readProperty("nature");
    } 
    
    
}
