package nc.ccas.gasel.model.budget.auto;

import java.util.List;

/** Class _NatureAide was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _NatureAide extends org.apache.cayenne.CayenneDataObject {

    public static final String ACTIF_PROPERTY = "actif";
    public static final String CODE_PROPERTY = "code";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String LOCKED_PROPERTY = "locked";
    public static final String FOURNISSEURS_PROPERTY = "fournisseurs";
    public static final String IMPUTATION_PROPERTY = "imputation";
    public static final String PARENT_PROPERTY = "parent";
    public static final String PUBLICS_CONCERNES_PROPERTY = "publicsConcernes";
    public static final String TYPE_ARRETE_PROPERTY = "typeArrete";

    public static final String ID_PK_COLUMN = "id";

    public void setActif(Boolean actif) {
        writeProperty("actif", actif);
    }
    public Boolean getActif() {
        return (Boolean)readProperty("actif");
    }
    
    
    public void setCode(Integer code) {
        writeProperty("code", code);
    }
    public Integer getCode() {
        return (Integer)readProperty("code");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }
    
    
    public void addToFournisseurs(nc.ccas.gasel.model.mairie.FournisseurMairie obj) {
        addToManyTarget("fournisseurs", obj, true);
    }
    public void removeFromFournisseurs(nc.ccas.gasel.model.mairie.FournisseurMairie obj) {
        removeToManyTarget("fournisseurs", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.mairie.FournisseurMairie> getFournisseurs() {
        return (List)readProperty("fournisseurs");
    }
    
    
    public void setImputation(nc.ccas.gasel.model.budget.Imputation imputation) {
        setToOneTarget("imputation", imputation, true);
    }

    public nc.ccas.gasel.model.budget.Imputation getImputation() {
        return (nc.ccas.gasel.model.budget.Imputation)readProperty("imputation");
    } 
    
    
    public void setParent(nc.ccas.gasel.model.budget.SecteurAide parent) {
        setToOneTarget("parent", parent, true);
    }

    public nc.ccas.gasel.model.budget.SecteurAide getParent() {
        return (nc.ccas.gasel.model.budget.SecteurAide)readProperty("parent");
    } 
    
    
    public void addToPublicsConcernes(nc.ccas.gasel.model.budget.TypePublicNature obj) {
        addToManyTarget("publicsConcernes", obj, true);
    }
    public void removeFromPublicsConcernes(nc.ccas.gasel.model.budget.TypePublicNature obj) {
        removeToManyTarget("publicsConcernes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.budget.TypePublicNature> getPublicsConcernes() {
        return (List)readProperty("publicsConcernes");
    }
    
    
    public void setTypeArrete(nc.ccas.gasel.model.aides.TypeArrete typeArrete) {
        setToOneTarget("typeArrete", typeArrete, true);
    }

    public nc.ccas.gasel.model.aides.TypeArrete getTypeArrete() {
        return (nc.ccas.gasel.model.aides.TypeArrete)readProperty("typeArrete");
    } 
    
    
}
