package nc.ccas.gasel.model.budget.auto;

import java.util.List;

import nc.ccas.gasel.model.budget.NatureAide;

/** Class _SecteurAide was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _SecteurAide extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2488460718664347654L;
	public static final String ACTIF_PROPERTY = "actif";
    public static final String CODE_PROPERTY = "code";
    public static final String LIBELLE_PROPERTY = "libelle";
    public static final String LOCKED_PROPERTY = "locked";
    public static final String NATURES_PROPERTY = "natures";

    public static final String ID_PK_COLUMN = "id";

    public void setActif(Boolean actif) {
        writeProperty("actif", actif);
    }
    public Boolean getActif() {
        return (Boolean)readProperty("actif");
    }
    
    
    public void setCode(Integer code) {
        writeProperty("code", code);
    }
    public Integer getCode() {
        return (Integer)readProperty("code");
    }
    
    
    public void setLibelle(String libelle) {
        writeProperty("libelle", libelle);
    }
    public String getLibelle() {
        return (String)readProperty("libelle");
    }
    
    
    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }
    
    
    public void addToNatures(nc.ccas.gasel.model.budget.NatureAide obj) {
        addToManyTarget("natures", obj, true);
    }
    public void removeFromNatures(nc.ccas.gasel.model.budget.NatureAide obj) {
        removeToManyTarget("natures", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<nc.ccas.gasel.model.budget.NatureAide> getNatures() {
        return (List<NatureAide>)readProperty("natures");
    }
    
    
}
