package nc.ccas.gasel.model.budget.auto;

/** Class _TypePublicNature was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _TypePublicNature extends org.apache.cayenne.CayenneDataObject {

    /**
	 * 
	 */
	private static final long serialVersionUID = 2293125221946592761L;
	public static final String NATURE_AIDE_PROPERTY = "natureAide";
    public static final String TYPE_PUBLIC_PROPERTY = "typePublic";

    public static final String NATURE_AIDE_ID_PK_COLUMN = "nature_aide_id";
    public static final String TYPE_PUBLIC_ID_PK_COLUMN = "type_public_id";

    public void setNatureAide(nc.ccas.gasel.model.budget.NatureAide natureAide) {
        setToOneTarget("natureAide", natureAide, true);
    }

    public nc.ccas.gasel.model.budget.NatureAide getNatureAide() {
        return (nc.ccas.gasel.model.budget.NatureAide)readProperty("natureAide");
    } 
    
    
    public void setTypePublic(nc.ccas.gasel.model.core.enums.TypePublic typePublic) {
        setToOneTarget("typePublic", typePublic, true);
    }

    public nc.ccas.gasel.model.core.enums.TypePublic getTypePublic() {
        return (nc.ccas.gasel.model.core.enums.TypePublic)readProperty("typePublic");
    } 
    
    
}
